import type {Page} from '@playwright/test';
export const conversationRows=[{id:'synthetic-alpha',customerId:'alpha',customerName:'测试客户 Alpha',customerCode:'FIX-A',currency:'SGD',phone:'+6500000001',preview:'Synthetic Alpha order message',lastMessageAt:'2026-10-01T00:10:00Z',orderStatus:'DRAFT'},{id:'synthetic-beta',customerId:'beta',customerName:'测试客户 Beta',customerCode:'FIX-B',currency:'SGD',phone:'+6500000002',preview:'Synthetic Beta question',lastMessageAt:'2026-10-01T00:05:00Z'}];
export const fixtureState=(id:string)=>{const row=conversationRows.find(c=>c.id===id)!;return{id,customer:row.customerName,phone:row.phone,conversation:{...row,accountId:'test-only-account'},messages:[{from:'customer',text:row.preview,occurredAt:row.lastMessageAt},{from:'ai',text:id==='synthetic-alpha'?'Synthetic recorded reply; no live model call.':'Synthetic Beta-only reply.',occurredAt:row.lastMessageAt}],activities:[],timeline:[],quote:id==='synthetic-alpha'?{no:'FIX-Q-ALPHA',status:'SENT',total:24,lines:[{rowItemNo:1,stockCode:'FIX-SKU',description:'Synthetic notebook',quantity:2,uom:'EA',unitPrice:12,subtotal:24}],deliveryDate:'2026-10-02',sourceMessageId:'fixture-inbound'}:undefined,so:id==='synthetic-alpha'?{no:'FIX-SO-ALPHA',status:'DRAFT',quoteNo:'FIX-Q-ALPHA',total:24}:undefined,uiState:{authority:{migrationState:'V1_ONLY',workspaceWriter:'LEGACY'},boundary:{aiCutoff:'SALES_ORDER.DRAFT'}},operational:{startupMode:'paused',modelMode:'deterministic'}}};
export async function useInboxFixtures(page:Page,options:{delayAlpha?:boolean;empty?:boolean;failList?:()=>boolean}={}){
 await page.route('**/health',r=>r.fulfill({json:{startupMode:'paused',channel:'whatsapp-qr',modelMode:'deterministic',agentRuntime:'legacy-or-disabled',v2TrafficEnabled:false,runtimeMode:'V1'}}));
 await page.route('**/api/conversations',r=>options.failList?.()?r.fulfill({status:503,json:{error:'TEST_ONLY_FAILURE'}}):r.fulfill({json:{conversations:options.empty?[]:conversationRows}}));
 await page.route('**/api/state?*',async r=>{const id=new URL(r.request().url()).searchParams.get('conversationId')!;if(options.delayAlpha&&id==='synthetic-alpha')await new Promise(resolve=>setTimeout(resolve,750));try{await r.fulfill({json:fixtureState(id)})}catch{}});
 await page.route('**/api/agent-trace*',r=>r.fulfill({json:{endpointCalls:[],turns:[],actions:[]}}));
 await page.route('**/api/staff/session',r=>r.fulfill({json:{authenticated:false}}));await page.route('**/api/agent-harness',r=>r.fulfill({json:{engine:'disabled',tools:[]}}));
 await page.route('**/api/channel/status',r=>r.fulfill({json:{mode:'whatsapp-qr',status:'disconnected',qrReady:false,qr:null,pairingControl:{enabled:true,processingPaused:true}}}));
}
