import {test,expect} from '@playwright/test';
import {useInboxFixtures} from './inbox-fixtures';
test('desktop inbox matches selected customer/chat/order and rejects stale asynchronous responses',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await useInboxFixtures(page,{delayAlpha:true});let posts=0;page.on('request',r=>{if(r.method()==='POST')posts++});
 await page.goto('/');await expect(page.locator('#inbox')).toContainText('测试客户 Alpha');await page.locator('[data-conversation-id="synthetic-beta"]').click();await expect(page.locator('#selectedName')).toHaveText('测试客户 Beta');await expect(page.locator('#printReview')).toHaveAttribute('href','/api/print?conversationId=synthetic-beta');await expect(page.locator('#chat')).toContainText('Synthetic Beta-only reply');await expect(page.locator('#customerCard')).toContainText('FIX-B');await expect(page.locator('#doc')).not.toContainText('FIX-Q-ALPHA');await expect(page.locator('#so')).not.toContainText('FIX-SO-ALPHA');await page.waitForTimeout(850);await expect(page.locator('#selectedName')).toHaveText('测试客户 Beta');
 await page.locator('[data-conversation-id="synthetic-alpha"]').click();await expect(page.locator('#doc')).toContainText('FIX-Q-ALPHA');await expect(page.locator('#so')).toContainText('FIX-SO-ALPHA');await expect(page.locator('#post')).toBeDisabled();await expect(page.locator('#composerText')).toBeDisabled();expect(posts).toBe(0);
 await page.screenshot({path:'../migration-evidence/inbox-after-desktop.png',fullPage:true});
});
test('mobile list/chat/details/back restore correct context, keyboard focus and history without horizontal overflow',async({page})=>{
 await page.setViewportSize({width:390,height:844});await useInboxFixtures(page);await page.goto('/');await expect(page.locator('#conversationPane')).toBeVisible();await expect(page.locator('#chatPane')).not.toBeVisible();await page.locator('[data-conversation-id="synthetic-alpha"]').click();await expect(page.locator('#chatPane')).toBeVisible();await expect(page.locator('#selectedName')).toHaveText('测试客户 Alpha');await expect(page.locator('#selectedName')).toBeFocused();await page.screenshot({path:'../migration-evidence/inbox-after-mobile.png',fullPage:true});
 await page.locator('#detailsToggle').click();await expect(page.locator('#detailPane')).toBeVisible();await expect(page.locator('#customerCard')).toContainText('FIX-A');await expect(page.locator('#detailBack')).toBeFocused();await page.locator('#detailBack').click();await expect(page.locator('#chatPane')).toBeVisible();await page.locator('#chatBack').click();await expect(page.locator('#conversationPane')).toBeVisible();await page.locator('[data-conversation-id="synthetic-beta"]').click();await expect(page.locator('#selectedName')).toHaveText('测试客户 Beta');await page.goBack();await expect(page.locator('#conversationPane')).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('tablet detail drawer closes to the selected chat and settings retain protected reconnect controls',async({page})=>{
 await page.setViewportSize({width:1024,height:900});await useInboxFixtures(page);await page.goto('/');await expect(page.locator('#selectedName')).toHaveText('测试客户 Alpha');await expect(page.locator('#detailPane')).not.toBeVisible();await page.locator('#detailsToggle').click();await expect(page.locator('#detailPane')).toBeVisible();await page.locator('#closeDetails').click();await expect(page.locator('#detailPane')).not.toBeVisible();await page.locator('#navSettings').click();await expect(page.locator('#regenerateQr')).toBeVisible();await expect(page.locator('#settingsView')).toContainText('消息处理、AI、自动回复保持暂停');await expect(page.locator('#simulatorControls')).not.toBeVisible();
});
test('empty, search-empty and retry states are truthful and clear previous content',async({page})=>{
 let fail=true;await useInboxFixtures(page,{failList:()=>fail});await page.goto('/');await expect(page.locator('#globalError')).toBeVisible();fail=false;await page.locator('#retryLoad').click();await expect(page.locator('#inbox')).toContainText('测试客户 Alpha');await page.locator('#conversationSearch').fill('no-fixture-match');await expect(page.locator('#inbox')).toContainText('No matching conversations');
});
test('no conversations does not invent messages, customers or order drafts',async({page})=>{
 await useInboxFixtures(page,{empty:true});await page.goto('/');await expect(page.locator('#inbox')).toContainText('No conversations yet');await expect(page.locator('#chat')).toContainText('Select a conversation');await expect(page.locator('#customerCard')).not.toContainText('Alpha');await expect(page.locator('#composerSend')).toBeDisabled();await expect(page.locator('#printReview')).not.toBeVisible();
});

test('SVG controls preserve accessible names, native keyboard activation and disclosure state',async({page})=>{
 await useInboxFixtures(page);await page.goto('/');
 for(const id of ['navInbox','navActivity','navSettings','headerSettings','detailsToggle','composerSend','chatBack','detailBack','closeDetails']){await expect(page.locator(`#${id} svg`)).toHaveAttribute('aria-hidden','true');await expect(page.locator(`#${id}`)).toHaveAttribute('aria-label',/.+/)}
 const sprite=await page.request.get('/icons.svg');expect(sprite.ok()).toBe(true);expect(await sprite.text()).toContain('id="settings"');
 await page.locator('#navSettings').focus();await page.keyboard.press('Enter');await expect(page.locator('#settingsView')).toBeVisible();await expect(page.locator('#regenerateQr')).toBeVisible();await page.locator('#navInbox').focus();await page.keyboard.press('Enter');await expect(page.locator('#chatPane')).toBeVisible();
 const summary=page.locator('#doc summary');await expect(summary.locator('svg')).toBeVisible();await summary.focus();await page.keyboard.press('Enter');await expect(page.locator('#doc details')).toHaveAttribute('open','');
 await page.screenshot({path:'../migration-evidence/svg-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.locator('[data-conversation-id="synthetic-alpha"]').click();await expect(page.locator('#chatPane')).toBeVisible();await page.screenshot({path:'../migration-evidence/svg-mobile.png',fullPage:true});
});

test('settings reflects active scoped inquiry provider metadata without paused claims or credentials',async({page})=>{
 await useInboxFixtures(page);
 await page.route('**/health',r=>r.fulfill({json:{startupMode:'active',channel:'whatsapp-qr',modelMode:'demo-gpt',agentRuntime:'pi-harness',runtimeMode:'V2',inquiry:{enabled:true,boundary:'SALES_ORDER.DRAFT'},llm:{provider:'demo-gpt',model:'demo-fast',runtime:'pi-harness-node',billingMode:'managed-demo-gateway'}}}));
 await page.route('**/api/channel/status',r=>r.fulfill({json:{mode:'whatsapp-qr',status:'connected',qrReady:false,qr:null,pairingControl:{enabled:false,processingPaused:false}}}));
 await page.goto('/');await page.locator('#navSettings').click();await expect(page.locator('#settingsProcessingCopy')).toContainText('咨询处理已启用');await expect(page.locator('#settingsProcessingCopy')).not.toContainText('保持暂停');await expect(page.locator('#runtime')).toContainText('demo-gpt');await expect(page.locator('#runtime')).toContainText('demo-fast');await expect(page.locator('#runtime')).toContainText('pi-harness-node');await expect(page.locator('#runtime')).toContainText('managed-demo-gateway');await expect(page.locator('#migrationBanner')).not.toBeVisible();await expect(page.locator('#pairingControls')).not.toBeVisible();await expect(page.locator('#simulatorControls')).not.toBeVisible();await expect(page.locator('#settingsView')).not.toContainText('Bearer ');
});
