import test from 'node:test';
import assert from 'node:assert/strict';
import { CommerceService } from '../src/commerce.js';
import { SimulatedChannel } from '../src/channels.js';
import { createStaffCapabilityAuthority } from '../src/staff-auth.js';
import { scriptedSemanticAgentFactory, goldenOffer, wingsOffer, prepareQuote, acceptQuote } from './semantic-agent.js';

const msg=(text:string,id:string,extra:any={})=>({channel:'whatsapp' as const,accountId:'demo-account',externalMessageId:id,conversationId:'conv-001',sender:{externalId:'+6591110001',phone:'+6591110001'},type:'text' as const,text,occurredAt:new Date().toISOString(),...extra});
const goldenOrder='Hi, same as last week. Ayam 10 ctn, red one 5 ctn. Tomorrow deliver can?';
const goldenFactory=()=>scriptedSemanticAgentFactory([goldenOffer(),prepareQuote,acceptQuote]);
async function flow(){const channel=new SimulatedChannel();await channel.connect();const authority=createStaffCapabilityAuthority();const service=new CommerceService(undefined,channel,authority.verify,goldenFactory());const capability=authority.issue('test-staff');service.resetAndSeed();await service.inbound(msg(goldenOrder,'m1'));await service.inbound(msg('Yes please.','m2'));await service.inbound(msg('OK confirm.','m3'));return {service,channel,capability};}

test('persistent SQLite golden flow and exact evidence',async()=>{const {service}=await flow();const s=service.state();assert.equal(s.quote?.no,'QT-000001');assert.equal(s.quote?.status,'ACCEPTED');assert.equal(s.so?.no,'SO-000052');assert.equal(s.so?.status,'DRAFT');assert.equal(service.database.db.prepare('SELECT count(*) n FROM erp_evidence').get().n,14);assert.equal(service.database.db.prepare('SELECT count(*) n FROM erp_evidence e JOIN agent_tool_calls a ON a.id=e.tool_call_id').get().n,14);assert.equal(service.database.db.prepare('SELECT count(*) n FROM erp_evidence WHERE length(lookup_key)=64').get().n,14);assert.equal(service.database.db.prepare('SELECT count(*) n FROM quotation_acceptances').get().n,1);});
test('Yes please is not acceptance; duplicate inbound is idempotent',async()=>{const {service}=await flow();assert.equal(service.state().quote?.status,'ACCEPTED');const before=service.database.db.prepare('SELECT count(*) n FROM messages').get().n;await service.inbound(msg('OK confirm.','m3'));assert.equal(service.database.db.prepare('SELECT count(*) n FROM messages').get().n,before);});
test('plain Yes after stock offer prepares quotation but never accepts it',async()=>{const channel=new SimulatedChannel();await channel.connect();const service=new CommerceService(undefined,channel,undefined,scriptedSemanticAgentFactory([goldenOffer(),prepareQuote]));service.resetAndSeed();await service.inbound(msg(goldenOrder,'yes-order'));assert.equal(service.state().quote,undefined);await service.inbound(msg('Yes','yes-prepare'));assert.equal(service.state().quote?.status,'SENT');assert.equal(service.state().so,undefined);assert.equal(service.database.db.prepare('SELECT count(*) n FROM quotation_acceptances').get().n,0);});
test('wrong sender, forwarded and unsupported media are clarified',async()=>{const channel=new SimulatedChannel();await channel.connect();const service=new CommerceService(undefined,channel,undefined,scriptedSemanticAgentFactory([goldenOffer(),prepareQuote]));service.resetAndSeed();await service.inbound(msg(goldenOrder,'a'));await service.inbound(msg('Yes please.','b'));await service.inbound(msg('OK confirm.','c',{sender:{externalId:'+6599999999'},forwarding:{isForwarded:true}}));assert.equal(service.state().so,undefined);await service.inbound({...msg('OK confirm.','d'),forwarding:{isForwarded:true}});assert.equal(service.state().so,undefined);await service.inbound({...msg(undefined as any,'media',{type:'image',media:{mimeType:'image/png',externalRef:'ref'}})});assert.equal(service.state().so,undefined);});
test('staff boundary is opaque-capability based, explicitly targeted, ordered, atomic and idempotent',async()=>{const {service,capability}=await flow();assert.throws(()=>service.staff('post','demo-staff-capability','p0','confirmed','SO-000052'),/STAFF_AUTH_REQUIRED/);assert.equal(service.state().so?.status,'DRAFT');assert.throws(()=>service.staff('post',capability,'p0','confirmed',''),/SALES_ORDER_REQUIRED/);assert.throws(()=>service.staff('post',capability,'p0',undefined,'SO-000052'),/DOUBLE_CONFIRMATION_REQUIRED/);service.staff('post',capability,'p1','Customer explicitly reconfirmed this order','SO-000052');assert.equal(service.state().so?.status,'POSTED');service.staff('post',capability,'p1','Customer explicitly reconfirmed this order','SO-000052');assert.throws(()=>service.staff('do',capability,'d0',undefined,'SO-000052'),/INVALID_TRANSITION/);service.staff('confirm',capability,'c1',undefined,'SO-000052');service.staff('do',capability,'d1',undefined,'SO-000052');assert.equal(service.state().so?.status,'DO_READY');assert.equal(Number(service.database.db.prepare("SELECT quantity_base FROM stock_balances WHERE product_id='FRANK-RED-1KG'").get().quantity_base),10);});
test('shortage blocks post without deduction',async()=>{const {service,capability}=await flow();service.database.db.prepare("UPDATE stock_balances SET quantity_base=4 WHERE product_id='FRANK-RED-1KG'").run();assert.throws(()=>service.staff('post',capability,'short','Customer explicitly reconfirmed this order','SO-000052'),/STOCK_SHORTAGE/);assert.equal(service.state().so?.status,'DRAFT');assert.equal(Number(service.database.db.prepare("SELECT quantity_base FROM stock_balances WHERE product_id='FCH-WHOLE-12'").get().quantity_base),820);});
test('expiry and DB-scoped sender/account guards fail closed',async()=>{const channel=new SimulatedChannel();await channel.connect();const service=new CommerceService(undefined,channel,undefined,scriptedSemanticAgentFactory([goldenOffer(),prepareQuote]));service.resetAndSeed();await service.inbound(msg(goldenOrder,'expired-1'));await service.inbound(msg('Yes please.','expired-2'));service.database.db.prepare("UPDATE quotations SET valid_until='2000-01-01T00:00:00Z'").run();await service.inbound(msg('OK confirm.','expired-3'));assert.equal(service.state().quote?.status,'EXPIRED');const s=new CommerceService(undefined,channel,undefined,scriptedSemanticAgentFactory([goldenOffer(),prepareQuote]));s.resetAndSeed();await s.inbound(msg(goldenOrder,'x1'));await s.inbound(msg('Yes please.','x2'));await s.inbound({...msg('OK confirm.','x3'),accountId:'wrong-account'});assert.equal(s.state().so,undefined);});
test('unknown outbound never blind-resends and crash recovery reconciles without resend',async()=>{const unknown=new SimulatedChannel([{status:'unknown',clientMessageId:'x'}]);await unknown.connect();const s=new CommerceService(undefined,unknown,undefined,scriptedSemanticAgentFactory([goldenOffer(),prepareQuote]));s.resetAndSeed();await s.inbound(msg(goldenOrder,'u1'));await s.inbound(msg('Yes please.','u2'));assert.equal(unknown.sendCount,1);await s.sendQuote('missing').catch(()=>{});assert.equal(unknown.sendCount,1);const channel=new SimulatedChannel();await channel.connect();const c=new CommerceService(undefined,channel,undefined,scriptedSemanticAgentFactory([goldenOffer(),prepareQuote]));c.resetAndSeed();c.setCrashAfterSubmittedBeforeFinalize();await c.inbound(msg(goldenOrder,'c1'));await assert.rejects(()=>c.inbound(msg('Yes please.','c2')),/INJECTED_CRASH/);assert.equal(channel.sendCount,1);const restarted=new CommerceService(c.database,channel);await restarted.reconcileOutbound();assert.equal(channel.sendCount,1);assert.equal(restarted.state().quote?.status,'SENT');});
test('replacement supersedes old quote and preserves one SO per accepted quote',async()=>{const channel=new SimulatedChannel();await channel.connect();const service=new CommerceService(undefined,channel,undefined,scriptedSemanticAgentFactory([goldenOffer(),prepareQuote,goldenOffer(),acceptQuote]));service.resetAndSeed();await service.inbound(msg(goldenOrder,'r1'));await service.inbound(msg('Yes please.','r2'));await service.inbound(msg(goldenOrder,'r3'));const qs=service.database.db.prepare('SELECT status FROM quotations ORDER BY rowid').all() as any[];assert.deepEqual(qs.map(x=>x.status),['SUPERSEDED','SENT']);assert.equal(channel.sendCount,2);await service.inbound(msg('OK confirm.','r4'));assert.equal(service.database.db.prepare("SELECT count(*) n FROM sales_orders WHERE status='DRAFT'").get().n,1);});

test('QR external JID maps only with explicit phone binding and outbound preserves JID',async()=>{class QrLikeChannel extends SimulatedChannel{readonly unofficial=true}const channel=new QrLikeChannel();await channel.connect();const service=new CommerceService(undefined,channel,undefined,scriptedSemanticAgentFactory([goldenOffer(),prepareQuote]));service.resetAndSeed();const old=process.env.WHATSAPP_QR_CUSTOMER_PHONE;process.env.WHATSAPP_QR_CUSTOMER_PHONE='+65 9111 0001';try{const qr=msg(goldenOrder,'qr-1',{conversationId:'6591110001@s.whatsapp.net',sender:{externalId:'6591110001@s.whatsapp.net',phone:'+6591110001'}});await service.inbound(qr);const row=service.database.db.prepare("SELECT id,external_conversation_id,customer_id FROM conversations WHERE external_conversation_id=?").get('6591110001@s.whatsapp.net') as any;assert.equal(row.customer_id,'CUST-001');await service.inbound({...qr,externalMessageId:'qr-2',text:'Yes please.'});assert.equal(channel.sent.at(-1)?.conversationId,'6591110001@s.whatsapp.net');}finally{if(old===undefined)delete process.env.WHATSAPP_QR_CUSTOMER_PHONE;else process.env.WHATSAPP_QR_CUSTOMER_PHONE=old}});

test('unknown QR sender is persisted but fails closed and gets bounded clarification',async()=>{class QrLikeChannel extends SimulatedChannel{readonly unofficial=true}const channel=new QrLikeChannel();await channel.connect();const service=new CommerceService(undefined,channel,undefined,scriptedSemanticAgentFactory([goldenOffer(),prepareQuote]));service.resetAndSeed();await service.inbound(msg('same as last week','unknown',{conversationId:'unknown@s.whatsapp.net',sender:{externalId:'unknown@s.whatsapp.net',phone:'+6599999999'}}));const conv=service.database.db.prepare("SELECT id,customer_id FROM conversations WHERE external_conversation_id='unknown@s.whatsapp.net'").get() as any;assert.ok(conv.id);assert.equal(conv.customer_id,null);assert.equal(service.database.db.prepare("SELECT count(*) n FROM messages WHERE external_message_id='unknown'").get().n,1);assert.equal(service.database.db.prepare('SELECT count(*) n FROM quotations WHERE source_conversation_id=?').get(conv.id).n,0);assert.match(channel.sent.at(-1)?.text??'',/linked customer account/i)});

test('service-level acceptance guard rejects vague model intent even if invoked directly',async()=>{const channel=new SimulatedChannel();await channel.connect();const service=new CommerceService(undefined,channel,undefined,scriptedSemanticAgentFactory([goldenOffer(),prepareQuote]));service.resetAndSeed();await service.inbound(msg(goldenOrder,'guard-1'));await service.inbound(msg('Yes please.','guard-2'));const q=service.database.db.prepare("SELECT * FROM quotations WHERE status='SENT'").get() as any;(service as any).accept(msg('Great, thanks!','guard-vague'),q);assert.equal(service.database.db.prepare('SELECT status FROM quotations WHERE id=?').get(q.id).status,'SENT');assert.equal(service.database.db.prepare('SELECT count(*) n FROM quotation_acceptances WHERE quotation_id=?').get(q.id).n,0)});

test('staff post aggregates repeated SKU demand before any stock deduction',async()=>{const {service,capability}=await flow();const so=service.database.db.prepare("SELECT * FROM sales_orders WHERE status='DRAFT'").get() as any;const line=service.database.db.prepare("SELECT * FROM sales_order_lines WHERE sales_order_id=? AND product_id='FCH-WHOLE-12'").get(so.id) as any;service.database.db.prepare('INSERT INTO sales_order_lines VALUES(?,?,?,?,?,?,?,?,?,?,?)').run('dup-fch',so.id,line.source_quotation_line_id,99,line.product_id,line.stock_code,line.stock_description,'75',line.uom,line.unit_price_cents,75*line.unit_price_cents);assert.throws(()=>service.staff('post',capability,'aggregate-shortage','Customer reconfirmed','SO-000052'),/STOCK_SHORTAGE/);assert.equal(Number(service.database.db.prepare("SELECT quantity_base FROM stock_balances WHERE product_id='FCH-WHOLE-12'").get().quantity_base),820);assert.equal(service.state().so?.status,'DRAFT')});

test('quotation available stock stays frozen after staff post',async()=>{const {service,capability}=await flow();assert.deepEqual(service.state().quote?.lines.map((line:any)=>line.available),[82,6]);service.staff('post',capability,'frozen-stock','Customer reconfirmed','SO-000052');assert.deepEqual(service.state().quote?.lines.map((line:any)=>line.available),[82,6]);assert.equal(Number(service.database.db.prepare("SELECT quantity_base FROM stock_balances WHERE product_id='FRANK-RED-1KG'").get().quantity_base),10)});

test('reconcile not_found permits one same-client-id quotation retry',async()=>{const channel=new SimulatedChannel([{status:'unknown',clientMessageId:'x'},{status:'submitted',externalMessageId:'retry-submitted',submittedAt:new Date().toISOString()}],[{status:'not_found'}]);await channel.connect();const service=new CommerceService(undefined,channel,undefined,scriptedSemanticAgentFactory([goldenOffer(),prepareQuote]));service.resetAndSeed();await service.inbound(msg(goldenOrder,'retry-1'));await service.inbound(msg('Yes please.','retry-2'));const q=service.database.db.prepare('SELECT id,status FROM quotations ORDER BY rowid DESC LIMIT 1').get() as any;assert.equal(q.status,'DRAFT');assert.equal(channel.sendCount,1);const firstClient=channel.clientMessageIds[0];await service.reconcileOutbound();const failed=service.database.db.prepare('SELECT status,last_error,attempt_count FROM outbound_messages WHERE entity_id=?').get(q.id) as any;assert.equal(failed.status,'FAILED');assert.equal(failed.last_error,'retryable:not_found');await service.sendQuote(q.id);assert.equal(channel.sendCount,2);assert.equal(channel.clientMessageIds[1],firstClient);const final=service.database.db.prepare('SELECT status,attempt_count FROM outbound_messages WHERE entity_id=?').get(q.id) as any;assert.equal(final.status,'SUBMITTED');assert.equal(final.attempt_count,2);assert.equal(service.database.db.prepare('SELECT status FROM quotations WHERE id=?').get(q.id).status,'SENT');await service.sendQuote(q.id);assert.equal(channel.sendCount,2)});

test('terminal quotation send failure never retries',async()=>{const channel=new SimulatedChannel([{status:'failed',retryable:false,errorCode:'PERMANENT'}]);await channel.connect();const service=new CommerceService(undefined,channel,undefined,scriptedSemanticAgentFactory([goldenOffer(),prepareQuote]));service.resetAndSeed();await service.inbound(msg(goldenOrder,'terminal-1'));await service.inbound(msg('Yes please.','terminal-2'));const q=service.database.db.prepare('SELECT id,status FROM quotations ORDER BY rowid DESC LIMIT 1').get() as any;assert.equal(q.status,'DRAFT');const out=service.database.db.prepare('SELECT status,last_error FROM outbound_messages WHERE entity_id=?').get(q.id) as any;assert.equal(out.status,'FAILED');assert.equal(out.last_error,'terminal:PERMANENT');await service.sendQuote(q.id);assert.equal(channel.sendCount,1)});

test('Pi-interpreted non-Golden order is resolved through deterministic ERP truth',async()=>{const channel=new SimulatedChannel();await channel.connect();const service=new CommerceService(undefined,channel,undefined,scriptedSemanticAgentFactory([wingsOffer(),prepareQuote]));service.resetAndSeed();await service.inbound(msg('Wings 2 ctn tomorrow deliver can?','dynamic-1'));const offered=service.state();assert.equal(offered.quote,undefined);assert.match(offered.messages.at(-1)?.text??'',/Stock is available/);await service.inbound(msg('Yes please.','dynamic-2'));const quote=service.state().quote;assert.equal(quote?.status,'SENT');assert.equal(quote?.lines.length,1);assert.equal(quote?.lines[0].stockCode,'FCH-WING-2KG');assert.equal(quote?.lines[0].quantity,2);assert.equal(quote?.lines[0].uom,'CTN');assert.equal(quote?.lines[0].unitPrice,42);assert.equal(quote?.lines[0].subtotal,84);assert.equal(quote?.lines[0].available,24);assert.equal(quote?.total,84);assert.match(quote?.deliveryDate??'',/^\d{4}-\d{2}-\d{2}$/)});

test('unresolved quotation send blocks a competing new quotation',async()=>{const channel=new SimulatedChannel([{status:'unknown',clientMessageId:'unknown-send'}]);await channel.connect();const service=new CommerceService(undefined,channel,undefined,scriptedSemanticAgentFactory([goldenOffer(),prepareQuote,goldenOffer(),prepareQuote]));service.resetAndSeed();await service.inbound(msg(goldenOrder,'block-1'));await service.inbound(msg('Yes please.','block-2'));assert.equal(channel.sendCount,1);assert.equal(service.database.db.prepare('SELECT count(*) n FROM quotations').get().n,1);await service.inbound(msg(goldenOrder,'block-3'));await service.inbound(msg('Yes please.','block-4'));assert.equal(channel.sendCount,1);assert.equal(service.database.db.prepare('SELECT count(*) n FROM quotations').get().n,1);assert.match(service.state().messages.at(-1)?.text??'',/still being reconciled/i)});


test('concurrent direct sendQuote retries serialize and submit once',async()=>{const channel=new SimulatedChannel([{status:'failed',retryable:true,errorCode:'TEMP'},{status:'submitted',externalMessageId:'retry-once',submittedAt:new Date().toISOString()}]);await channel.connect();const service=new CommerceService(undefined,channel,undefined,scriptedSemanticAgentFactory([goldenOffer(),prepareQuote]));service.resetAndSeed();await service.inbound(msg(goldenOrder,'send-lock-1'));await service.inbound(msg('Yes please.','send-lock-2'));const q=service.database.db.prepare('SELECT id,status FROM quotations ORDER BY rowid DESC LIMIT 1').get() as any;assert.equal(q.status,'DRAFT');assert.equal(channel.sendCount,1);await Promise.all([service.sendQuote(q.id),service.sendQuote(q.id)]);assert.equal(channel.sendCount,2);assert.equal(service.database.db.prepare('SELECT status FROM quotations WHERE id=?').get(q.id).status,'SENT')});

test('sendQuote cannot revive a terminal quotation',async()=>{const channel=new SimulatedChannel([{status:'failed',retryable:false,errorCode:'PERMANENT'}]);await channel.connect();const service=new CommerceService(undefined,channel,undefined,scriptedSemanticAgentFactory([goldenOffer(),prepareQuote]));service.resetAndSeed();await service.inbound(msg(goldenOrder,'send-terminal-1'));await service.inbound(msg('Yes please.','send-terminal-2'));const q=service.database.db.prepare('SELECT id FROM quotations ORDER BY rowid DESC LIMIT 1').get() as any;service.database.db.prepare("UPDATE quotations SET status='REJECTED'").run();await assert.rejects(()=>service.sendQuote(q.id),/INVALID_QUOTE_TRANSITION/);assert.equal(channel.sendCount,1)});
