import test from 'node:test';
import assert from 'node:assert/strict';
import {V1Database} from '../src/database.js';
import {CommerceService} from '../src/commerce.js';
import {V2RolloutService,V2_CAPABILITIES} from '../src/v2-rollout.js';
import {createRolloutApprovalAuthority} from '../src/rollout-auth.js';
import {V2CanaryIngressRouter,type ProspectReplyScope} from '../src/v2-canary-ingress-router.js';
const message=(accountId='test-account',conversationId='prospect-a',id='scope-1')=>({accountId,conversationId,externalMessageId:id,channel:'whatsapp' as const,sender:{externalId:'synthetic-sender',phone:'+6500000000'},type:'text' as const,text:'Synthetic catalog question',occurredAt:new Date().toISOString()});
function setup(scopes?:readonly ProspectReplyScope[]){const approvals=createRolloutApprovalAuthority();const db=new V1Database(':memory:',undefined,approvals);db.resetAndSeed();let models=0,sends=0,reads=0;const rollout=new V2RolloutService(db,approvals);const router=new V2CanaryIngressRouter(db,new CommerceService(db),rollout,{enabled:true,prospectReplyScopes:scopes,outbound:{send:async()=>{sends++}} as any,prospectModel:async()=>{models++;return 'Synthetic response'},prospectCatalog:{searchProducts:async()=>{reads++;return []},getProductDetail:async()=>{reads++;return null}} as any});return{db,approvals,rollout,router,counts:()=>({models,sends,reads})}}
test('customer rollout cannot authorize prospect replies; default denial persists intake and suppresses replay',async()=>{
 const x=setup();try{for(const capability of V2_CAPABILITIES)x.rollout.configure({capability,enabled:true,accountId:'demo-account',conversationId:'conv-001',idempotencyKey:'synthetic-'+capability,approval:x.approvals.issue('synthetic-owner',{action:'ENABLE',capability,accountId:'demo-account',conversationId:'conv-001',enabled:true})});
 const m=message();for(let i=0;i<2;i++){const result=await x.router.receive(m) as any;assert.equal(result.routeOutcome,'PROSPECT_OUTBOUND_SCOPE_REQUIRED');assert.equal(result.replySuppressed,true)}
 assert.deepEqual(x.counts(),{models:0,sends:0,reads:0});assert.equal((x.db.db.prepare('SELECT count(*) n FROM messages WHERE external_message_id=?').get(m.externalMessageId) as any).n,1);assert.equal((x.db.db.prepare("SELECT reply_state FROM prospect_reply_sequence WHERE account_id=? AND external_message_id=?").get(m.accountId,m.externalMessageId) as any).reply_state,'SUPPRESSED');assert.equal((x.db.db.prepare("SELECT count(*) n FROM inbound_route_audit WHERE route_outcome='PROSPECT_OUTBOUND_SCOPE_REQUIRED'").get() as any).n,1);assert.equal((x.db.db.prepare('SELECT count(*) n FROM customer_channel_identities WHERE external_id=?').get(m.sender.externalId) as any).n,0);
 }finally{x.db.db.close()}
});
test('only exact account/conversation gets fresh prospect reply; caller mutation cannot widen scope',async()=>{
 const scopes=[{accountId:'test-account',externalConversationId:'prospect-a'}],x=setup(scopes);try{scopes.push({accountId:'other-account',externalConversationId:'prospect-b'});await x.router.receive(message('test-account','prospect-b','scope-b'));await x.router.receive(message('other-account','prospect-a','scope-other'));await x.router.receive(message('other-account','prospect-b','scope-mutation'));assert.deepEqual(x.counts(),{models:0,sends:0,reads:0});await x.router.receive(message());assert.deepEqual(x.counts(),{models:1,sends:1,reads:0});await x.router.receive(message());assert.deepEqual(x.counts(),{models:1,sends:1,reads:0})}finally{x.db.db.close()}
});
test('later authorization never replays an inbound suppressed before approval',async()=>{
 const x=setup();try{const m=message();await x.router.receive(m);let sent=0,modeled=0;const approved=new V2CanaryIngressRouter(x.db,new CommerceService(x.db),x.rollout,{enabled:true,prospectReplyScopes:[{accountId:m.accountId,externalConversationId:m.conversationId}],outbound:{send:async()=>{sent++}} as any,prospectModel:async()=>{modeled++;return 'Synthetic response'}});await approved.receive(m);assert.equal(sent,0);assert.equal(modeled,0);await approved.receive(message('test-account','prospect-a','fresh-approved'));assert.equal(sent,1);assert.equal(modeled,1)}finally{x.db.db.close()}
});
test('wildcard and malformed prospect reply scope is rejected',()=>{for(const scopes of [[{accountId:'*',externalConversationId:'prospect-a'}],[{accountId:'test-account',externalConversationId:'*'}],[{accountId:'',externalConversationId:'prospect-a'}]])assert.throws(()=>setup(scopes),/PROSPECT_REPLY_SCOPE_INVALID/)});
