import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync, rmSync, readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {V1Database} from '../src/database.js';
import {AgentTurnCoordinator} from '../src/v2-agent-turn-coordinator.js';

const A='demo-account', C='conv-001', U='CUST-001', P='sales-digital-employee';
function fixture(file=':memory:'){const d=new V1Database(file);d.resetAndSeed();d.db.prepare("INSERT INTO messages(id,conversation_id,external_message_id,direction,message_type,text,account_id,occurred_at) VALUES('in-1',?,'ext-1','INBOUND','text','hello',?,'2026-09-09T01:02:03Z')").run(C,A);return d}
const start={accountId:A,conversationId:C,inboundMessageId:'in-1',profileId:P,nowIso:'2026-09-09T09:00:00+08:00',timezone:'Asia/Singapore'} as const;
const action=(turnId:string,sequence=1,extra:Record<string,unknown>={})=>({turnId,sequence,capabilityName:'get_customer_context',capabilityVersion:'v1',arguments:{accountId:A,conversationId:C,customerId:U},...extra});
const result={status:'SUCCEEDED',data:{customerId:U},evidence:[],stateChanges:[]};

test('PI-001 starts one durable turn and exact inbound replay returns its id',()=>{const d=fixture();const c=new AgentTurnCoordinator(d);const first=c.start(start),again=c.start(start);assert.equal(first.turnId,again.turnId);assert.equal(d.db.prepare('SELECT count(*) n FROM agent_turns').get().n,1);assert.equal(Object.isFrozen(first),true);});
test('PI-001 start and resume replay the exact durable initial context snapshot',()=>{const d=fixture(),c=new AgentTurnCoordinator(d),first=c.start(start) as any;const original=JSON.stringify(first.context);d.db.prepare("UPDATE customers SET name='Changed Canonical Customer' WHERE id=?").run(U);const exact=c.start({...start,nowIso:'2026-09-09T10:00:00+08:00'}) as any,resumed=c.resume({...start,nowIso:'2026-09-09T10:00:00+08:00'}) as any;assert.equal(JSON.stringify(exact.context),original);assert.equal(JSON.stringify(resumed.context),original);assert.equal(resumed.context.customerContext.name,'Sunrise Mini Mart Pte Ltd');});

test('PI-001 fails closed for scope, profile and inbound identity',()=>{const d=fixture(),c=new AgentTurnCoordinator(d);assert.throws(()=>c.start({...start,accountId:'other'}),/INBOUND_SCOPE/);assert.throws(()=>c.start({...start,conversationId:'other'}),/INBOUND_SCOPE/);assert.throws(()=>c.start({...start,inboundMessageId:'missing'}),/INBOUND_SCOPE/);assert.throws(()=>c.start({...start,profileId:'missing'}),/EMPLOYEE_PROFILE_NOT_FOUND/);});
test('PI-001 validates registered version and profile narrowing without dispatch',()=>{const d=fixture(),c=new AgentTurnCoordinator(d),t=c.start(start);assert.throws(()=>c.propose({...action(t.turnId),capabilityVersion:'v9'}),/CAPABILITY_VERSION/);d.db.prepare('UPDATE employee_profiles SET capability_permissions_json=? WHERE id=?').run('["v2.capability.get_order_history"]',P);assert.throws(()=>c.propose(action(t.turnId)),/PERMISSION_DENIED/);});
test('PI-001 action and result replay are idempotent and conflicts reject',()=>{const d=fixture(),c=new AgentTurnCoordinator(d),t=c.start(start),a=c.propose(action(t.turnId) as any),same=c.propose({...action(t.turnId),actionId:(a.actions[0] as any).id} as any);assert.equal((same.actions[0] as any).id,(a.actions[0] as any).id);assert.throws(()=>c.propose({...action(t.turnId),actionId:'different',arguments:{accountId:A,conversationId:C,customerId:'wrong'}} as any),/ACTION_REPLAY_CONFLICT|CUSTOMER_SCOPE/);const r=c.recordResult({turnId:t.turnId,actionId:(a.actions[0] as any).id,sequence:1,result});assert.equal(r.status,'AWAITING_DECISION');assert.deepEqual((c.recordResult({turnId:t.turnId,actionId:(a.actions[0] as any).id,sequence:1,result} as any).actions[0] as any).result,result);assert.throws(()=>c.recordResult({turnId:t.turnId,actionId:(a.actions[0] as any).id,sequence:1,result:{...result,reasonCode:'CONFLICT'}}),/RESULT_REPLAY_CONFLICT/);});
test('PI-001 resumes pending action and then awaits decision after result across restart',()=>{const dir=mkdtempSync(join(tmpdir(),'pi001-'));const file=join(dir,'db.sqlite');try{let d=fixture(file),c=new AgentTurnCoordinator(d),t=c.start(start),a=c.propose(action(t.turnId) as any),id=(a.actions[0] as any).id;assert.equal(c.start(start).status,'RECONCILE_ACTION');d.db.close();d=new V1Database(file);c=new AgentTurnCoordinator(d);assert.equal(c.resume(start).status,'RECONCILE_ACTION');assert.equal((c.resume(start).actions[0] as any).id,id);c.recordResult({turnId:t.turnId,actionId:id,sequence:1,result});assert.equal(c.resume(start).status,'AWAITING_DECISION');d.db.close();}finally{rmSync(dir,{recursive:true,force:true})}});
test('PI-001 completion requires resolved actions and terminal replay is stable',()=>{const d=fixture(),c=new AgentTurnCoordinator(d),t=c.start(start),a=c.propose(action(t.turnId) as any),id=(a.actions[0] as any).id;assert.throws(()=>c.complete({turnId:t.turnId}),/UNRESOLVED_ACTION/);c.recordResult({turnId:t.turnId,actionId:id,sequence:1,result});assert.equal(c.complete({turnId:t.turnId,reason:'DONE'}).status,'TERMINAL');assert.equal(c.complete({turnId:t.turnId,reason:'DONE'}).status,'TERMINAL');assert.throws(()=>c.propose(action(t.turnId,2) as any),/TERMINAL_MUTATION/);});
test('PI-001 action tables are append-only and reset clears children before parents',()=>{const d=fixture(),c=new AgentTurnCoordinator(d),t=c.start(start),a=c.propose(action(t.turnId) as any),id=(a.actions[0] as any).id;assert.throws(()=>d.db.prepare('UPDATE agent_actions SET arguments_hash=? WHERE id=?').run('x',id),/IMMUTABLE_AGENT_ACTION/);assert.throws(()=>d.db.prepare('DELETE FROM agent_actions WHERE id=?').run(id),/IMMUTABLE_AGENT_ACTION/);c.recordResult({turnId:t.turnId,actionId:id,sequence:1,result});const resultId=(d.db.prepare('SELECT id FROM agent_action_results WHERE action_id=?').get(id) as any).id;assert.throws(()=>d.db.prepare('UPDATE agent_action_results SET result_hash=? WHERE id=?').run('x',resultId),/IMMUTABLE_AGENT_ACTION_RESULT/);assert.throws(()=>d.db.prepare('DELETE FROM agent_action_results WHERE id=?').run(resultId),/IMMUTABLE_AGENT_ACTION_RESULT/);assert.throws(()=>d.db.prepare("UPDATE agent_turns SET profile_id='other' WHERE id=?").run(t.turnId),/IMMUTABLE_AGENT_TURN/);d.resetAndSeed();assert.equal(d.db.prepare('SELECT count(*) n FROM agent_turns').get().n,0);assert.equal(d.db.prepare('SELECT count(*) n FROM agent_actions').get().n,0);assert.equal(d.db.prepare('SELECT count(*) n FROM agent_action_results').get().n,0);});
test('PI-001 rejects secrets and accessor-backed result without invoking getter',()=>{const d=fixture(),c=new AgentTurnCoordinator(d),t=c.start(start);let calls=0;const malicious={status:'SUCCEEDED',evidence:[],stateChanges:[]};Object.defineProperty(malicious,'data',{enumerable:true,get(){calls++;return {token:'secret'}}});assert.throws(()=>c.recordResult({turnId:t.turnId,actionId:'missing',sequence:1,result:malicious}),/ACTION_NOT_FOUND/);assert.equal(calls,0);const a=c.propose(action(t.turnId) as any);assert.throws(()=>c.recordResult({turnId:t.turnId,actionId:(a.actions[0] as any).id,sequence:1,result:{status:'SUCCEEDED',data:{token:'abc'},evidence:[],stateChanges:[]}}),/RESULT_SECRET/);});

test('PI-001 stable canonical replay ignores JSON object key insertion order and bounds persisted results',()=>{const d=fixture(),c=new AgentTurnCoordinator(d),t=c.start(start);const first=c.propose(action(t.turnId,1,{actionId:'stable-action'}) as any);const reordered={customerId:U,conversationId:C,accountId:A};const replay=c.propose({...action(t.turnId),actionId:'stable-action',arguments:reordered} as any);assert.equal((first.actions[0] as any).id,(replay.actions[0] as any).id);const id=(first.actions[0] as any).id;const r1={stateChanges:[],data:{b:2,a:1},evidence:[],status:'SUCCEEDED'};c.recordResult({turnId:t.turnId,actionId:id,sequence:1,result:r1});const r2={status:'SUCCEEDED',evidence:[],stateChanges:[],data:{a:1,b:2}};assert.doesNotThrow(()=>c.recordResult({turnId:t.turnId,actionId:id,sequence:1,result:r2}));const t2=fixture(),c2=new AgentTurnCoordinator(t2),turn2=c2.start(start),a2=c2.propose(action(turn2.turnId) as any);assert.throws(()=>c2.recordResult({turnId:turn2.turnId,actionId:(a2.actions[0] as any).id,sequence:1,result:{status:'SUCCEEDED',data:{note:'x'.repeat(40000)},evidence:[],stateChanges:[]}}),/RESULT_SIZE/);});

test('PI-001 raw SQL cannot forge turn/action/result ledger inserts',()=>{const d=fixture();assert.throws(()=>d.db.prepare("INSERT INTO agent_turns(id,account_id,conversation_id,inbound_message_id,profile_id,profile_version,timezone,status,context_fingerprint,context_provenance_json,created_at,updated_at) VALUES('forged',?,?,?,?,1,'UTC','AWAITING_DECISION','h','{}','2026-09-09','2026-09-09')").run(A,C,'in-1',P),/AGENT_TURN_INSERT_REQUIRES_COORDINATOR/);});



test('PI-001 exact replay returns the durable context snapshot even after mutable canonical state changes',()=>{const d=fixture(),c=new AgentTurnCoordinator(d),first=c.start(start) as any;const original=JSON.stringify(first.context);d.db.prepare("UPDATE customers SET name='Changed After Turn Start' WHERE id=?").run(U);d.db.prepare("UPDATE messages SET text='changed after turn start' WHERE id='in-1'").run();const resumed=c.resume({...start,nowIso:'2026-09-09T10:00:00+08:00'}) as any;assert.equal(JSON.stringify(resumed.context),original);assert.equal(resumed.context.currentTime.iso,'2026-09-09T09:00:00+08:00');const stored=(d.db.prepare('SELECT context_snapshot_json FROM agent_turns WHERE id=?').get(first.turnId) as any).context_snapshot_json;assert.equal(JSON.stringify(resumed.context),stored);});

test('PI-001 database exposes no generic agent-turn mutation callback and raw ledger writes stay blocked',()=>{const d=fixture();assert.equal('runAgentTurnMutation' in (d as any),false);const c=new AgentTurnCoordinator(d);assert.equal(typeof (c as any).mutate,'undefined');assert.throws(()=>d.db.prepare("INSERT INTO agent_turns(id,account_id,conversation_id,inbound_message_id,profile_id,profile_version,timezone,status,context_fingerprint,context_snapshot_json,context_provenance_json,created_at,updated_at) VALUES('forged',?,?,?,?,1,?,'AWAITING_DECISION','x','{}','{}','2026-09-09','2026-09-09')").run(A,C,'in-1',P,'Asia/Singapore'),/AGENT_TURN_INSERT_REQUIRES_COORDINATOR/);});
test('PI-001 additive opening preserves V1 data and coordinator source stays operational-only',()=>{const dir=mkdtempSync(join(tmpdir(),'pi001-migrate-')),file=join(dir,'db.sqlite');try{let d=new V1Database(file);d.resetAndSeed();d.db.prepare("INSERT INTO customer_order_memory VALUES('legacy','CUST-001','note','last','{}',1,NULL,'2026-09-09')").run();d.db.close();d=new V1Database(file);assert.equal(d.db.prepare("SELECT value_json FROM customer_order_memory WHERE id='legacy'").get().value_json,'{}');assert.equal(d.db.prepare("SELECT name FROM sqlite_master WHERE name IN ('agent_turns','agent_actions') ORDER BY name").all().length,2);d.db.close();const source=readFileSync(new URL('../src/v2-agent-turn-coordinator.ts',import.meta.url),'utf8'),databaseSource=readFileSync(new URL('../src/database.ts',import.meta.url),'utf8');assert.doesNotMatch(source,/pi-agent|dispatch|executeCapability|sendOutbound|lease|heartbeat|arrival_seq/i);assert.doesNotMatch(databaseSource,/runAgentTurnMutation/);}finally{rmSync(dir,{recursive:true,force:true})}});


test('PI-004 completed action cannot be repeated under a new sequence or idempotency key',()=>{const d=fixture(),c=new AgentTurnCoordinator(d),t=c.start(start);const first=c.propose(action(t.turnId) as any);c.recordResult({turnId:t.turnId,actionId:(first.actions[0] as any).id,sequence:1,result});assert.throws(()=>c.propose({...action(t.turnId,2),idempotencyKey:'different-host-key'} as any),/COMPLETED_ACTION_REPEAT/);assert.equal(d.db.prepare('SELECT count(*) n FROM agent_actions').get().n,1);assert.equal(d.db.prepare('SELECT count(*) n FROM agent_action_results').get().n,1);});
test('PI-004 response plan ledger is coordinator-only append-only and replay-safe',()=>{
 const d=fixture(),c=new AgentTurnCoordinator(d),t=c.start(start);
 const plan:any={turnId:t.turnId,intent:'ANSWER',connectiveText:'I can help with that.',factClaims:[],outboundPurpose:'customer_reply'};
 assert.throws(()=>d.db.prepare("INSERT INTO agent_response_plans(turn_id,plan_json,plan_hash,created_at) VALUES(?,?,?,'now')").run(t.turnId,'{}','x'),/AGENT_RESPONSE_PLAN_INSERT_REQUIRES_COORDINATOR/);
 assert.equal(c.completeWithResponsePlan(t.turnId,plan).status,'TERMINAL');
 assert.deepEqual(c.finalResponsePlan(t.turnId),plan);
 assert.doesNotThrow(()=>c.completeWithResponsePlan(t.turnId,plan));
 assert.throws(()=>c.completeWithResponsePlan(t.turnId,{...plan,connectiveText:'Verified.'} as any),/RESPONSE_PLAN_REPLAY_CONFLICT/);
 assert.throws(()=>d.db.prepare("UPDATE agent_response_plans SET plan_hash='x' WHERE turn_id=?").run(t.turnId),/IMMUTABLE_AGENT_RESPONSE_PLAN/);
 assert.throws(()=>d.db.prepare('DELETE FROM agent_response_plans WHERE turn_id=?').run(t.turnId),/IMMUTABLE_AGENT_RESPONSE_PLAN/);
 d.resetAndSeed(); assert.equal(d.db.prepare('SELECT count(*) n FROM agent_response_plans').get().n,0);
});
