import assert from 'node:assert/strict';
import test from 'node:test';
import {buildV3AttachmentSource} from '../src/v3-attachment-source.js';
import {buildV3AttachmentEvidence, verifyV3AttachmentEvidence} from '../src/v3-attachment-evidence.js';

const scope = {tenantId: 'tenant-1', accountId: 'account-1', channelAccountId: 'channel-1', conversationId: 'conversation-1', customerId: 'customer-1'} as const;
const source = buildV3AttachmentSource({scope, attachmentId: 'attachment-1', sourceMessageId: 'message-1', sourceRef: 'media://source-1', mimeType: 'application/pdf', bytes: new Uint8Array([1, 2, 3])});
const input = (overrides: Record<string, unknown> = {}) => ({source, mediaType: 'PDF', extractionType: 'TEXT', extractionVersion: 'pdf-text-v1', extractorRef: 'host/pdf-text', extractorVersion: '1.2.0', pageNumber: null, regionRef: null, boundingBox: null, timeRange: null, derivedAt: '2026-09-19T00:00:00.000Z', freshnessState: 'CURRENT', provenanceRefs: ['message-1', 'attachment-1'], ...overrides});

test('builds deterministic immutable evidence and preserves MM-001 binding', () => { const one = buildV3AttachmentEvidence(input()), two = buildV3AttachmentEvidence(input()); assert.deepEqual(one, two); assert.equal(one.contractVersion, 'V3-MM-002'); assert.equal(one.authority, 'NON_AUTHORITATIVE_DERIVED'); assert.equal(one.trustClass, 'UNTRUSTED_CUSTOMER_EVIDENCE'); assert.equal(one.sourceContentHash, source.contentSha256); assert.equal(one.sourceFingerprint, source.recordFingerprint); assert(Object.isFrozen(one)); assert(Object.isFrozen(one.scope)); assert(Object.isFrozen(one.provenanceRefs)); assert.equal(verifyV3AttachmentEvidence(one, source), true); });
test('versions extraction identity and exact provenance', () => { const a = buildV3AttachmentEvidence(input()), b = buildV3AttachmentEvidence(input({extractionVersion: 'pdf-text-v2', extractorVersion: '2.0.0', provenanceRefs: ['message-1', 'attachment-1', 'page:1']})); assert.notEqual(a.evidenceId, b.evidenceId); assert.notEqual(a.recordFingerprint, b.recordFingerprint); assert.deepEqual(b.provenanceRefs, ['message-1', 'attachment-1', 'page:1']); });
test('supports nullable page, region, box, and time locations', () => { const record = buildV3AttachmentEvidence(input({pageNumber: 2, regionRef: 'table-1', boundingBox: {x: 1, y: 2, width: 30, height: 40}, timeRange: {start: 1.5, end: 4}})); assert.equal(record.pageNumber, 2); assert.deepEqual(record.boundingBox, {x: 1, y: 2, width: 30, height: 40}); assert.deepEqual(record.timeRange, {start: 1.5, end: 4}); });
test('includes extraction class and location in evidence identity', () => { const base = buildV3AttachmentEvidence(input({pageNumber: 1})), pageTwo = buildV3AttachmentEvidence(input({pageNumber: 2})), ocr = buildV3AttachmentEvidence(input({pageNumber: 1, extractionType: 'OCR'})), region = buildV3AttachmentEvidence(input({pageNumber: 1, regionRef: 'region-2'})); assert.notEqual(base.evidenceId, pageTwo.evidenceId); assert.notEqual(base.evidenceId, ocr.evidenceId); assert.notEqual(base.evidenceId, region.evidenceId); });
test('preserves every freshness state without changing authority', () => { for (const freshnessState of ['CURRENT', 'STALE', 'SUPERSEDED', 'INVALIDATED'] as const) { const record = buildV3AttachmentEvidence(input({freshnessState})); assert.equal(record.freshnessState, freshnessState); assert.equal(record.grantsEffects, false); assert.equal(record.aiAuthorityCutoff, 'SALES_ORDER.DRAFT'); } });
test('rejects source, scope, hash, and record tampering', () => { const record = buildV3AttachmentEvidence(input()); assert.throws(() => verifyV3AttachmentEvidence(record, {...source, sourceMessageId: 'other'} as never), /BINDING|SOURCE_FINGERPRINT/); assert.throws(() => verifyV3AttachmentEvidence({...record, sourceContentHash: '0'.repeat(64)} as never, source), /BINDING|RECORD_FINGERPRINT/); assert.throws(() => verifyV3AttachmentEvidence({...record, scope: {...scope, accountId: 'other'}} as never, source), /BINDING|RECORD_FINGERPRINT/); });
test('rejects accessors, proxies, unknown fields, and model authority fields', () => { const candidate = input() as Record<string, unknown>; let called = false; Object.defineProperty(candidate, 'derivedAt', {enumerable: true, get() { called = true; return '2026-09-19'; }}); assert.throws(() => buildV3AttachmentEvidence(candidate as never), /ACCESSOR/); assert.equal(called, false); assert.throws(() => buildV3AttachmentEvidence(new Proxy(input(), {get() { throw new Error('getter'); }}) as never), /CLOSED_DATA/); assert.throws(() => buildV3AttachmentEvidence({...input(), authority: 'AUTHORITATIVE'} as never), /CLOSED_DATA/); });
test('enforces bounds and immutable nested location data', () => { assert.throws(() => buildV3AttachmentEvidence(input({pageNumber: 0})), /PAGE_NUMBER/); assert.throws(() => buildV3AttachmentEvidence(input({timeRange: {start: 4, end: 3}})), /TIME_RANGE/); assert.throws(() => buildV3AttachmentEvidence(input({provenanceRefs: Array(129).fill('x')})), /PROVENANCE/); const record = buildV3AttachmentEvidence(input({boundingBox: {x: 1, y: 2, width: 3, height: 4}})); assert(Object.isFrozen(record.boundingBox)); assert.throws(() => (record.boundingBox as {x: number}).x = 9, TypeError); });
