import test from 'node:test';
import assert from 'node:assert/strict';
import {Worker} from 'node:worker_threads';
import {mkdtempSync, rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {V1Database} from '../src/database.js';
import {V2QueueService} from '../src/v2-queue.js';
import {buildInboundBundle} from '../src/v3-inbound-bundle.js';
import {buildContextSnapshot} from '../src/v3-context-snapshot.js';
import {buildV3FreshnessVectorFromDatabase, type V3FreshnessVectorInput} from '../src/v3-freshness-vector.js';
import {buildConversationGoal} from '../src/v3-conversation-goal.js';
import {V3GoalProposalHost} from '../src/v3-goal-proposal.js';
import {V3DurableContinuationStore, buildV3DurableContinuation, v3FreshnessVectorRef, v3ResumeConditionRef, type V3ContinuationHostCondition} from '../src/v3-durable-continuation.js';
import {V3ContinuationProcessor} from '../src/v3-continuation-processing.js';
import {isCurrentReasoningLease} from '../src/v3-reasoning-lease.js';

const scope = {accountId: 'demo-account', conversationId: 'conv-001'} as const;
const condition = (trigger: V3ContinuationHostCondition['resumeTriggerType'] = 'EXTERNAL_EVENT', text = 'ready'): V3ContinuationHostCondition => ({...scope, resumeTriggerType: trigger, condition: text});
function fixture(file = ':memory:') {
  const database = new V1Database(file); database.resetAndSeed(); const queue = new V2QueueService(database);
  const inbound = queue.enqueueInbound({...scope, externalMessageId: 'goal005-inbound', occurredAt: '2030-01-01T00:00:00.000Z', text: 'untrusted customer content'});
  const bundle = buildInboundBundle(database.db, {...scope, messageIds: [inbound.messageId], bundleRevision: 1, hardCapAt: '2030-01-01T00:00:03.000Z', closedAt: '2030-01-01T00:00:01.000Z', closeReason: 'QUIET_WINDOW'});
  database.db.prepare("INSERT INTO work_items(id,account_id,conversation_id,customer_id,type,state,revision,goal_summary,source_message_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run('goal005-wi', scope.accountId, scope.conversationId, 'CUST-001', 'SALES_ORDER_REQUEST', 'DRAFTING', 1, 'async work', inbound.messageId, '2030-01-01T00:00:00.000Z', '2030-01-01T00:00:00.000Z');
  const goals = new V3GoalProposalHost(database); const goal = buildConversationGoal({goalId: 'goal005-goal', ...scope, sourceMessageIds: [inbound.messageId], sourceAttachmentIds: [], erpObjectRefs: [], parentGoalId: null, dependsOnGoalIds: [], relatedGoalIds: [], description: 'async work', status: 'OPEN', createdBy: 'AGENT', createdAt: '2030-01-01T00:00:00.000Z', updatedAt: '2030-01-01T00:00:00.000Z', fulfillmentEvidenceRefs: []});
  goals.admit({scope, operation: 'CREATE', expected: {goalId: null, revision: null, status: null}, goal}, {proposalId: 'goal005-proposal', idempotencyKey: 'goal005-proposal', createdAt: '2030-01-01T00:00:00.000Z'});
  goals.admit({scope, operation: 'UPDATE', expected: {goalId: goal.goalId, revision: 1, status: 'OPEN'}, goal: {...goal, status: 'WAITING_EXTERNAL', updatedAt: '2030-01-01T00:00:01.000Z'}}, {proposalId: 'goal005-update', idempotencyKey: 'goal005-update', createdAt: '2030-01-01T00:00:01.000Z'});
  const fingerprint = buildV3FreshnessVectorFromDatabase(database.db, input(inbound.messageId)).dependencies.authoritativeV2FreshnessFingerprint;
  const context = buildContextSnapshot({accountId: scope.accountId, conversationId: scope.conversationId, turnId: 'goal005-turn', inboundMessageRef: {id: inbound.messageId, occurredAt: '2030-01-01T00:00:00.000Z'}, profile: {id: 'sales-digital-employee', version: 1}, activeQuotationSalesOrder: {quotation: null, salesOrder: null}, freshness: {fingerprint, inboundMessageId: inbound.messageId, summaryVersion: null, workItemRevision: null, draftRevision: null, quotationId: null, salesOrderId: null}});
  const vector = buildV3FreshnessVectorFromDatabase(database.db, input(inbound.messageId)); const c = condition();
  const continuation = buildV3DurableContinuation({continuationId: 'goal005-continuation', workItemId: 'goal005-wi', goalId: 'goal005-goal', ...scope, disposition: 'WAITING_EXTERNAL', ownerType: 'HOST', ownerId: 'host', state: 'WAITING', resumeTriggerType: c.resumeTriggerType, resumeConditionRef: v3ResumeConditionRef(c), nextEligibleAt: null, deadlineAt: '2030-01-02T00:00:00.000Z', expectedFreshnessVectorRef: v3FreshnessVectorRef(vector), lastEvidenceRefs: [], lastEffectRefs: [], attempt: 0, budgetState: {maxAttempts: 3, consumed: 0, deadlineAt: '2030-01-02T00:00:00.000Z'}, idempotencyKey: 'goal005-continuation', createdAt: '2030-01-01T00:00:00.000Z', updatedAt: '2030-01-01T00:00:00.000Z'});
  new V3DurableContinuationStore(database).create(continuation, vector, c);
  return {database, queue, bundle, context, vector, continuation};
}
function input(messageId: string): Omit<V3FreshnessVectorInput, 'authoritativeV2FreshnessFingerprint'> { return {identityScope: {...scope, customerId: 'CUST-001', channelAccountId: scope.accountId}, employeeProfile: {id: 'sales-digital-employee', version: 1}, capabilityPolicy: {policyVersion: 1, availableCapabilities: []}, workItemOrderDraftRefs: {workItem: null, orderDraft: null}, canonicalBusiness: {quotations: [], acceptances: [], outbound: [], salesOrders: []}, relevantErpEvidence: [], goalGraph: {version: null, dependencyRefs: []}, attachmentExtraction: {version: null, dependencyRefs: []}, retentionAccess: {version: 1, dependencyRefs: []}, conversationBundle: {conversationRevision: 0, bundleRevision: 0, messageRefs: [{id: messageId, version: 1}]}}; }
function wake(f: ReturnType<typeof fixture>, overrides: Record<string, unknown> = {}) { const c = condition(); return {accountId: scope.accountId, conversationId: scope.conversationId, continuationId: f.continuation.continuationId, resumeTriggerType: c.resumeTriggerType, condition: c.condition, nowIso: '2030-01-01T00:00:02.000Z', ownerId: 'worker', wakeEventId: 'host-event-1', bundle: f.bundle, context: f.context, freshnessVector: f.vector, ...overrides}; }

test('GOAL-005 reacquires a current fenced lease and duplicate wake is idempotent', () => { const f = fixture(); const p = new V3ContinuationProcessor(f.database); const first = p.process(wake(f)); assert.equal(first.disposition, 'RESUME_AUTHORIZED'); assert.equal(first.reasonCode, 'LEASE_REACQUIRED'); assert.ok(first.lease?.fencingToken); const duplicate = p.process(wake(f)); assert.equal(duplicate.disposition, 'RESUME_AUTHORIZED'); assert.equal(duplicate.reasonCode, 'DUPLICATE_WAKE'); assert.equal(duplicate.wakeId, first.wakeId); assert.equal(duplicate.lease?.generation, first.lease?.generation); });
test('GOAL-005 rejects wrong trigger/condition/scope and stale freshness/context', () => { const f = fixture(); const p = new V3ContinuationProcessor(f.database); assert.equal(p.process(wake(f, {resumeTriggerType: 'DEADLINE', condition: 'ready'})).reasonCode, 'INVALID_WAKE'); assert.equal(p.process(wake(f, {condition: 'wrong'})).reasonCode, 'INVALID_WAKE'); assert.throws(() => p.process(wake(f, {accountId: 'other'})), /CONTINUATION_NOT_FOUND/); const stale = {...f.vector, vectorHash: 'stale'}; assert.throws(() => p.process(wake(f, {freshnessVector: stale})), /INVALID_WAKE/); });
test('GOAL-005 deadline and manual handoff are bounded non-effect decisions', () => { const deadline = fixture(); const processor = new V3ContinuationProcessor(deadline.database); assert.deepEqual(processor.process(wake(deadline, {nowIso: '2030-01-02T00:00:00Z'})).reasonCode, 'DEADLINE_EXHAUSTED'); assert.equal(processor.process(wake(deadline, {resumeTriggerType: 'DEADLINE', condition: '', nowIso: '2030-01-02T00:00:00Z'})).disposition, 'NON_EFFECT_HANDOFF'); assert.equal(processor.process(wake(deadline, {resumeTriggerType: 'DEADLINE', condition: '', nowIso: '2030-01-01T00:00:02Z'})).reasonCode, 'INVALID_WAKE'); assert.throws(() => processor.process(wake(deadline, {resumeTriggerType: 'NOT_A_TRIGGER' as any})), /INVALID_WAKE/); const handoff = fixture(); const c = condition('MANUAL_HANDOFF', 'human-required'); const vector = handoff.vector; const record = buildV3DurableContinuation({...handoff.continuation, continuationId: 'handoff', idempotencyKey: 'handoff', ownerType: 'HUMAN', ownerId: 'staff', resumeTriggerType: c.resumeTriggerType, resumeConditionRef: v3ResumeConditionRef(c)}); new V3DurableContinuationStore(handoff.database).create(record, vector, c); assert.equal(new V3ContinuationProcessor(handoff.database).process(wake(handoff, {continuationId: 'handoff', resumeTriggerType: c.resumeTriggerType, condition: c.condition})).reasonCode, 'MANUAL_HANDOFF'); });
test('GOAL-005 restart readback preserves duplicate wake identity and lease fence', () => { const dir = '/tmp/goal005-restart-' + Date.now(); const f = fixture(dir); const processor = new V3ContinuationProcessor(f.database); const first = processor.process(wake(f)); const old = first.lease!; f.database.db.close(); const reopened = new V1Database(dir); const resumed = new V3ContinuationProcessor(reopened).process(wake(f)); assert.equal(resumed.reasonCode, 'DUPLICATE_WAKE'); assert.equal(resumed.wakeId, first.wakeId); assert.equal(resumed.lease?.generation, old.generation); reopened.db.close(); });
test('GOAL-005 fences an expired generation and reports final budget exhaustion', () => { const f = fixture(); const first = new V3ContinuationProcessor(f.database).process(wake(f, {leaseMs: 1000})); const old = first.lease!; const newer = f.queue.claimNext({...scope, owner: 'new-worker', nowIso: '2030-01-01T00:00:04.000Z', leaseMs: 1000})!; assert.equal(newer.leaseOwner, 'new-worker'); assert.equal(isCurrentReasoningLease(f.database.db, old, f.bundle, f.context, '2030-01-01T00:00:04.000Z'), false); const c = condition(); const exhausted = buildV3DurableContinuation({...f.continuation, continuationId: 'budget', idempotencyKey: 'budget', budgetState: {maxAttempts: 1, consumed: 0, deadlineAt: f.continuation.deadlineAt}}); new V3DurableContinuationStore(f.database).create(exhausted, f.vector, c); const processor = new V3ContinuationProcessor(f.database); assert.equal(processor.process(wake(f, {continuationId: 'budget'})).reasonCode, 'LEASE_UNAVAILABLE'); assert.equal(processor.process(wake(f, {continuationId: 'budget', wakeEventId: 'budget-distinct'})).reasonCode, 'BUDGET_EXHAUSTED'); });
test('GOAL-005 rejects a previously valid wake after current DB freshness changes', () => { const profile = fixture(); profile.database.db.prepare('UPDATE employee_profiles SET version=version+1 WHERE id=?').run('sales-digital-employee'); const profileDecision = new V3ContinuationProcessor(profile.database).process(wake(profile)); assert.equal(profileDecision.disposition, 'NON_EFFECT_REJECTED'); assert.equal(profileDecision.reasonCode, 'STALE_FRESHNESS'); const dependency = fixture(); dependency.database.db.prepare('UPDATE work_items SET goal_summary=? WHERE id=?').run('changed host dependency', 'goal005-wi'); const dependencyDecision = new V3ContinuationProcessor(dependency.database).process(wake(dependency)); assert.equal(dependencyDecision.disposition, 'NON_EFFECT_REJECTED'); assert.equal(dependencyDecision.reasonCode, 'STALE_FRESHNESS'); });
test('GOAL-005 immutable base consumed/attempt leaves exactly the remaining durable slot', () => { const f = fixture(); const c = condition(); const continuation = buildV3DurableContinuation({...f.continuation, continuationId: 'base-budget', idempotencyKey: 'base-budget', attempt: 2, budgetState: {maxAttempts: 3, consumed: 2, deadlineAt: f.continuation.deadlineAt}}); new V3DurableContinuationStore(f.database).create(continuation, f.vector, c); const first = f.database.v3WakeReserve({accountId: scope.accountId, conversationId: scope.conversationId, continuationId: continuation.continuationId, wakeId: 'event-wake-1', wakeEventId: 'host-event-base-1', now: '2030-01-01T00:00:02.000Z'}); assert.equal(first.status, 'NEW'); assert.equal(first.attempt, 3); const second = f.database.v3WakeReserve({accountId: scope.accountId, conversationId: scope.conversationId, continuationId: continuation.continuationId, wakeId: 'event-wake-2', wakeEventId: 'host-event-base-2', now: '2030-01-01T00:00:02.000Z'}); assert.equal(second.status, 'BUDGET_EXHAUSTED'); });
test('GOAL-005 reserved-unbound event retries binding, while bound event cannot reacquire', () => { const f = fixture(); f.queue.claimNext({...scope, owner: 'busy', nowIso: '2030-01-01T00:00:02.000Z', leaseMs: 1000}); const first = new V3ContinuationProcessor(f.database).process(wake(f, {nowIso: '2030-01-01T00:00:02.000Z'})); assert.equal(first.reasonCode, 'LEASE_UNAVAILABLE'); const rebound = new V3ContinuationProcessor(f.database).process(wake(f, {nowIso: '2030-01-01T00:00:04.000Z', leaseMs: 1000})); assert.equal(rebound.reasonCode, 'LEASE_REACQUIRED'); assert.equal(rebound.lease?.generation, 2); const duplicate = new V3ContinuationProcessor(f.database).process(wake(f, {nowIso: '2030-01-01T00:00:06.000Z'})); assert.equal(duplicate.reasonCode, 'LEASE_UNAVAILABLE'); const newer = new V3ContinuationProcessor(f.database).process(wake(f, {wakeEventId: 'host-event-2', nowIso: '2030-01-01T00:00:06.000Z', leaseMs: 1000})); assert.equal(newer.reasonCode, 'LEASE_REACQUIRED'); assert.equal(newer.lease?.generation, 3); assert.equal((f.database.db.prepare("SELECT count(*) AS n FROM v3_continuation_wake_events WHERE event_type='ATTEMPT_RESERVED'").get() as {n:number}).n, 2); });

test('GOAL-005 bind fails closed when the goal becomes terminal after reservation', () => { const f = fixture(); const w = wake(f); const receipt = f.database.v3WakeReserve({accountId: scope.accountId, conversationId: scope.conversationId, continuationId: f.continuation.continuationId, wakeId: 'terminal-race', wakeEventId: w.wakeEventId, now: w.nowIso}); assert.equal(receipt.status, 'NEW'); const terminal = buildConversationGoal({goalId: f.continuation.goalId, accountId: scope.accountId, conversationId: scope.conversationId, sourceMessageIds: [f.bundle.messageIds[0]], sourceAttachmentIds: [], erpObjectRefs: [], parentGoalId: null, dependsOnGoalIds: [], relatedGoalIds: [], description: 'FULFILLED', status: 'FULFILLED', createdBy: 'AGENT', createdAt: '2030-01-01T00:00:00.000Z', updatedAt: '2030-01-01T00:00:03.000Z', fulfillmentEvidenceRefs: []}); new V3GoalProposalHost(f.database).admit({scope, operation: 'UPDATE', expected: {goalId: f.continuation.goalId, revision: 2, status: 'WAITING_EXTERNAL'}, goal: terminal}, {proposalId: 'terminal-race', idempotencyKey: 'terminal-race', createdAt: '2030-01-01T00:00:03.000Z'}); const lease = f.queue.claimNext({...scope, owner: 'worker', nowIso: w.nowIso, leaseMs: 30_000})!; const bound = f.database.v3WakeBindLease({accountId: scope.accountId, conversationId: scope.conversationId, continuationId: f.continuation.continuationId, wakeId: 'terminal-race', attempt: receipt.attempt, owner: lease.leaseOwner, generation: lease.leaseGeneration, now: w.nowIso, bundle: f.bundle, context: f.context, freshnessVector: f.vector}); assert.equal(bound.status, 'STALE'); assert.equal((f.database.db.prepare("SELECT count(*) AS n FROM v3_continuation_wake_events WHERE event_type='LEASE_BOUND'").get() as {n:number}).n, 0); });

test('GOAL-005 bind fails closed when freshness changes after reservation', () => { const f = fixture(); const w = wake(f); const receipt = f.database.v3WakeReserve({accountId: scope.accountId, conversationId: scope.conversationId, continuationId: f.continuation.continuationId, wakeId: 'freshness-race', wakeEventId: w.wakeEventId, now: w.nowIso}); assert.equal(receipt.status, 'NEW'); f.database.db.prepare('UPDATE work_items SET goal_summary=? WHERE id=?').run('changed after reservation', 'goal005-wi'); const lease = f.queue.claimNext({...scope, owner: 'worker', nowIso: w.nowIso, leaseMs: 30_000})!; const bound = f.database.v3WakeBindLease({accountId: scope.accountId, conversationId: scope.conversationId, continuationId: f.continuation.continuationId, wakeId: 'freshness-race', attempt: receipt.attempt, owner: lease.leaseOwner, generation: lease.leaseGeneration, now: w.nowIso, bundle: f.bundle, context: f.context, freshnessVector: f.vector}); assert.equal(bound.status, 'STALE'); assert.equal((f.database.db.prepare("SELECT count(*) AS n FROM v3_continuation_wake_events WHERE event_type='LEASE_BOUND'").get() as {n:number}).n, 0); });

test('GOAL-005 bind fails closed when lease owner and generation change after reservation', () => { const f = fixture(); const w = wake(f); const receipt = f.database.v3WakeReserve({accountId: scope.accountId, conversationId: scope.conversationId, continuationId: f.continuation.continuationId, wakeId: 'lease-race', wakeEventId: w.wakeEventId, now: w.nowIso}); assert.equal(receipt.status, 'NEW'); f.queue.claimNext({...scope, owner: 'old-worker', nowIso: w.nowIso, leaseMs: 1_000})!; const oldGeneration = Number((f.database.db.prepare('SELECT lease_generation FROM v2_conversation_inbox WHERE account_id=? AND conversation_id=?').get(scope.accountId, scope.conversationId) as {lease_generation:number}).lease_generation); f.queue.claimNext({...scope, owner: 'new-worker', nowIso: '2030-01-01T00:00:04.000Z', leaseMs: 30_000})!; const newState = f.database.db.prepare('SELECT lease_owner,lease_generation FROM v2_conversation_inbox WHERE account_id=? AND conversation_id=?').get(scope.accountId, scope.conversationId) as {lease_owner:string;lease_generation:number}; assert.equal(newState.lease_owner, 'new-worker'); assert.notEqual(newState.lease_generation, oldGeneration); const bound = f.database.v3WakeBindLease({accountId: scope.accountId, conversationId: scope.conversationId, continuationId: f.continuation.continuationId, wakeId: 'lease-race', attempt: receipt.attempt, owner: 'old-worker', generation: oldGeneration, now: w.nowIso, bundle: f.bundle, context: f.context, freshnessVector: f.vector}); assert.equal(bound.status, 'STALE'); assert.equal((f.database.db.prepare("SELECT count(*) AS n FROM v3_continuation_wake_events WHERE event_type='LEASE_BOUND'").get() as {n:number}).n, 0); });

function workerRace(file:string, wakes:unknown[], mode:'process'|'reserve'='process') {
  const barrier = new SharedArrayBuffer(4);
  const workers = wakes.map((input, i) => new Worker(new URL('./v3-continuation-processing-race-worker.ts', import.meta.url), {workerData: {file, barrier, input, mode}, execArgv: ['--import', 'tsx'], name: `goal005-${i}`}));
  return (async () => { await Promise.all(workers.map(worker => new Promise<void>((resolve, reject) => { worker.once('message', message => message?.ready ? resolve() : reject(Error(String(message)))); worker.once('error', error => { console.error('RACE_WORKER_ERROR', error); reject(error); }); }))); const messages = workers.map(worker => new Promise<any>((resolve, reject) => { worker.once('message', resolve); worker.once('error', reject); })); const exits = workers.map(worker => new Promise<void>((resolve, reject) => { worker.once('exit', code => code === 0 ? resolve() : reject(Error(`worker exit ${code}`))); worker.once('error', reject); })); Atomics.store(new Int32Array(barrier), 0, 1); Atomics.notify(new Int32Array(barrier), 0, workers.length); const results = await Promise.all(messages); await Promise.all(exits); return results; })();
}

test('GOAL-005 same Host event races across SQLite connections reserve once and replay safely', async () => { const dir = mkdtempSync(join(tmpdir(), 'goal005-same-event-')), file = join(dir, 'db.sqlite'); try { const f = fixture(file); const input = wake(f); f.database.db.close(); await workerRace(file, [input, input]); const check = new V1Database(file); assert.equal((check.db.prepare("SELECT count(*) AS n FROM v3_continuation_wake_events WHERE event_type='ATTEMPT_RESERVED'").get() as any).n, 1); assert.equal((check.db.prepare("SELECT count(*) AS n FROM v3_continuation_wake_events WHERE event_type='LEASE_BOUND'").get() as any).n, 1); check.db.close(); } finally { rmSync(dir, {recursive: true, force: true}); } });

test('GOAL-005 different Host events race for the final slot with one budget winner', async () => { const dir = mkdtempSync(join(tmpdir(), 'goal005-final-race-')), file = join(dir, 'db.sqlite'); try { const f = fixture(file); const c = condition(); const continuation = buildV3DurableContinuation({...f.continuation, continuationId: 'final-race', idempotencyKey: 'final-race', attempt: 2, budgetState: {maxAttempts: 3, consumed: 2, deadlineAt: f.continuation.deadlineAt}}); new V3DurableContinuationStore(f.database).create(continuation, f.vector, c); const inputs = ['final-a', 'final-b'].map(wakeEventId => ({accountId: scope.accountId, conversationId: scope.conversationId, continuationId: continuation.continuationId, wakeId: `wake-${wakeEventId}`, wakeEventId, now: '2030-01-01T00:00:02Z'})); f.database.db.close(); await workerRace(file, inputs, 'reserve'); const check = new V1Database(file); assert.equal((check.db.prepare("SELECT count(*) AS n FROM v3_continuation_wake_events WHERE event_type='ATTEMPT_RESERVED'").get() as any).n, 1); assert.equal((check.db.prepare("SELECT attempt_number FROM v3_continuation_wake_events WHERE event_type='ATTEMPT_RESERVED'").get() as any).attempt_number, 3); check.db.close(); } finally { rmSync(dir, {recursive: true, force: true}); } });

test('GOAL-005 terminal goal statuses block old continuation before receipt and lease', () => { for (const status of ['FULFILLED', 'SUPERSEDED', 'CANCELLED'] as const) { const f = fixture(); const terminal = buildConversationGoal({goalId: f.continuation.goalId, accountId: scope.accountId, conversationId: scope.conversationId, sourceMessageIds: [f.bundle.messageIds[0]], sourceAttachmentIds: [], erpObjectRefs: [], parentGoalId: null, dependsOnGoalIds: [], relatedGoalIds: [], description: status, status, createdBy: 'AGENT', createdAt: '2030-01-01T00:00:00.000Z', updatedAt: '2030-01-01T00:00:03.000Z', fulfillmentEvidenceRefs: []}); const operation = status === 'FULFILLED' ? 'UPDATE' : status === 'SUPERSEDED' ? 'SUPERSEDE' : 'CANCEL'; new V3GoalProposalHost(f.database).admit({scope, operation, expected: {goalId: f.continuation.goalId, revision: 2, status: 'WAITING_EXTERNAL'}, goal: terminal}, {proposalId: `terminal-${status}`, idempotencyKey: `terminal-${status}`, createdAt: '2030-01-01T00:00:03.000Z'}); const result = new V3ContinuationProcessor(f.database).process(wake(f)); assert.equal(result.reasonCode, 'NOT_ELIGIBLE'); assert.equal((f.database.db.prepare('SELECT count(*) AS n FROM v3_continuation_wake_events').get() as any).n, 0); assert.equal((f.database.db.prepare('SELECT lease_owner FROM v2_conversation_inbox').get() as any).lease_owner, null); f.database.db.close(); } });

test('GOAL-005 wake ledger raw writes are guarded while service path succeeds', () => { const f = fixture(); const table = "v3_continuation_wake_events(wake_event_id,account_id,conversation_id,continuation_id,wake_id,event_type,attempt_number,lease_owner,lease_generation,payload_json,event_hash,created_at)"; const values = "'raw','demo-account','conv-001','goal005-continuation','raw','ATTEMPT_RESERVED',1,NULL,NULL,'{}','hash','2030-01-01T00:00:00Z'"; assert.equal(f.database.v3WakeReserve({accountId: scope.accountId, conversationId: scope.conversationId, continuationId: f.continuation.continuationId, wakeId: 'service', wakeEventId: 'service', now: '2030-01-01T00:00:02Z'}).status, 'NEW'); assert.throws(() => f.database.db.prepare(`INSERT INTO ${table} VALUES(${values})`).run(), /REQUIRES_SERVICE/); assert.throws(() => f.database.db.prepare("UPDATE v3_continuation_wake_events SET wake_id='x'").run(), /IMMUTABLE_V3_WAKE_EVENT/); assert.throws(() => f.database.db.prepare("DELETE FROM v3_continuation_wake_events").run(), /IMMUTABLE_V3_WAKE_EVENT/); f.database.db.close(); });

test('GOAL-005 foreign scope fails closed without a receipt', () => { const f = fixture(); assert.throws(() => f.database.v3WakeReserve({accountId: 'foreign', conversationId: scope.conversationId, continuationId: f.continuation.continuationId, wakeId: 'foreign', wakeEventId: 'foreign', now: '2030-01-01T00:00:02Z'}), /V3_WAKE_CONTINUATION_SCOPE/); assert.throws(() => new V3ContinuationProcessor(f.database).process(wake(f, {accountId: 'foreign'})), /CONTINUATION_NOT_FOUND/); assert.equal((f.database.db.prepare('SELECT count(*) AS n FROM v3_continuation_wake_events').get() as any).n, 0); f.database.db.close(); });

test('GOAL-005 restart preserves an unbound final reservation and binds the same attempt', () => { const dir = mkdtempSync(join(tmpdir(), 'goal005-unbound-restart-')), file = join(dir, 'db.sqlite'); try { const f = fixture(file); const c = condition(); const continuation = buildV3DurableContinuation({...f.continuation, continuationId: 'restart-final', idempotencyKey: 'restart-final', attempt: 2, budgetState: {maxAttempts: 3, consumed: 2, deadlineAt: f.continuation.deadlineAt}}); new V3DurableContinuationStore(f.database).create(continuation, f.vector, c); f.queue.claimNext({...scope, owner: 'busy', nowIso: '2030-01-01T00:00:02Z', leaseMs: 1000}); const first = new V3ContinuationProcessor(f.database).process(wake(f, {continuationId: continuation.continuationId, nowIso: '2030-01-01T00:00:02Z'})); assert.equal(first.reasonCode, 'LEASE_UNAVAILABLE'); f.database.db.close(); const reopened = new V1Database(file); const second = new V3ContinuationProcessor(reopened).process(wake(f, {continuationId: continuation.continuationId, nowIso: '2030-01-01T00:00:04Z'})); assert.equal(second.reasonCode, 'LEASE_REACQUIRED'); assert.equal((reopened.db.prepare("SELECT attempt_number FROM v3_continuation_wake_events WHERE event_type='ATTEMPT_RESERVED'").get() as any).attempt_number, 3); assert.equal((reopened.db.prepare("SELECT count(*) AS n FROM v3_continuation_wake_events WHERE event_type='ATTEMPT_RESERVED'").get() as any).n, 1); assert.equal(new V3ContinuationProcessor(reopened).process(wake(f, {continuationId: continuation.continuationId, wakeEventId: 'restart-distinct', nowIso: '2030-01-01T00:00:04Z'})).reasonCode, 'BUDGET_EXHAUSTED'); reopened.db.close(); } finally { rmSync(dir, {recursive: true, force: true}); } });

test('GOAL-005 Host wakeEventId closed shape rejects missing empty accessor and extra fields', () => { const f = fixture(); const p = new V3ContinuationProcessor(f.database); const base:any = wake(f); for (const input of [{...base, wakeEventId: undefined}, {...base, wakeEventId: ''}, {...base, extra: true}]) assert.throws(() => p.process(input), /INVALID_WAKE/); let invoked = false; const accessor:any = {...base}; Object.defineProperty(accessor, 'wakeEventId', {enumerable: true, get() { invoked = true; throw Error('getter'); }}); assert.throws(() => p.process(accessor), /INVALID_WAKE/); assert.equal(invoked, false); f.database.db.close(); });
