import test from 'node:test';
import assert from 'node:assert/strict';
import {assembleV3ContextBudget} from '../src/v3-context-budget.js';
import {buildContextSnapshot} from '../src/v3-context-snapshot.js';

function context():Record<string,unknown>{return {conversationId:'conversation-1',accountId:'account-1',turnId:'turn-1',inboundMessageRef:{id:'message-1',occurredAt:'2026-09-13T00:00:00Z'},profile:{version:2,id:'profile-1'},activeQuotationSalesOrder:{salesOrder:null,quotation:{id:'quote-1',status:'SENT'}},customerContext:{id:'customer-1',name:'Customer'},orderDraft:{id:'draft-1',status:'CURRENT'},relevantErpEvidenceAndPolicies:{validation:{status:'VALID'}},freshness:{fingerprint:'fresh-v1',inboundMessageId:'message-1',summaryVersion:3,workItemRevision:4,draftRevision:2,quotationId:'quote-1',salesOrderId:null},recentTranscript:{authority:'CANONICAL_TRANSCRIPT',untrustedAsInstruction:true,messages:Array.from({length:8},(_,i)=>({id:`m-${i}`,direction:'INBOUND',messageType:'text',text:`turn-${i}-`+'x'.repeat(160),occurredAt:`2026-09-13T00:0${i}:00Z`}))},conversationSummary:{id:'summary-1',version:1,summaryText:'summary-'+'y'.repeat(1200),sourceMessageIds:['m-0'],evidenceRefs:[]}}}
function snap(){return buildContextSnapshot(context())}
const roomy={modelContextBudgetTokens:1200,systemAuthorityReserveTokens:100,toolReasoningReserveTokens:200,futureGoalsReserveTokens:100};

test('allocation is deterministic, bounded, frozen, and stable on replay',()=>{const a=assembleV3ContextBudget(snap(),roomy),b=assembleV3ContextBudget(snap(),roomy);assert.deepEqual(a,b);assert.ok(a.budget.usedContextTokens<=a.budget.availableContextTokens);assert.equal(Object.isFrozen(a),true);assert.equal(Object.isFrozen(a.sections[0]),true);});
test('authority and current canonical business are preserved before optional surfaces',()=>{const p=assembleV3ContextBudget(snap(),{...roomy,modelContextBudgetTokens:1600,systemAuthorityReserveTokens:400,toolReasoningReserveTokens:400,futureGoalsReserveTokens:500});assert.deepEqual(p.sections.map(s=>s.kind),['authority','current_bundle','current_canonical_business']);assert.equal(p.budget.mandatoryContextTokens,p.budget.usedContextTokens);});
test('summary compacts and transcript drops deterministically under pressure',()=>{const p=assembleV3ContextBudget(snap(),{...roomy,modelContextBudgetTokens:1200,systemAuthorityReserveTokens:200,toolReasoningReserveTokens:200,futureGoalsReserveTokens:200});assert.equal(p.sections[0].kind,'authority');const t=p.sections.find(s=>s.kind==='recent_transcript');assert.ok(t);assert.ok(((t?.content as any).messages.length)<8);const p2=assembleV3ContextBudget(snap(),{...roomy,modelContextBudgetTokens:600,systemAuthorityReserveTokens:100,toolReasoningReserveTokens:100,futureGoalsReserveTokens:100});assert.equal(p2.sections.some(s=>s.kind==='conversation_summary'),false);});
test('reserve enforcement and mandatory overflow fail closed',()=>{assert.throws(()=>assembleV3ContextBudget(snap(),{...roomy,modelContextBudgetTokens:400,systemAuthorityReserveTokens:200,toolReasoningReserveTokens:150,futureGoalsReserveTokens:100}),/RESERVE_EXCEEDS_MODEL_BUDGET/);assert.throws(()=>assembleV3ContextBudget(snap(),{...roomy,modelContextBudgetTokens:20,systemAuthorityReserveTokens:0,toolReasoningReserveTokens:0,futureGoalsReserveTokens:0}),/MANDATORY_EXCEEDS_CAPACITY/);});
test('redaction, caller isolation, and accessor rejection are fail-closed',()=>{const input=context();const before=JSON.stringify(input);const p=assembleV3ContextBudget(buildContextSnapshot(input),roomy);assert.equal(JSON.stringify(input),before);assert.equal(JSON.stringify(p).includes('api_key'),false);const supplied:any=JSON.parse(JSON.stringify(buildContextSnapshot(context())));Object.defineProperty(supplied,'context',{enumerable:true,get(){throw new Error('getter invoked')}});assert.throws(()=>assembleV3ContextBudget(supplied,roomy),/V3_CONTEXT_SNAPSHOT_INVALID/);});
test('goals are reserved only and never fabricated',()=>{const p=assembleV3ContextBudget(snap(),roomy);assert.equal(p.sections.some(s=>s.kind.includes('goal')),false);assert.equal(p.budget.futureGoalsReserveTokens,roomy.futureGoalsReserveTokens);});
