import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {test} from 'node:test';
import {V1Database} from '../src/database.js';
import {V3GoalProposalHost} from '../src/v3-goal-proposal.js';
import {buildConversationGoal} from '../src/v3-conversation-goal.js';
import {buildV3DurableContinuation,V3DurableContinuationStore,v3FreshnessVectorRef,v3ResumeConditionRef,type V3ContinuationHostCondition} from '../src/v3-durable-continuation.js';
import {buildV3FreshnessVectorFromDatabase,type V3FreshnessVectorInput} from '../src/v3-freshness-vector.js';

const scope={accountId:'demo-account',conversationId:'conv-001'};
const condition=(overrides:Partial<V3ContinuationHostCondition>={}):V3ContinuationHostCondition=>({accountId:scope.accountId,conversationId:scope.conversationId,resumeTriggerType:'EXTERNAL_EVENT',condition:'erp-check-1',...overrides});
function freshnessInput():Omit<V3FreshnessVectorInput,'authoritativeV2FreshnessFingerprint'>{return {identityScope:{accountId:scope.accountId,conversationId:scope.conversationId,customerId:'CUST-001',channelAccountId:scope.accountId},employeeProfile:{id:'sales-digital-employee',version:1},capabilityPolicy:{policyVersion:1,availableCapabilities:[]},workItemOrderDraftRefs:{workItem:null,orderDraft:null},canonicalBusiness:{quotations:[],acceptances:[],outbound:[],salesOrders:[]},relevantErpEvidence:[],goalGraph:{version:null,dependencyRefs:[]},attachmentExtraction:{version:null,dependencyRefs:[]},retentionAccess:{version:1,dependencyRefs:[]},conversationBundle:{conversationRevision:0,bundleRevision:0,messageRefs:[]}}}
function proof(database:V1Database){return buildV3FreshnessVectorFromDatabase(database.db,freshnessInput())}
function fixture(file=':memory:',goalStatus:'WAITING_EXTERNAL'|'OPEN'|'IN_PROGRESS'='WAITING_EXTERNAL'){
  const database=new V1Database(file);database.resetAndSeed();
  database.db.prepare("INSERT INTO messages(id,conversation_id,external_message_id,direction,message_type,text,sender_external_id,account_id,occurred_at) VALUES(?,?,?,?,?,?,?,?,?)").run('m1',scope.conversationId,'m1','INBOUND','TEXT','waiting','customer',scope.accountId,'2026-09-14T00:00:00.000Z');
  database.db.prepare("INSERT INTO work_items(id,account_id,conversation_id,customer_id,type,state,revision,goal_summary,source_message_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run('wi1',scope.accountId,scope.conversationId,'CUST-001','SALES_ORDER_REQUEST','DRAFTING',1,'external check','m1','2026-09-14T00:00:00.000Z','2026-09-14T00:00:00.000Z');
  const host=new V3GoalProposalHost(database);const goal=buildConversationGoal({goalId:'g1',...scope,sourceMessageIds:['m1'],sourceAttachmentIds:[],erpObjectRefs:[],parentGoalId:null,dependsOnGoalIds:[],relatedGoalIds:[],description:'external check',status:'OPEN',createdBy:'AGENT',createdAt:'2026-09-14T00:00:01.000Z',updatedAt:'2026-09-14T00:00:01.000Z',fulfillmentEvidenceRefs:[]});
  host.admit({scope,operation:'CREATE',expected:{goalId:null,revision:null,status:null},goal},{proposalId:'p1',idempotencyKey:'p1',createdAt:'2026-09-14T00:00:02.000Z'});
  if(goalStatus!=='OPEN')host.admit({scope,operation:'UPDATE',expected:{goalId:'g1',revision:1,status:'OPEN'},goal:{...goal,status:goalStatus,updatedAt:'2026-09-14T00:00:03.000Z'}},{proposalId:'p2',idempotencyKey:'p2',createdAt:'2026-09-14T00:00:03.000Z'});
  return {database,store:new V3DurableContinuationStore(database)};
}
function record(vector:ReturnType<typeof proof>,overrides:Record<string,unknown>={}){const c=condition();return buildV3DurableContinuation({continuationId:'c1',workItemId:'wi1',goalId:'g1',...scope,disposition:'WAITING_EXTERNAL',ownerType:'HOST',ownerId:'external-checker',state:'WAITING',resumeTriggerType:c.resumeTriggerType,resumeConditionRef:v3ResumeConditionRef(c),nextEligibleAt:null,deadlineAt:'2026-09-15T00:00:00.000Z',expectedFreshnessVectorRef:v3FreshnessVectorRef(vector),lastEvidenceRefs:[],lastEffectRefs:[],attempt:0,budgetState:{maxAttempts:3,consumed:0,deadlineAt:'2026-09-15T00:00:00.000Z'},idempotencyKey:'c1',createdAt:'2026-09-14T00:00:03.000Z',updatedAt:'2026-09-14T00:00:03.000Z',...overrides});}

test('GOAL-004 WAITING_EXTERNAL persists, reads back, and exact replay is idempotent',()=>{const f=fixture(),v=proof(f.database),value=record(v),row=f.store.create(value,v,condition());assert.equal(row.continuation_id,'c1');assert.deepEqual(f.store.create(value,v,condition()),row);const got=f.store.get(scope,'c1')!;assert.deepEqual(got,value);assert.equal(Object.isFrozen(got),true);assert.equal(Object.isFrozen(got.lastEvidenceRefs),true);assert.equal(Object.isFrozen(got.lastEffectRefs),true);assert.equal(Object.isFrozen(got.budgetState),true);assert.equal(f.database.db.prepare('SELECT count(*) AS n FROM durable_continuations').get().n,1);f.database.db.close();});

test('STILL_IN_PROGRESS supports durable READY work and nullable time deadline',()=>{const f=fixture(':memory:','OPEN'),v=proof(f.database),c=condition({resumeTriggerType:'NEW_INBOUND',condition:'new-message'}),value=record(v,{disposition:'STILL_IN_PROGRESS',state:'READY',resumeTriggerType:'NEW_INBOUND',resumeConditionRef:v3ResumeConditionRef(c),deadlineAt:null,nextEligibleAt:null,budgetState:{maxAttempts:3,consumed:0,deadlineAt:null}});assert.equal(f.store.create(value,v,c).goal_id,'g1');assert.equal(f.store.get(scope,'c1')?.deadlineAt,null);f.database.db.close();});

test('new writes require current DB-derived freshness while exact replay survives later staleness',()=>{const f=fixture(),v=proof(f.database),value=record(v),first=f.store.create(value,v,condition());f.database.db.prepare("UPDATE employee_profiles SET version=version+1 WHERE id='sales-digital-employee'").run();assert.deepEqual(f.store.create(value,v,condition()),first);const different=record(v,{continuationId:'c2',idempotencyKey:'c2'});assert.throws(()=>f.store.create(different,v,condition()),/PROFILE_VERSION_MISMATCH|FRESHNESS_STALE/);f.database.db.close();});

test('Host condition envelope is separate, exact, scoped, and bound to the persisted ref',()=>{const f=fixture(),v=proof(f.database),value=record(v);assert.equal(value.resumeConditionRef.includes('erp-check-1'),false);assert.throws(()=>f.store.create(value,v,condition({condition:'different'})),/CONDITION_SCOPE/);assert.throws(()=>f.store.create(value,v,{...condition(),accountId:'other'}),/CONDITION_SCOPE/);assert.throws(()=>f.store.create(value,v,{...condition(),extra:true} as any),/INPUT_SHAPE/);let called=0;const unsafe:any={...condition()};Object.defineProperty(unsafe,'condition',{enumerable:true,get(){called++;throw Error('getter')}});assert.throws(()=>f.store.create(value,v,unsafe),/INPUT_SHAPE/);assert.equal(called,0);f.database.db.close();});

test('continuation identity replay is exact and chimera/partial conflicts fail closed',()=>{const f=fixture(),v=proof(f.database),value=record(v);f.store.create(value,v,condition());assert.throws(()=>f.store.create(record(v,{idempotencyKey:'other'}),v,condition()),/IDEMPOTENCY_CONFLICT/);assert.throws(()=>f.store.create(record(v,{continuationId:'other'}),v,condition()),/IDEMPOTENCY_CONFLICT/);f.database.db.close();});

test('work item scope/customer/terminal and goal/disposition prerequisites fail closed',()=>{const a=fixture();a.database.db.prepare("UPDATE work_items SET customer_id='OTHER' WHERE id='wi1'").run();const av=proof(a.database);assert.throws(()=>a.store.create(record(av),av,condition()),/WORK_ITEM_SCOPE/);a.database.db.close();const b=fixture();b.database.db.prepare("INSERT INTO work_items(id,account_id,conversation_id,customer_id,type,state,revision,goal_summary,source_message_id,created_at,updated_at) VALUES('wi-done',?,?,?,?,?,?,?,?,?,?)").run(scope.accountId,scope.conversationId,'CUST-001','SALES_ORDER_REQUEST','COMPLETED',1,'x','m1','2026-09-14T00:00:00.000Z','2026-09-14T00:00:00.000Z');const bv=proof(b.database);assert.throws(()=>b.store.create(record(bv,{workItemId:'wi-done'}),bv,condition()),/WORK_ITEM_SCOPE/);assert.throws(()=>b.store.create(record(bv,{goalId:'missing'}),bv,condition()),/GOAL_NOT_FOUND/);assert.throws(()=>b.store.create(record(bv,{state:'READY'}),bv,condition()),/WAITING_STATE/);b.database.db.close();});

test('evidence/effect refs are typed and must exist in exact scope',()=>{const f=fixture(),v=proof(f.database);assert.throws(()=>f.store.create(record(v,{lastEvidenceRefs:['bad']}),v,condition()),/REFERENCE_UNKNOWN/);assert.throws(()=>f.store.create(record(v,{lastEvidenceRefs:['evidence:missing']}),v,condition()),/EVIDENCE_SCOPE/);assert.throws(()=>f.store.create(record(v,{lastEffectRefs:['effect:missing']}),v,condition()),/EFFECT_SCOPE/);f.database.db.close();});

test('budget/deadline coherence is bounded and nullable deadlines do not become a scheduling policy',()=>{const f=fixture(),v=proof(f.database);assert.throws(()=>record(v,{attempt:2,budgetState:{maxAttempts:3,consumed:1,deadlineAt:'2026-09-15T00:00:00.000Z'}}),/BUDGET_EXHAUSTED/);assert.throws(()=>record(v,{budgetState:{maxAttempts:1,consumed:1,deadlineAt:'2026-09-15T00:00:00.000Z'}}),/BUDGET_EXHAUSTED/);assert.throws(()=>record(v,{deadlineAt:null,budgetState:{maxAttempts:3,consumed:0,deadlineAt:'2026-09-15T00:00:00.000Z'}}),/BUDGET_DEADLINE_MISMATCH/);assert.throws(()=>record(v,{nextEligibleAt:'2026-09-16T00:00:00.000Z'}),/NEXT_ELIGIBLE_AFTER_DEADLINE/);f.database.db.close();});

test('closed-shape and array inputs reject accessor/hidden/symbol/sparse data without invoking getters',()=>{const f=fixture(),v=proof(f.database),base:any={...record(v)};let calls=0;Object.defineProperty(base,'ownerId',{enumerable:true,get(){calls++;throw Error('getter')}});assert.throws(()=>buildV3DurableContinuation(base),/INPUT_SHAPE/);assert.equal(calls,0);const hidden:any={...record(v)};Object.defineProperty(hidden,'extra',{value:true,enumerable:false});assert.throws(()=>buildV3DurableContinuation(hidden),/INPUT_SHAPE/);const symbolic:any={...record(v)};symbolic[Symbol('x')]=true;assert.throws(()=>buildV3DurableContinuation(symbolic),/INPUT_SHAPE/);const sparse:any={...record(v),lastEvidenceRefs:new Array(1)};assert.throws(()=>buildV3DurableContinuation(sparse),/EVIDENCE_REFS/);const arrayGetter:any[]=[];Object.defineProperty(arrayGetter,'0',{enumerable:true,get(){calls++;throw Error('array getter')}});arrayGetter.length=1;assert.throws(()=>buildV3DurableContinuation({...record(v),lastEvidenceRefs:arrayGetter}),/EVIDENCE_REFS/);assert.equal(calls,0);f.database.db.close();});

test('raw insert/update/delete are blocked and scoped get rejects malformed callers',()=>{const f=fixture(),v=proof(f.database),value=record(v);f.store.create(value,v,condition());assert.throws(()=>f.database.db.prepare("INSERT INTO durable_continuations(continuation_id,account_id,conversation_id,work_item_id,goal_id,record_json,record_hash,idempotency_key,created_at,updated_at) VALUES('x','demo-account','conv-001','wi1','g1','{}','h','x','a','a')").run(),/REQUIRES_SERVICE/);assert.throws(()=>f.database.db.prepare("UPDATE durable_continuations SET record_hash='x' WHERE continuation_id='c1'").run(),/IMMUTABLE_V3_CONTINUATION/);assert.throws(()=>f.database.db.prepare("DELETE FROM durable_continuations WHERE continuation_id='c1'").run(),/IMMUTABLE_V3_CONTINUATION/);assert.throws(()=>f.store.get({...scope,extra:true} as any,'c1'),/INPUT_SHAPE/);let calls=0;const unsafe:any={...scope};Object.defineProperty(unsafe,'accountId',{enumerable:true,get(){calls++;throw Error('getter')}});assert.throws(()=>f.store.get(unsafe,'c1'),/INPUT_SHAPE/);assert.equal(calls,0);f.database.db.close();});

test('file-backed restart preserves immutable continuation readback',()=>{const dir=mkdtempSync(join(tmpdir(),'v3-goal004-'));const file=join(dir,'db.sqlite');try{const f=fixture(file),v=proof(f.database),value=record(v);f.store.create(value,v,condition());f.database.db.close();const reopened=new V1Database(file),store=new V3DurableContinuationStore(reopened);assert.deepEqual(store.get(scope,'c1'),value);reopened.db.close();}finally{rmSync(dir,{recursive:true,force:true})}});
