import assert from 'node:assert/strict';
import {test} from 'node:test';
import {Worker} from 'node:worker_threads';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {V1Database} from '../src/database.js';
import {V3GoalProposalHost} from '../src/v3-goal-proposal.js';
import {buildConversationGoal} from '../src/v3-conversation-goal.js';

const scope={accountId:'demo-account',conversationId:'conv-001'};
function fixture(file=':memory:'){const database=new V1Database(file);database.resetAndSeed();for(const id of ['m1','m2','m3'])database.db.prepare("INSERT INTO messages(id,conversation_id,external_message_id,direction,message_type,text,sender_external_id,sender_phone,account_id,occurred_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(id,scope.conversationId,id,'INBOUND','TEXT',id,'customer',null,scope.accountId,'2026-09-14T00:00:00.000Z');return {database,host:new V3GoalProposalHost(database)};}
function goal(id:string,status:'OPEN'|'IN_PROGRESS'|'FULFILLED'|'SUPERSEDED'|'CANCELLED'='OPEN',source='m1'){return buildConversationGoal({goalId:id,...scope,sourceMessageIds:[source],sourceAttachmentIds:[],erpObjectRefs:[],parentGoalId:null,dependsOnGoalIds:[],relatedGoalIds:[],description:`goal ${id}`,status,createdBy:'AGENT',createdAt:'2026-09-14T00:00:01.000Z',updatedAt:'2026-09-14T00:00:01.000Z',fulfillmentEvidenceRefs:[]});}
function proposal(operation:any,g:any,expected:any){return {scope,operation,expected,goal:g};}
function envelope(id:string,at='2026-09-14T00:00:02.000Z'){return {proposalId:id,idempotencyKey:`idem-${id}`,createdAt:at};}
const fresh=(id:string,status:any,source='m2')=>buildConversationGoal({...goal(id,status,source),updatedAt:'2026-09-14T00:00:03.000Z'});

test('GOAL-003 lifecycle uses dedicated terminal events and active metadata refresh',()=>{const f=fixture();assert.equal(f.host.admit(proposal('CREATE',goal('g1'),{goalId:null,revision:null,status:null}),envelope('create')).event_type,'CREATED');assert.equal(f.host.admit(proposal('UPDATE',fresh('g1','OPEN'),{goalId:'g1',revision:1,status:'OPEN'}),envelope('refresh','2026-09-14T00:00:03.000Z')).event_type,'UPDATED');assert.equal(f.host.admit(proposal('UPDATE',fresh('g1','FULFILLED'),{goalId:'g1',revision:2,status:'OPEN'}),envelope('fulfill','2026-09-14T00:00:04.000Z')).event_type,'UPDATED');f.database.db.close();});
test('non-CREATE proposals cannot rewrite createdAt or regress updatedAt',()=>{const f=fixture();f.host.admit(proposal('CREATE',{...goal('g1'),updatedAt:'2026-09-14T00:00:03.000Z'},{goalId:null,revision:null,status:null}),envelope('create'));
  const rewritten={...fresh('g1','OPEN'),createdAt:'2026-09-14T00:00:09.000Z',updatedAt:'2026-09-14T00:00:09.000Z'};
  assert.throws(()=>f.host.admit(proposal('UPDATE',rewritten,{goalId:'g1',revision:1,status:'OPEN'}),envelope('rewrite')),/CREATED_AT_REWRITE/);
  const regressed={...fresh('g1','OPEN'),updatedAt:'2026-09-14T00:00:01.500Z'};
  assert.throws(()=>f.host.admit(proposal('UPDATE',regressed,{goalId:'g1',revision:1,status:'OPEN'}),envelope('regress')),/UPDATED_AT_REGRESSION/);
  f.database.db.close();});
test('SUPERSEDE and CANCEL are only active-to-terminal, and terminal goals cannot move',()=>{const f=fixture();f.host.admit(proposal('CREATE',goal('g1'),{goalId:null,revision:null,status:null}),envelope('create'));assert.equal(f.host.admit(proposal('SUPERSEDE',fresh('g1','SUPERSEDED'),{goalId:'g1',revision:1,status:'OPEN'}),envelope('sup')).event_type,'SUPERSEDED');assert.throws(()=>f.host.admit(proposal('CANCEL',fresh('g1','CANCELLED'),{goalId:'g1',revision:2,status:'SUPERSEDED'}),envelope('cancel')),/ILLEGAL_TRANSITION/);f.database.db.close();});
test('UPDATE cannot target CANCELLED or SUPERSEDED and terminal-operation bypass is rejected',()=>{const f=fixture();f.host.admit(proposal('CREATE',goal('g1'),{goalId:null,revision:null,status:null}),envelope('create'));assert.throws(()=>f.host.admit(proposal('UPDATE',fresh('g1','CANCELLED'),{goalId:'g1',revision:1,status:'OPEN'}),envelope('bad-cancel')),/ILLEGAL_TRANSITION/);assert.throws(()=>f.host.admit(proposal('UPDATE',fresh('g1','SUPERSEDED'),{goalId:'g1',revision:1,status:'OPEN'}),envelope('bad-sup')),/ILLEGAL_TRANSITION/);f.host.admit(proposal('CANCEL',fresh('g1','CANCELLED'),{goalId:'g1',revision:1,status:'OPEN'}),envelope('cancel'));assert.throws(()=>f.host.admit(proposal('SUPERSEDE',fresh('g1','SUPERSEDED'),{goalId:'g1',revision:2,status:'CANCELLED'}),envelope('bypass')),/ILLEGAL_TRANSITION/);f.database.db.close();});
test('semantic proposal and Host envelope are independently exact, accessor-safe, and replay/chimera fenced',()=>{const f=fixture();const p=proposal('CREATE',goal('g1'),{goalId:null,revision:null,status:null}),e=envelope('create');const committed=f.host.admit(p,e);assert.deepEqual(f.host.admit(p,e),committed);f.host.admit(proposal('UPDATE',fresh('g1','OPEN'),{goalId:'g1',revision:1,status:'OPEN'}),envelope('advance','2026-09-14T00:00:03.000Z'));assert.deepEqual(f.host.admit(p,e),committed);assert.throws(()=>f.host.admit({...p,proposalId:'model-owned'} as any,e),/INPUT_SHAPE/);assert.throws(()=>f.host.admit(p,{...e,extra:true}),/INPUT_SHAPE/);assert.throws(()=>f.host.admit(p,{...e,idempotencyKey:'other'}),/IDEMPOTENCY_CONFLICT/);const unsafe:any={...p};Object.defineProperty(unsafe,'operation',{enumerable:true,get(){throw Error('getter invoked')}});assert.throws(()=>f.host.admit(unsafe,e),/INPUT_SHAPE/);const unsafeEnvelope:any={...e};Object.defineProperty(unsafeEnvelope,'createdAt',{enumerable:true,get(){throw Error('getter invoked')}});assert.throws(()=>f.host.admit(p,unsafeEnvelope),/INPUT_SHAPE/);f.database.db.close();});
test('source-message provenance remains exact-scope Host validation',()=>{const f=fixture();assert.throws(()=>f.host.admit(proposal('CREATE',goal('g1','OPEN','missing'),{goalId:null,revision:null,status:null}),envelope('bad')),/SOURCE_PROVENANCE/);f.database.db.close();});

test('two independent SQLite writers race rev1/OPEN with one success and one stale',async()=>{const dir=mkdtempSync(join(tmpdir(),'v3-goal003-race-')),file=join(dir,'db.sqlite');try{const f=fixture(file);f.host.admit(proposal('CREATE',goal('g1'),{goalId:null,revision:null,status:null}),envelope('create'));f.database.db.close();const barrier=new SharedArrayBuffer(4),specs=['IN_PROGRESS','FULFILLED'].map((status,i)=>({file,barrier,proposal:proposal('UPDATE',fresh('g1',status,i?'m3':'m2'),{goalId:'g1',revision:1,status:'OPEN'}),envelope:envelope(`race-${i}`,`2026-09-14T00:00:0${3+i}.000Z`)}));const workers=specs.map(data=>new Worker(new URL('./v3-goal-proposal-race-worker.ts',import.meta.url),{workerData:data,execArgv:['--import','tsx']}));await Promise.all(workers.map(w=>new Promise<void>((resolve,reject)=>{const onError=(error:Error)=>{w.off('message',onReady);reject(error)};const onReady=(m:any)=>{if(!m?.ready){w.off('error',onError);reject(Error(String(m)));return;}w.off('error',onError);resolve();};w.once('message',onReady);w.once('error',onError);})));const resultPromises=workers.map(w=>new Promise<any>((resolve,reject)=>{const onError=(error:Error)=>{w.off('message',onResult);reject(error)};const onExit=(code:number)=>{if(code!==0){w.off('message',onResult);w.off('error',onError);reject(Error(`worker exited before result: ${code}`));}};const onResult=(message:any)=>{w.off('error',onError);w.off('exit',onExit);resolve(message);};w.once('message',onResult);w.once('error',onError);w.once('exit',onExit);}));Atomics.store(new Int32Array(barrier),0,1);Atomics.notify(new Int32Array(barrier),0,2);const results=await Promise.all(resultPromises);await Promise.all(workers.map(w=>new Promise<void>((resolve,reject)=>{if(w.threadId===-1){resolve();return;}w.once('exit',code=>code===0?resolve():reject(Error(`worker exit ${code}`)));w.once('error',reject);})));const successes=results.filter(r=>r.ok),stales=results.filter(r=>!r.ok&&/STALE/.test(r.error));assert.equal(successes.length,1);assert.equal(stales.length,1);const check=new V1Database(file);assert.equal(check.db.prepare('SELECT count(*) AS n FROM conversation_goal_events').get().n,2);assert.deepEqual(check.db.prepare('SELECT revision FROM conversation_goal_events ORDER BY revision').all(),[{revision:1},{revision:2}]);check.db.close();}finally{rmSync(dir,{recursive:true,force:true});}});
