import assert from 'node:assert/strict';
import test from 'node:test';
import {V1Database} from '../src/database.js';
import {OrderDraftService,WorkItemService} from '../src/v2-workspace.js';
import {WorkspaceMigrationService} from '../src/v2-workspace-migration.js';
import {createMigrationApprovalAuthority} from '../src/migration-auth.js';
import {issueBoundMigrationApproval} from './migration-approval-helper.js';
import {buildV3AttachmentSource} from '../src/v3-attachment-source.js';
import {runV3AttachmentExtractionAdapter} from '../src/v3-attachment-extraction.js';
import {buildV3AttachmentEvidence} from '../src/v3-attachment-evidence.js';
import {createV3AttachmentRetrieval,type V3AttachmentReadResult} from '../src/v3-attachment-retrieval.js';
import {reverifyV3HistoricalMediaForConsequentialDecision} from '../src/v3-multimodal-canonical-reverify.js';

const A='demo-account',C='conv-001',U='CUST-001',M='mm006-source-message';
const scope=Object.freeze({tenantId:'tenant-1',accountId:A,channelAccountId:A,conversationId:C,customerId:U});
function setup(){const authority=createMigrationApprovalAuthority(),db=new V1Database(':memory:',authority);db.resetAndSeed();db.db.prepare("INSERT INTO messages(id,conversation_id,external_message_id,direction,message_type,text,sender_external_id,sender_phone,account_id,occurred_at) VALUES(?,?,?,?,?,?,?,?,?,datetime('now'))").run(M,C,M,'INBOUND','text','order','+6591110001','+6591110001',A);const migration=new WorkspaceMigrationService(db,authority),work=new WorkItemService(db),shadow=migration.shadowImport({accountId:A,conversationId:C,customerId:U,idempotencyKey:'mm006-shadow',approval:issueBoundMigrationApproval(authority,migration,'mm006','MIGRATION_OWNER','SHADOW_IMPORT',{accountId:A,conversationId:C,customerId:U})});migration.promoteCanary({accountId:A,conversationId:C,customerId:U,expectedLegacySourceHash:shadow.sourceHash!,expectedWorkItemId:null,expectedDraftRevision:null,idempotencyKey:'mm006-promote',approval:issueBoundMigrationApproval(authority,migration,'mm006','V1_OWNER','PROMOTE_CANARY',{accountId:A,conversationId:C,customerId:U},{expectedHash:shadow.sourceHash!,expectedWorkItemId:null,expectedDraftRevision:null})});const item=work.getOrCreate({accountId:A,conversationId:C,customerId:U,sourceMessageId:M,idempotencyKey:'mm006-work'});const draft=new OrderDraftService(db,work).create({workItemId:item.id,accountId:A,conversationId:C,customerId:U,sourceMessageId:M,warehouseId:'SG-MAIN',currency:'SGD',lines:[{lineNo:1,requestedWording:'ayam',quantity:1,requestedUom:'CTN'}]},{idempotencyKey:'mm006-draft',expectedWorkItemRevision:item.revision});return{db,draft};}
function read(media:'PDF'|'IMAGE',kind:'TEXT'|'OCR'|'VISION',output:unknown,freshnessState:'CURRENT'|'STALE'='CURRENT',lineage=scope):V3AttachmentReadResult{const source=buildV3AttachmentSource({scope:lineage,attachmentId:`attachment-${media}-${kind}-${freshnessState}`,sourceMessageId:`message-${media}-${kind}-${freshnessState}`,sourceRef:`media://${media.toLowerCase()}`,mimeType:media==='PDF'?'application/pdf':'image/png',bytes:new Uint8Array([7,8,9])});const extraction=runV3AttachmentExtractionAdapter({adapterId:'fixture/mm006',adapterVersion:'1',extract:()=>output},{source,mediaKind:media,extractionKind:kind,extractionVersion:'fixture-v1',derivedAt:'2026-09-19T00:00:00.000Z',provenanceRefs:[source.sourceMessageId,source.attachmentId],pageNumber:1,regionRef:null,timeRange:null});assert.equal(extraction.status,'SUCCEEDED');const actual=freshnessState==='CURRENT'?extraction:Object.freeze({...extraction,evidence:buildV3AttachmentEvidence({source,mediaType:media,extractionType:kind,extractionVersion:'fixture-v1',extractorRef:'fixture/mm006',extractorVersion:'1',pageNumber:1,regionRef:null,boundingBox:null,timeRange:null,derivedAt:'2026-09-19T00:00:00.000Z',freshnessState,provenanceRefs:[source.sourceMessageId,source.attachmentId]})});return createV3AttachmentRetrieval(lineage,Object.freeze([source]),Object.freeze([actual])).attachment_read({evidenceId:actual.evidence!.evidenceId})}

test('old PDF price cannot override fresh canonical ERP price',async()=>{const x=setup(),historical=read('PDF','TEXT',{text:'old price SGD 47.00'});const out=await reverifyV3HistoricalMediaForConsequentialDecision(x.db,{attachmentRead:historical,claim:{kind:'PRICE',draftId:x.draft.id,draftRevision:1,lineNo:1,productId:'FCH-WHOLE-12',unitPriceCents:4700}});assert.equal(out.verdict,'REPLAN_REQUIRED');assert.equal(out.reasonCode,'HISTORICAL_MEDIA_CONFLICT');assert.equal(out.mayUseForConsequentialDecision,false);assert.equal(out.grantsEffects,false)});

test('old stock screenshot cannot override current ERP shortage',async()=>{const x=setup();x.db.db.prepare("UPDATE stock_balances SET quantity_base='0' WHERE product_id='FCH-WHOLE-12' AND warehouse_id='SG-MAIN'").run();const historical=read('IMAGE','VISION',{description:'warehouse screen shows stock available'});const out=await reverifyV3HistoricalMediaForConsequentialDecision(x.db,{attachmentRead:historical,claim:{kind:'STOCK',draftId:x.draft.id,draftRevision:1,lineNo:1,available:true}});assert.equal(out.verdict,'REPLAN_REQUIRED');assert.equal(out.reasonCode,'HISTORICAL_MEDIA_CONFLICT');assert.equal(out.mayUseForConsequentialDecision,false)});

test('old PDF status cannot override current canonical quotation status',async()=>{const x=setup();x.db.db.prepare('INSERT INTO quotations(id,quotation_no,customer_id,status,currency,quotation_date,valid_until,source_conversation_id,source_message_id,subtotal_cents,tax_cents,grand_total_cents) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run('q-mm006','QT-MM006',U,'ACCEPTED','SGD','2026-09-19','2026-09-30',C,M,4800,0,4800);const historical=read('PDF','OCR',{text:'Quotation QT-MM006 status SENT'});const out=await reverifyV3HistoricalMediaForConsequentialDecision(x.db,{attachmentRead:historical,claim:{kind:'STATUS',objectType:'QUOTATION',objectId:'q-mm006',status:'SENT'}});assert.equal(out.verdict,'REPLAN_REQUIRED');assert.equal(out.reasonCode,'HISTORICAL_MEDIA_CONFLICT')});

test('matching fresh canonical ERP truth is usable only as admission input and never grants effects',async()=>{const x=setup(),historical=read('PDF','TEXT',{text:'current price SGD 48.00'});const out=await reverifyV3HistoricalMediaForConsequentialDecision(x.db,{attachmentRead:historical,claim:{kind:'PRICE',draftId:x.draft.id,draftRevision:1,lineNo:1,productId:'FCH-WHOLE-12',unitPriceCents:4800}});assert.equal(out.verdict,'CURRENT_ERP_MATCH');assert.equal(out.reasonCode,'MATCH');assert.equal(out.mayUseForConsequentialDecision,true);assert.equal(out.grantsEffects,false);assert.equal(out.requiresSideEffectAdmission,true);assert.equal(out.aiAuthorityCutoff,'SALES_ORDER.DRAFT');assert.equal(out.untrustedHistoricalMedia,true);assert(Object.isFrozen(out));assert(out.canonicalEvidenceRefs.length>0)});

test('stale historical media and stale draft revision fail closed',async()=>{const x=setup(),stale=read('PDF','TEXT',{text:'old price'},'STALE');const a=await reverifyV3HistoricalMediaForConsequentialDecision(x.db,{attachmentRead:stale,claim:{kind:'PRICE',draftId:x.draft.id,draftRevision:1,lineNo:1,productId:'FCH-WHOLE-12',unitPriceCents:4800}});assert.equal(a.reasonCode,'HISTORICAL_EVIDENCE_STALE');assert.equal(a.mayUseForConsequentialDecision,false);const b=await reverifyV3HistoricalMediaForConsequentialDecision(x.db,{attachmentRead:read('PDF','TEXT',{text:'price'}),claim:{kind:'PRICE',draftId:x.draft.id,draftRevision:2,lineNo:1,productId:'FCH-WHOLE-12',unitPriceCents:4800}});assert.equal(b.reasonCode,'CANONICAL_REVERIFY_REQUIRED');assert.equal(b.mayUseForConsequentialDecision,false)});

test('cross-scope attachment and malformed accessor/proxy input fail closed',async()=>{const x=setup(),other=Object.freeze({...scope,conversationId:'other-conversation'}),historical=read('PDF','TEXT',{text:'price'},'CURRENT',other);await assert.rejects(()=>reverifyV3HistoricalMediaForConsequentialDecision(x.db,{attachmentRead:historical,claim:{kind:'PRICE',draftId:x.draft.id,draftRevision:1,lineNo:1,productId:'FCH-WHOLE-12',unitPriceCents:4800}}),/CANONICAL_SCOPE/);const valid=read('PDF','TEXT',{text:'price'});const accessor=Object.defineProperty({attachmentRead:valid},'claim',{enumerable:true,get(){return {kind:'PRICE'}}});await assert.rejects(()=>reverifyV3HistoricalMediaForConsequentialDecision(x.db,accessor as any),/INPUT/);await assert.rejects(()=>reverifyV3HistoricalMediaForConsequentialDecision(x.db,new Proxy({attachmentRead:valid,claim:{kind:'PRICE',draftId:x.draft.id,draftRevision:1,lineNo:1,productId:'FCH-WHOLE-12',unitPriceCents:4800}}, {}) as any),/INPUT/)});
