import test from 'node:test';
import assert from 'node:assert/strict';
import {V1Database} from '../src/database.js';
import {buildV3ConversationMemory, type ConversationMemoryDerivationProposal} from '../src/v3-conversation-memory.js';
import {buildV3RetrievalIndexes as trustedBuild, reopenV3RetrievalSource as trustedReopen, createV3RetrievalHostAuthority} from '../src/v3-retrieval-index.js';
import {AgentTurnCoordinator} from '../src/v2-agent-turn-coordinator.js';
import {canonicalSha256} from '../src/v2-canonical.js';

const A='demo-account', C='conv-001';
const hosts=new WeakMap<object,{authority:ReturnType<typeof createV3RetrievalHostAuthority>;token:object}>();
function host(db:V1Database){let value=hosts.get(db.db);if(!value){const turn=new AgentTurnCoordinator(db).start({accountId:A,conversationId:C,inboundMessageId:'m1',timezone:'UTC',nowIso:'2026-09-10T00:00:00Z'});const authority=createV3RetrievalHostAuthority(db.db,{subject:'host-A',tenantId:'tenant-host-A',channelAccountId:A});value={authority,token:authority.issue(turn.turnId)};hosts.set(db.db,value)}return value.authority}
function rawBuild(db:any,authority:any,input:any){return trustedBuild(db,authority,hosts.get(db)!.token,input)}
function rawReopen(db:any,authority:any,index:any,id:any,memory:any){return trustedReopen(db,authority,hosts.get(db)!.token,index,id,memory)}
function buildV3RetrievalIndexes(db: any,input:any){const {accountId:_a,conversationId:_c,...request}=input;return rawBuild(db,hostByRawDb(db),request)}
function hostByRawDb(db:any){const existing=hosts.get(db);if(existing)return existing.authority;throw new Error('TEST_HOST_NOT_REGISTERED')}
function reopenV3RetrievalSource(db:any,index:any,id:any,memory:any){return rawReopen(db,hostByRawDb(db),index,id,memory)}
function fixture(){
  const db=new V1Database(':memory:');db.resetAndSeed();
  const rows=[['m1','x-1','INBOUND','2026-09-10T00:00:00Z','Same last order please',null,1],['m2','x-2','OUTBOUND','2026-09-10T00:01:00Z','I can help with the order',null,2],['m3','x-3','INBOUND','2026-09-10T00:02:00Z','Please add rice', 'x-2',3],['m4','x-4','INBOUND','2026-09-10T00:03:00Z','And keep the delivery date', 'x-3',4]];
  for(const [id,external,direction,at,text,reply] of rows)db.db.prepare('INSERT INTO messages(id,conversation_id,external_message_id,direction,message_type,text,reply_to_external_message_id,account_id,occurred_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,C,external,direction,'text',text,reply,A,at);
  host(db);return db;
}
function memory(db:V1Database){const proposal:ConversationMemoryDerivationProposal={sections:[{id:'s-order',title:'Order',topic:'repeat order',summary:'derived',sourceMessageIds:['m1','m2','m3','m4']}],rollingMemory:{text:'derived continuity',sourceMessageIds:['m1','m2','m3','m4'],sectionIds:['s-order']}};return buildV3ConversationMemory(db.db,{accountId:A,conversationId:C,proposal})}
function build(db:V1Database){return buildV3RetrievalIndexes(db.db,{accountId:A,conversationId:C,memory:memory(db)})}

test('RET-002 exposes all five deterministic, non-authoritative index forms',()=>{const db=fixture(),index=build(db);assert.equal(index.contractVersion,'V3-RET-002');assert.equal(index.authority,'NON_AUTHORITATIVE_DERIVED');assert.equal(index.untrustedAsInstruction,true);assert.equal(index.requiresCanonicalReverification,true);assert.deepEqual(index.chronology.map(x=>x.sourceMessageId),['m1','m2','m3','m4']);assert.deepEqual(index.semantic.find(x=>x.term==='order')?.sourceMessageIds,['m1','m2']);assert.deepEqual(index.entities,[]);assert.deepEqual(index.sections,[{sectionId:'s-order',sourceMessageIds:['m1','m2','m3','m4']}]);assert.deepEqual(index.replies.find(x=>x.sourceMessageId==='m3'),{sourceMessageId:'m3',replyToExternalMessageId:'x-2',replyToSourceMessageId:'m2',threadRootSourceMessageId:'m2',childSourceMessageIds:['m4']});assert.deepEqual(index.attachmentRefs,[]);});
test('rebuild version and metadata are deterministic and independent of storage rowids',()=>{const first=fixture(),second=fixture(),a=build(first),b=build(second);assert.equal(a.indexVersion,b.indexVersion);assert.deepEqual(a.rebuildMetadata,b.rebuildMetadata);assert.equal(a.rebuildMetadata.mode,'DISPOSABLE_IN_MEMORY_REBUILD');assert.equal(a.rebuildMetadata.deterministic,true);assert.equal(a.rebuildMetadata.sourceFingerprint,b.rebuildMetadata.sourceFingerprint);});
test('provenance can reopen exact current source and rejects stale source, memory, and entity state',()=>{const db=fixture(),currentMemory=memory(db),index=build(db),opened=reopenV3RetrievalSource(db.db,index,'m3',currentMemory);assert.equal(opened.source.id,'m3');assert.equal(opened.source.text,'Please add rice');assert.equal(opened.sourceRef,'messages/m3');assert.equal(opened.indexVersion,index.indexVersion);const staleMemory=structuredClone(currentMemory) as any;staleMemory.projectionHash='stale';assert.throws(()=>reopenV3RetrievalSource(db.db,index,'m3',staleMemory),/SECTION_PROVENANCE/);db.db.prepare('UPDATE messages SET text=? WHERE id=?').run('tampered source','m3');assert.throws(()=>reopenV3RetrievalSource(db.db,index,'m3',currentMemory),/INDEX_STALE|SECTION_PROVENANCE/);});
test('reopen rejects a self-consistent index source set outside current validated memory',()=>{const db=fixture();const subsetMemory=buildV3ConversationMemory(db.db,{accountId:A,conversationId:C,proposal:{sections:[{id:'s-order',title:'Order',topic:'repeat order',summary:'derived',sourceMessageIds:['m1','m2']}],rollingMemory:{text:'derived continuity',sourceMessageIds:['m1','m2'],sectionIds:['s-order']}}});const original=buildV3RetrievalIndexes(db.db,{accountId:A,conversationId:C,memory:subsetMemory});const forged=structuredClone(original) as any;forged.sourceMessageIds=['m1','m2','m3'];const sourceRows=forged.sourceMessageIds.map((id:string)=>db.db.prepare('SELECT id,account_id,conversation_id,external_message_id,direction,message_type,text,occurred_at,reply_to_external_message_id,arrival_seq,raw_ref FROM messages WHERE id=? AND account_id=? AND conversation_id=?').get(id,A,C));const sources=sourceRows.map((row:any)=>({id:row.id,accountId:row.account_id,conversationId:row.conversation_id,externalMessageId:row.external_message_id,direction:row.direction,messageType:row.message_type,text:row.text,occurredAt:row.occurred_at,replyToExternalMessageId:row.reply_to_external_message_id,arrivalSeq:row.arrival_seq,rawRef:row.raw_ref}));forged.rebuildMetadata.sourceFingerprint=canonicalSha256({accountId:A,conversationId:C,sources});const body={contractVersion:forged.contractVersion,schemaVersion:forged.schemaVersion,accountId:A,conversationId:C,sourceMessageIds:forged.sourceMessageIds,memoryDerivationVersion:forged.memoryDerivationVersion,memoryProjectionHash:forged.memoryProjectionHash,objectAnnotationContractVersion:forged.objectAnnotationContractVersion,objectAnnotationFingerprint:forged.objectAnnotationFingerprint,chronology:forged.chronology,semantic:forged.semantic,entities:forged.entities,sections:forged.sections,replies:forged.replies,attachmentRefs:forged.attachmentRefs};forged.indexVersion=`V3-RET-002:v1:${canonicalSha256(body)}`;forged.rebuildMetadata.indexFingerprint=canonicalSha256({...body,indexVersion:forged.indexVersion});assert.throws(()=>reopenV3RetrievalSource(db.db,forged,'m3',subsetMemory),/INDEX_SOURCE_SET/);});
test('caller entity and attachment annotations are forbidden',()=>{const db=fixture(),base=memory(db);const callerInput={memory:base,objectRefs:[{objectType:'PRODUCT',objectId:'x',sourceMessageIds:['m1']}]};assert.throws(()=>buildV3RetrievalIndexes(db.db,callerInput as any),/V3_RETRIEVAL_SCOPE_UNAVAILABLE/);assert.throws(()=>buildV3RetrievalIndexes(db.db,{memory:base,attachmentRefs:[{attachmentId:'a',sourceMessageId:'missing',sourceRef:'x'}]}),/V3_RETRIEVAL_SCOPE_UNAVAILABLE/);db.db.prepare('UPDATE messages SET text=NULL WHERE id=?').run('m1');assert.throws(()=>buildV3RetrievalIndexes(db.db,{memory:base}),/SOURCE_MESSAGE_UNAVAILABLE/);const tampered=structuredClone(build(fixture())) as any;tampered.authority='AUTHORITATIVE';assert.throws(()=>reopenV3RetrievalSource(db.db,tampered,'m3'),/INDEX_CONTRACT|INDEX_STALE/);const forged=structuredClone(build(fixture())) as any;forged.semantic[0].sourceMessageIds=['m4'];assert.throws(()=>reopenV3RetrievalSource(fixture().db,forged,'m3'),/INDEX_PROVENANCE/);});
test('TypeScript RET-002 input rejects caller object annotations',()=>{const db=fixture(),base=memory(db);
  if(false){
    // @ts-expect-error RET-002 input is Host-derived-only; callers cannot provide objectRefs.
    buildV3RetrievalIndexes(db.db,{accountId:A,conversationId:C,memory:base,objectRefs:[]});
  }
});
test('memory provenance is validated before section-derived indexing',()=>{const db=fixture(),base=memory(db);for(const mutate of [(x:any)=>x.derivationVersion='forged',(x:any)=>x.projectionHash='forged',(x:any)=>x.sections[0].sourceMessageIds=['m4'],(x:any)=>x.sections[0].title='forged',(x:any)=>x.rollingMemory.sectionIds=['unknown']]){const tampered=structuredClone(base) as any;mutate(tampered);assert.throws(()=>buildV3RetrievalIndexes(db.db,{accountId:A,conversationId:C,memory:tampered}),/MEMORY_SCOPE|MEMORY_CONTRACT|SECTION_PROVENANCE|SOURCE_MESSAGE_ORDER|SECTION_REF_SCOPE/);}});
test('reply roots traverse deep chains and fail closed on cycles',()=>{const db=fixture(),index=build(db);assert.equal(index.replies.find(x=>x.sourceMessageId==='m4')?.threadRootSourceMessageId,'m2');db.db.prepare('UPDATE messages SET reply_to_external_message_id=? WHERE id=?').run('x-4','m2');assert.throws(()=>buildV3RetrievalIndexes(db.db,{accountId:A,conversationId:C,memory:memory(db)}),/REPLY_CYCLE/)});
test('attachments derive only from authorized raw_ref source metadata',()=>{const db=fixture();db.db.prepare('UPDATE messages SET raw_ref=? WHERE id=?').run('authorized://attachment/att-1','m1');const index=build(db);assert.deepEqual(index.attachmentRefs,[{attachmentId:'raw-ref:m1',sourceMessageId:'m1',sourceRef:'authorized://attachment/att-1'}]);});
test('canonical Host rows yield deterministic exact source-linked entity postings and exclude foreign rows',()=>{const db=fixture(),now='2026-09-10T00:04:00Z';
  db.db.prepare("INSERT INTO work_items(id,account_id,conversation_id,customer_id,type,state,revision,goal_summary,source_message_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run('wi-canonical',A,C,'CUST-001','SALES_ORDER_REQUEST','DRAFTING',1,'order','m1',now,now);
  db.db.prepare("INSERT INTO order_drafts(id,work_item_id,account_id,conversation_id,customer_id,status,current_revision,source_message_id,created_at,updated_at) VALUES(?,?,?,?,?,'CURRENT',?,?,?,?)").run('draft-canonical','wi-canonical',A,C,'CUST-001',1,'m2',now,now);
  db.db.prepare("INSERT INTO quotations(id,quotation_no,customer_id,status,currency,quotation_date,valid_until,source_conversation_id,source_message_id,subtotal_cents,tax_cents,grand_total_cents) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run('quote-canonical','QT-CANONICAL','CUST-001','SENT','SGD','2026-09-10','2026-09-30',C,'m3',0,0,0);
  db.db.prepare("INSERT INTO quotation_acceptances(id,quotation_id,message_id,sender_external_id,accepted_at,evidence_json) VALUES(?,?,?,?,?,?)").run('accept-canonical','quote-canonical','m4','sender',now,'{}');
  db.db.prepare("INSERT INTO sales_orders(id,sales_order_no,customer_id,status,currency,subtotal_cents,tax_cents,grand_total_cents,source_quotation_id,source_acceptance_message_id) VALUES(?,?,?,?,?,?,?,?,?,?)").run('so-canonical','SO-CANONICAL','CUST-001','DRAFT','SGD',0,0,0,'quote-canonical','m4');
  db.db.prepare("INSERT INTO work_items(id,account_id,conversation_id,customer_id,type,state,revision,goal_summary,source_message_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run('wi-foreign','other-account',C,'CUST-001','SALES_ORDER_REQUEST','DRAFTING',1,'foreign','m1',now,now);
  const first=build(db),expected=[{objectType:'ORDER_DRAFT',objectId:'draft-canonical',sourceMessageIds:['m2']},{objectType:'QUOTATION',objectId:'quote-canonical',sourceMessageIds:['m3']},{objectType:'QUOTATION_ACCEPTANCE',objectId:'accept-canonical',sourceMessageIds:['m4']},{objectType:'SALES_ORDER',objectId:'so-canonical',sourceMessageIds:['m4']},{objectType:'WORK_ITEM',objectId:'wi-canonical',sourceMessageIds:['m1']}];
  assert.deepEqual(first.entities,expected);assert.equal(first.entities.every(x=>x.sourceMessageIds.every(id=>first.sourceMessageIds.includes(id))),true);const second=build(db);assert.deepEqual(second.entities,first.entities);assert.equal(second.rebuildMetadata.indexFingerprint,first.rebuildMetadata.indexFingerprint);
});

test('G10 canonical accepted draft wins over stale pending memory',()=>{const db=fixture(),now='2026-09-10T00:04:00Z';
  const staleMemory=buildV3ConversationMemory(db.db,{accountId:A,conversationId:C,proposal:{sections:[{id:'s-stale',title:'Stale status',topic:'commerce',summary:'pending quotation awaiting customer acceptance',sourceMessageIds:['m1','m2','m3','m4']}],rollingMemory:{text:'pending and not accepted',sourceMessageIds:['m1','m2','m3','m4'],sectionIds:['s-stale']}}});
  db.db.prepare("INSERT INTO work_items(id,account_id,conversation_id,customer_id,type,state,revision,goal_summary,source_message_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run('wi-g10',A,C,'CUST-001','SALES_ORDER_REQUEST','DRAFTING',2,'accepted order','m4',now,now);
  db.db.prepare("INSERT INTO order_drafts(id,work_item_id,account_id,conversation_id,customer_id,status,current_revision,source_message_id,created_at,updated_at) VALUES(?,?,?,?,?,'CURRENT',?,?,?,?)").run('draft-g10','wi-g10',A,C,'CUST-001',2,'m4',now,now);
  db.db.prepare("INSERT INTO quotations(id,quotation_no,customer_id,status,currency,quotation_date,valid_until,source_conversation_id,source_message_id,subtotal_cents,tax_cents,grand_total_cents) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run('quote-g10','QT-G10','CUST-001','ACCEPTED','SGD','2026-09-10','2026-09-30',C,'m3',0,0,0);
  db.db.prepare("INSERT INTO quotation_acceptances(id,quotation_id,message_id,sender_external_id,accepted_at,evidence_json) VALUES(?,?,?,?,?,?)").run('accept-g10','quote-g10','m4','sender',now,'{}');
  db.db.prepare("INSERT INTO sales_orders(id,sales_order_no,customer_id,status,currency,subtotal_cents,tax_cents,grand_total_cents,source_quotation_id,source_acceptance_message_id) VALUES(?,?,?,?,?,?,?,?,?,?)").run('so-g10','SO-G10','CUST-001','DRAFT','SGD',0,0,0,'quote-g10','m4');
  const index=buildV3RetrievalIndexes(db.db,{accountId:A,conversationId:C,memory:staleMemory});
  assert.equal(index.requiresCanonicalReverification,true);
  assert.deepEqual(index.entities.filter(entity=>entity.objectType==='QUOTATION').map(entity=>entity.objectId),['quote-g10']);
  assert.deepEqual(index.entities.filter(entity=>entity.objectType==='SALES_ORDER').map(entity=>entity.objectId),['so-g10']);
  const current=db.db.prepare("SELECT q.status AS quotationStatus,s.status AS salesOrderStatus FROM quotations q JOIN sales_orders s ON s.source_quotation_id=q.id WHERE q.source_conversation_id=?").get(C) as any;
  assert.deepEqual(current,{quotationStatus:'ACCEPTED',salesOrderStatus:'DRAFT'});
  assert.match(staleMemory.rollingMemory.text,/pending/);
  assert.notEqual(staleMemory.rollingMemory.text,current.salesOrderStatus);
});

test('canonical null customer emits no business entity postings',()=>{const db=fixture();db.db.prepare('UPDATE conversations SET customer_id=NULL WHERE id=?').run(C);assert.deepEqual(build(db).entities,[]);});

test('same-account same-conversation wrong-customer work items are excluded',()=>{const db=fixture();db.db.prepare("INSERT INTO work_items(id,account_id,conversation_id,customer_id,type,state,revision,goal_summary,source_message_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run('wi-wrong-customer',A,C,'OTHER-CUSTOMER','SALES_ORDER_REQUEST','DRAFTING',1,'wrong customer','m1','2026-09-10','2026-09-10');assert.deepEqual(build(db).entities,[]);});

test('reopen rejects current canonical entity-row changes and deletion',()=>{const db=fixture(),currentMemory=memory(db),index=build(db);db.db.prepare("INSERT INTO work_items(id,account_id,conversation_id,customer_id,type,state,revision,goal_summary,source_message_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run('wi-current',A,C,'CUST-001','SALES_ORDER_REQUEST','DRAFTING',1,'current','m1','2026-09-10','2026-09-10');assert.throws(()=>reopenV3RetrievalSource(db.db,index,'m1',currentMemory),/INDEX_STALE_ENTITIES/);const db2=fixture();db2.db.prepare("INSERT INTO work_items(id,account_id,conversation_id,customer_id,type,state,revision,goal_summary,source_message_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run('wi-current',A,C,'CUST-001','SALES_ORDER_REQUEST','DRAFTING',1,'current','m1','2026-09-10','2026-09-10');const memory2=memory(db2),index2=build(db2);db2.db.prepare('DELETE FROM work_items WHERE id=?').run('wi-current');assert.throws(()=>reopenV3RetrievalSource(db2.db,index2,'m1',memory2),/INDEX_STALE_ENTITIES/);});

test('unindexed canonical source linkage is excluded',()=>{const db=fixture();db.db.prepare("INSERT INTO work_items(id,account_id,conversation_id,customer_id,type,state,revision,goal_summary,source_message_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run('wi-unindexed',A,C,'CUST-001','SALES_ORDER_REQUEST','DRAFTING',1,'order','m4','2026-09-10','2026-09-10');const proposal:ConversationMemoryDerivationProposal={sections:[{id:'s-order',title:'Order',topic:'order',summary:'derived',sourceMessageIds:['m1','m2']}],rollingMemory:{text:'derived',sourceMessageIds:['m1','m2'],sectionIds:['s-order']}};const index=buildV3RetrievalIndexes(db.db,{accountId:A,conversationId:C,memory:buildV3ConversationMemory(db.db,{accountId:A,conversationId:C,proposal})});assert.deepEqual(index.entities,[]);});

test('RET-003 derives the host-authenticated tenant and canonical turn scope',()=>{const db=fixture(),index=build(db);assert.deepEqual(index.scope,{tenantId:'tenant-host-A',accountId:A,channelAccountId:A,conversationId:C,customerId:'CUST-001'});assert.equal(index.scopeVersion,'V3-RET-003:v1:'+canonicalSha256(index.scope));assert.deepEqual(index.scopeAudit,{contractVersion:'V3-RET-003',derivation:'HOST_AUTHENTICATED_PRINCIPAL_IMMUTABLE_AGENT_TURN_CANONICAL_DB',authoritative:false,deterministic:true});});
test('RET-003 authority binding is closed and issue accepts only turnId',()=>{const db=fixture(),principal={subject:'host-A',tenantId:'tenant-host-A',channelAccountId:A},authority=createV3RetrievalHostAuthority(db.db,principal);(principal as any).channelAccountId='foreign-account';const turnId=(db.db.prepare('SELECT id FROM agent_turns LIMIT 1').get() as {id:string}).id;assert.equal(authority.issue.length,1);const token=authority.issue(turnId);assert.ok(token);assert.throws(()=>createV3RetrievalHostAuthority(db.db,{...principal,extra:'forged'} as any),/^Error: V3_RETRIEVAL_SCOPE_UNAVAILABLE$/);const accessor=Object.create(Object.prototype);Object.defineProperty(accessor,'memory',{enumerable:true,get(){return memory(db)}});assert.throws(()=>trustedBuild(db.db,authority,token,accessor as any),/^Error: V3_RETRIEVAL_SCOPE_UNAVAILABLE$/);const requestedScope=Object.create(null);Object.defineProperty(requestedScope,'accountId',{enumerable:true,get(){return A}});assert.throws(()=>trustedBuild(db.db,authority,token,{memory:memory(db),requestedScope} as any),/^Error: V3_RETRIEVAL_SCOPE_UNAVAILABLE$/);});
test('RET-003 rejects cross-scope and tampered requested scope generically before any mode returns',()=>{const db=fixture(),base=memory(db),wrongScopes=[{accountId:'other-account',memory:base},{conversationId:'foreign-conversation',memory:base},{memory:base,requestedScope:{customerId:'OTHER-CUSTOMER'}},{memory:base,requestedScope:{channelAccountId:'other-channel'}},{memory:base,requestedScope:{tenantId:'tenant-foreign'}}];for(const input of wrongScopes)assert.throws(()=>rawBuild(db.db,host(db),input as any),/^Error: V3_RETRIEVAL_SCOPE_UNAVAILABLE$/);const index=build(db),tampered=structuredClone(index) as any;tampered.scope.customerId='OTHER-CUSTOMER';assert.throws(()=>reopenV3RetrievalSource(db.db,tampered,'m1',base),/^Error: V3_RETRIEVAL_SCOPE_UNAVAILABLE$/);const tamperedVersion=structuredClone(index) as any;tamperedVersion.scopeVersion='V3-RET-003:v1:forged';assert.throws(()=>reopenV3RetrievalSource(db.db,tamperedVersion,'m1',base),/^Error: V3_RETRIEVAL_SCOPE_UNAVAILABLE$/);});
test('RET-003 excludes same-account wrong-customer entities and keeps foreign reply references non-existent',()=>{const db=fixture();db.db.prepare("INSERT INTO work_items(id,account_id,conversation_id,customer_id,type,state,revision,goal_summary,source_message_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run('wi-wrong','demo-account','conv-001','OTHER-CUSTOMER','SALES_ORDER_REQUEST','DRAFTING',1,'foreign','m1','2026-09-10','2026-09-10');db.db.prepare('UPDATE messages SET reply_to_external_message_id=? WHERE id=?').run('foreign-external','m3');const index=build(db);assert.deepEqual(index.entities,[]);assert.equal(index.replies.find(x=>x.sourceMessageId==='m3')?.replyToSourceMessageId,null);assert.equal(index.replies.every(x=>x.childSourceMessageIds.every(id=>index.sourceMessageIds.includes(id))),true);});

test('RET-003 host A cannot use a real foreign account pair, requested scope, or a cloned authority',()=>{const db=fixture(),B='foreign-account',D='foreign-conversation',K='CUST-FOREIGN';
  db.db.prepare("INSERT INTO channel_accounts VALUES (?,?,?,?,?,?)").run(B,'simulated',B,'CONNECTED','2026-09-10','2026-09-10');db.db.prepare("INSERT INTO customers VALUES (?,?,?,?,?,?)").run(K,K,'Foreign Customer','SGD','OK','SG-MAIN');db.db.prepare("INSERT INTO conversations VALUES (?,?,?,?,?,?)").run(D,B,D,K,'OPEN','2026-09-10');db.db.prepare("INSERT INTO messages(id,conversation_id,external_message_id,direction,message_type,text,reply_to_external_message_id,account_id,occurred_at) VALUES(?,?,?,?,?,?,?,?,?)").run('fm1',D,'foreign-1','INBOUND','text','foreign order',null,B,'2026-09-10T00:00:00Z');
  const foreignMemory=buildV3ConversationMemory(db.db,{accountId:B,conversationId:D,proposal:{sections:[{id:'foreign-section',title:'Foreign',topic:'foreign',summary:'foreign',sourceMessageIds:['fm1']}],rollingMemory:{text:'foreign',sourceMessageIds:['fm1'],sectionIds:['foreign-section']}}});
  const foreignTurn=new AgentTurnCoordinator(db).start({accountId:B,conversationId:D,inboundMessageId:'fm1',timezone:'UTC',nowIso:'2026-09-10T00:00:00Z'});assert.ok(foreignTurn.turnId);
  const generic=/^Error: V3_RETRIEVAL_SCOPE_UNAVAILABLE$/,authorityA=host(db),authorityB=createV3RetrievalHostAuthority(db.db,{subject:'host-B',tenantId:'tenant-host-B',channelAccountId:B}),tokenB=authorityB.issue(foreignTurn.turnId);assert.throws(()=>rawBuild(db.db,authorityA,{memory:foreignMemory}),generic);assert.throws(()=>trustedBuild(db.db,authorityA,tokenB,{memory:foreignMemory}),generic);assert.throws(()=>rawBuild(db.db,authorityA,{memory:memory(db),requestedScope:{tenantId:'tenant-foreign',accountId:B,channelAccountId:B,conversationId:D,customerId:K}}),generic);assert.throws(()=>trustedBuild(db.db,authorityA,structuredClone(hosts.get(db.db)!.token),{memory:memory(db)}),generic);assert.throws(()=>rawBuild(db.db,{...authorityA},{memory:memory(db)}),generic);
});

test('RET-003 ignores forged verify methods and requires exact authority and token identity',()=>{const db=fixture(),currentMemory=memory(db),index=build(db),real=hosts.get(db.db)!;
  const forgedData={db:db.db,tenantId:'tenant-host-A',channelAccountId:A,turnId:'forged-turn'};
  const lookalike={verify:()=>forgedData};
  const variants=[lookalike,{...lookalike},structuredClone({verify:'forged'}),Object.create(Object.getPrototypeOf(real.authority))];
  for(const candidate of variants){assert.throws(()=>trustedBuild(db.db,candidate as any,real.token,{memory:currentMemory}),/^Error: V3_RETRIEVAL_SCOPE_UNAVAILABLE$/);assert.throws(()=>trustedReopen(db.db,candidate as any,real.token,index,'m1',currentMemory),/^Error: V3_RETRIEVAL_SCOPE_UNAVAILABLE$/)}
  const accessor=Object.create(Object.prototype);Object.defineProperty(accessor,'verify',{enumerable:true,get(){return ()=>forgedData}});
  assert.throws(()=>trustedBuild(db.db,accessor as any,real.token,{memory:currentMemory}),/^Error: V3_RETRIEVAL_SCOPE_UNAVAILABLE$/);
  assert.throws(()=>trustedBuild(db.db,real.authority,structuredClone(real.token),{memory:currentMemory}),/^Error: V3_RETRIEVAL_SCOPE_UNAVAILABLE$/);
  const foreign=fixture(),foreignAuthority=createV3RetrievalHostAuthority(foreign.db,{subject:'host-B',tenantId:'tenant-host-B',channelAccountId:A}),foreignTurn=(foreign.db.prepare('SELECT id FROM agent_turns LIMIT 1').get() as {id:string}).id;
  assert.throws(()=>trustedBuild(db.db,foreignAuthority,foreignAuthority.issue(foreignTurn),{memory:currentMemory}),/^Error: V3_RETRIEVAL_SCOPE_UNAVAILABLE$/);
});

test('RET-003 reopen fails closed when current canonical scope or turn lineage changes',()=>{for(const mutate of [
  (db:V1Database)=>{db.db.prepare("INSERT INTO customers VALUES (?,?,?,?,?,?)").run('CUST-REBOUND','CUST-REBOUND','Rebound','SGD','OK','SG-MAIN');db.db.prepare('UPDATE conversations SET customer_id=? WHERE id=?').run('CUST-REBOUND',C)},
  (db:V1Database)=>db.db.prepare('DELETE FROM customers WHERE id=?').run('CUST-001'),
  (db:V1Database)=>{db.db.prepare("INSERT INTO channel_accounts VALUES (?,?,?,?,?,?)").run('foreign-channel','simulated','foreign-channel','CONNECTED','2026-09-10','2026-09-10');db.db.prepare('UPDATE conversations SET channel_account_id=? WHERE id=?').run('foreign-channel',C)},
]){const db=fixture(),current=memory(db),index=build(db);mutate(db);assert.throws(()=>reopenV3RetrievalSource(db.db,index,'m1',current),/^Error: V3_RETRIEVAL_SCOPE_UNAVAILABLE$/);}
  const db=fixture(),foreign='foreign-account';db.db.prepare("INSERT INTO channel_accounts VALUES (?,?,?,?,?,?)").run(foreign,'simulated',foreign,'CONNECTED','2026-09-10','2026-09-10');db.db.prepare("INSERT INTO conversations VALUES (?,?,?,?,?,?)").run('foreign-conversation',foreign,'foreign-conversation',null,'OPEN','2026-09-10');db.db.prepare("INSERT INTO messages(id,conversation_id,external_message_id,direction,message_type,text,reply_to_external_message_id,account_id,occurred_at) VALUES(?,?,?,?,?,?,?,?,?)").run('foreign-inbound','foreign-conversation','foreign-inbound','INBOUND','text','foreign',null,foreign,'2026-09-10T00:00:00Z');const foreignTurn=new AgentTurnCoordinator(db).start({accountId:foreign,conversationId:'foreign-conversation',inboundMessageId:'foreign-inbound',timezone:'UTC',nowIso:'2026-09-10T00:00:00Z'});const hostA=createV3RetrievalHostAuthority(db.db,{subject:'host-A',tenantId:'tenant-host-A',channelAccountId:A});assert.throws(()=>hostA.issue(foreignTurn.turnId),/^Error: V3_RETRIEVAL_SCOPE_UNAVAILABLE$/);});
