import type {CommerceState} from './commerce.js';
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
/** Read-only canonical projection. No model, provider or mutation capability. */
export function renderConversationPrint(state:CommerceState,conversation:{id:string;customerId:string|null;[key:string]:unknown}){
 const money=(n:unknown)=>Number(n??0).toFixed(2),q=state.quote,so=state.so;
 const quote=q?`<h2>Quotation ${esc(q.no)} · ${esc(q.status)}</h2><p>Delivery ${esc(q.deliveryDate)} · Source message ${esc(q.sourceMessageId)}</p><table><thead><tr><th>SKU / Description</th><th>Quantity</th><th>Unit price</th><th>Subtotal</th></tr></thead><tbody>${q.lines.map((l:any)=>`<tr><td>${esc(l.stockCode)} · ${esc(l.description)}</td><td>${esc(l.quantity)} ${esc(l.uom)}</td><td>${money(l.unitPrice)}</td><td>${money(l.subtotal)}</td></tr>`).join('')}</tbody></table><p>Total ${esc(conversation.currency)} ${money(q.total)}</p>`:'<p>No quotation recorded.</p>';
 const order=so?`<h2>Sales Order ${esc(so.no)} · ${esc(so.status)}</h2><p>Source quotation ${esc(so.quoteNo)} · Total ${esc(conversation.currency)} ${money(so.total)}</p><p>Acceptance: ${esc(so.acceptanceEvidence?.text??'No acceptance evidence recorded.')}</p><p>Accepted at ${esc(so.acceptanceEvidence?.acceptedAt??'—')} · External message ${esc(so.acceptanceEvidence?.externalMessageId??'—')}</p>`:'<p>No Sales Order recorded.</p>';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>WhatsApp ERP · ${esc(q?.no??conversation.id)}</title><style>body{font:14px system-ui,sans-serif;color:#183530;max-width:900px;margin:36px auto;padding:20px}h1{font-size:25px}h2{font-size:19px;margin-top:30px}table{border-collapse:collapse;width:100%}th,td{border-bottom:1px solid #ccd8d3;padding:10px;text-align:left}.boundary{padding:12px;border:1px solid #ccd8d3}@media print{body{margin:0;max-width:none;padding:0}h2{break-after:avoid}tr{break-inside:avoid}}</style></head><body><h1>WhatsApp ERP · Order review</h1><p>${esc(state.customer)} · Customer ${esc(conversation.customerId??'UNLINKED')} · Conversation ${esc(conversation.id)}</p><p class="boundary">Read-only canonical record. AI authority ends at SALES_ORDER.DRAFT. Staff post/confirm/DO require separate authorized actions. Use the browser Print command; opening this page sends no messages and changes no order.</p>${quote}${order}<h2>Audit timeline</h2><pre>${esc(JSON.stringify(state.timeline,null,2))}</pre><h2>Staff actions</h2><pre>${esc(JSON.stringify(state.staffActions??[],null,2))}</pre></body></html>`;
}
