import {createHash, randomUUID} from 'node:crypto';
import {V1Database} from './database.js';
import {AgentContextBuilder,MAX_AGENT_CONTEXT_CHARS,type AgentContextInput} from './v2-agent-context.js';
import {authorizeCapability,type HostAuthorizationContext} from './v2-capability-authorization.js';
import {getCapability} from './v2-capability-registry.js';
import {normalizeCapabilityResult} from './v2-capability-result.js';
import {EmployeeProfileResolver,PILOT_BUDGET_CEILINGS,type EmployeeTurnBudgets} from './v2-employee-profile.js';
import {redactContextText} from './v2-context-projection.js';
import {validateGroundedResponsePlan, type GroundedResponsePlan} from './v2-grounded-response-plan.js';

export type TurnResumeState='AWAITING_DECISION'|'RECONCILE_ACTION'|'TERMINAL';
export type AgentTurnStart=Omit<AgentContextInput,'turnId'>;
export type ProposedAgentAction={turnId:string;sequence:number;actionId?:string;capabilityName?:string;capabilityVersion?:string;capability?:{name:string;version:string};arguments:unknown;idempotencyKey?:string};
export type AgentActionProjection=Readonly<{id:string;sequence:number;capability:Readonly<{name:string;version:string}>;arguments:unknown;result:unknown|null}>;
export type AgentTurnProjection=Readonly<{turnId:string;status:TurnResumeState;context:unknown;actions:readonly AgentActionProjection[]}>;
export type TurnOutboundDisposition='RUNTIME_RESPONSE'|'CAPABILITY_OWNED_QUOTATION'|'HANDOFF_NO_CUSTOMER_MESSAGE'|'NONE';

const MAX_ARGUMENT_JSON_CHARS=16_384,MAX_RESULT_JSON_CHARS=32_768,MAX_CONTEXT_PROVENANCE_CHARS=8_192;
const mutationState=new WeakMap<object,{depth:number}>();

function fail(code:string):never{throw new Error(`AGENT_TURN_INVALID:${code}`)}
function text(v:unknown,code:string,max=256):string{if(typeof v!=='string'||v.trim()===''||v.length>max)fail(code);return v}
function positive(v:unknown,code:string):number{if(!Number.isSafeInteger(v)||Number(v)<=0)fail(code);return Number(v)}
function freeze<T>(v:T):T{if(v&&typeof v==='object'){for(const c of Object.values(v as Record<string,unknown>))freeze(c);if(!Object.isFrozen(v))Object.freeze(v)}return v}
function stableValue(v:unknown):unknown{if(Array.isArray(v))return v.map(stableValue);if(v&&typeof v==='object'){const out:Record<string,unknown>={};for(const key of Object.keys(v as Record<string,unknown>).sort())out[key]=stableValue((v as Record<string,unknown>)[key]);return out}return v}
function stableJson(v:unknown):string{return JSON.stringify(stableValue(v))}
function hashString(v:string):string{return createHash('sha256').update(v).digest('hex')}
function persistedJson(v:unknown,code:string,max:number):{json:string;hash:string}{const json=stableJson(v);if(json.length>max)fail(`${code}_SIZE`);if(redactContextText(json)!==json)fail(`${code}_SECRET`);return{json,hash:hashString(json)}}
function dbRow(db:V1Database['db'],sql:string,...args:unknown[]):any{return db.prepare(sql).get(...args)}
function installMutationGuard(db:V1Database['db']){let state=mutationState.get(db as object);if(!state){state={depth:0};mutationState.set(db as object,state)}db.function('v2_agent_turn_mutation_authorized',()=>state!.depth>0?1:0)}
const BUDGET_KEYS=['maxModelTurns','maxCapabilityCalls','perCallTimeoutMs','turnTimeoutMs','maxRepairAttempts'] as const;
function nonnegative(v:unknown,code:string):number{if(!Number.isSafeInteger(v)||Number(v)<0)fail(code);return Number(v)}
function parseBudgets(raw:unknown):EmployeeTurnBudgets{if(typeof raw!=='string'||raw.length>2048)fail('BUDGET_PROVENANCE');let v:any;try{v=JSON.parse(raw)}catch{fail('BUDGET_PROVENANCE')}if(!v||typeof v!=='object'||Array.isArray(v)||Object.getPrototypeOf(v)!==Object.prototype)fail('BUDGET_PROVENANCE');const keys=Object.keys(v).sort(),expected=[...BUDGET_KEYS].sort();if(keys.length!==expected.length||keys.some((k,i)=>k!==expected[i]))fail('BUDGET_PROVENANCE_FIELDS');const budgets={maxModelTurns:positive(v.maxModelTurns,'MAX_MODEL_TURNS'),maxCapabilityCalls:positive(v.maxCapabilityCalls,'MAX_CAPABILITY_CALLS'),perCallTimeoutMs:positive(v.perCallTimeoutMs,'PER_CALL_TIMEOUT'),turnTimeoutMs:positive(v.turnTimeoutMs,'TURN_TIMEOUT'),maxRepairAttempts:nonnegative(v.maxRepairAttempts,'MAX_REPAIR_ATTEMPTS')};if(budgets.perCallTimeoutMs>budgets.turnTimeoutMs)fail('CALL_TIMEOUT_EXCEEDS_TURN');for(const k of BUDGET_KEYS)if(budgets[k]>PILOT_BUDGET_CEILINGS[k])fail('BUDGET_EXCEEDS_PILOT_CAP');return freeze(budgets)}

export class AgentTurnCoordinator{
 private readonly db:V1Database['db'];
 private readonly contexts:AgentContextBuilder;
 private readonly profiles:EmployeeProfileResolver;
 constructor(private readonly database:V1Database){this.db=database.db;installMutationGuard(this.db);this.contexts=new AgentContextBuilder(this.db);this.profiles=new EmployeeProfileResolver(this.db)}
 #mutate<T>(operation:()=>T):T{const state=mutationState.get(this.db as object);if(!state)fail('MUTATION_GUARD');state.depth+=1;try{return this.db.transaction(operation)()}finally{state.depth-=1}}
 private identity(input:AgentTurnStart){const accountId=text(input.accountId,'ACCOUNT_ID'),conversationId=text(input.conversationId,'CONVERSATION_ID'),inboundMessageId=text(input.inboundMessageId,'INBOUND_MESSAGE_ID'),timezone=text(input.timezone,'TIMEZONE',120);const profile=input.profileId===undefined?this.profiles.resolve():this.profiles.resolve(input.profileId);if(!dbRow(this.db,"SELECT 1 FROM messages WHERE id=? AND account_id=? AND conversation_id=? AND direction='INBOUND'",inboundMessageId,accountId,conversationId))fail('INBOUND_SCOPE');return{accountId,conversationId,inboundMessageId,timezone,profile}}
 private exactContext(turn:any):unknown{if(typeof turn.context_snapshot_json!=='string'||turn.context_snapshot_json.length>MAX_AGENT_CONTEXT_CHARS)fail('STORED_CONTEXT_SIZE');let context:unknown;try{context=JSON.parse(turn.context_snapshot_json)}catch{fail('STORED_CONTEXT_JSON')}const canonical=stableJson(context);if(canonical!==turn.context_snapshot_json||hashString(canonical)!==turn.context_fingerprint||redactContextText(canonical)!==canonical)fail('STORED_CONTEXT_INTEGRITY');return context}
 private disposition(turnId:string,disposition:TurnOutboundDisposition,purpose:string,payloadHash:string,createdAt:string){
  const prior=dbRow(this.db,'SELECT disposition,purpose,payload_hash FROM turn_outbound_dispositions WHERE turn_id=?',turnId);
  if(prior){if(prior.disposition!==disposition||prior.purpose!==purpose||prior.payload_hash!==payloadHash)fail('OUTBOUND_DISPOSITION_REPLAY_CONFLICT');return;}
  this.database.runOutboundMutation(()=>this.db.prepare('INSERT INTO turn_outbound_dispositions(turn_id,disposition,purpose,outbound_message_id,payload_hash,created_at) VALUES(?,?,?,?,?,?)').run(turnId,disposition,purpose,null,payloadHash,createdAt));
 }

 start(input:AgentTurnStart):AgentTurnProjection{
  const {accountId,conversationId,inboundMessageId,timezone,profile}=this.identity(input);
  const existing=dbRow(this.db,'SELECT * FROM agent_turns WHERE account_id=? AND conversation_id=? AND inbound_message_id=?',accountId,conversationId,inboundMessageId);
  if(existing){if(existing.profile_id!==profile.id||existing.profile_version!==profile.version||existing.timezone!==timezone)fail('REPLAY_IDENTITY_CONFLICT');return this.project(existing.id,this.exactContext(existing))}
  const turnId=randomUUID(),context=this.contexts.build({...input,turnId,profileId:profile.id});
  const snapshot=persistedJson(context,'CONTEXT_SNAPSHOT',MAX_AGENT_CONTEXT_CHARS);
  const provenance=persistedJson({inboundMessageId,profileId:profile.id,profileVersion:profile.version,freshness:(context as any).freshness},'CONTEXT_PROVENANCE',MAX_CONTEXT_PROVENANCE_CHARS);
  const startedAt=new Date().toISOString(), deadlineAt=new Date(Date.now()+profile.turnBudgets.turnTimeoutMs).toISOString();
  const budget=persistedJson(profile.turnBudgets,'BUDGET_PROVENANCE',2048);
  try{this.#mutate(()=>this.db.prepare('INSERT INTO agent_turns(id,account_id,conversation_id,inbound_message_id,profile_id,profile_version,timezone,status,context_fingerprint,context_snapshot_json,context_provenance_json,budget_provenance_json,runtime_started_at,runtime_deadline_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(turnId,accountId,conversationId,inboundMessageId,profile.id,profile.version,timezone,'AWAITING_DECISION',snapshot.hash,snapshot.json,provenance.json,budget.json,startedAt,deadlineAt,startedAt,startedAt))}catch(error){if(!String(error).includes('UNIQUE'))throw error;const raced=dbRow(this.db,'SELECT * FROM agent_turns WHERE account_id=? AND conversation_id=? AND inbound_message_id=?',accountId,conversationId,inboundMessageId);if(!raced||raced.profile_id!==profile.id||raced.profile_version!==profile.version||raced.timezone!==timezone)fail('REPLAY_IDENTITY_CONFLICT');return this.project(raced.id,this.exactContext(raced))}
  return this.project(turnId,context)
 }
 resume(input:AgentTurnStart):AgentTurnProjection{const {accountId,conversationId,inboundMessageId,timezone,profile}=this.identity(input);const turn=dbRow(this.db,'SELECT * FROM agent_turns WHERE account_id=? AND conversation_id=? AND inbound_message_id=?',accountId,conversationId,inboundMessageId);if(!turn)fail('TURN_NOT_FOUND');if(turn.profile_id!==profile.id||turn.profile_version!==profile.version||turn.timezone!==timezone)fail('REPLAY_IDENTITY_CONFLICT');return this.project(turn.id,this.exactContext(turn))}
  startOrResume(input:AgentTurnStart):AgentTurnProjection{const found=dbRow(this.db,'SELECT 1 FROM agent_turns WHERE account_id=? AND conversation_id=? AND inbound_message_id=?',input.accountId,input.conversationId,input.inboundMessageId);return found?this.resume(input):this.start(input)}

  read(turnId:string):AgentTurnProjection{return this.projectFromCurrent(text(turnId,'TURN_ID'))}
  terminalReason(turnId:string):string|null{const row=dbRow(this.db,'SELECT terminal_reason FROM agent_turns WHERE id=?',text(turnId,'TURN_ID'));if(!row)fail('TURN_NOT_FOUND');return row.terminal_reason??null}
  finalResponsePlan(turnId:string):GroundedResponsePlan|null{const id=text(turnId,'TURN_ID'),row=dbRow(this.db,'SELECT plan_json,plan_hash FROM agent_response_plans WHERE turn_id=?',id);if(!row)return null;if(typeof row.plan_json!=='string'||hashString(row.plan_json)!==row.plan_hash)fail('RESPONSE_PLAN_INTEGRITY');let value:unknown;try{value=JSON.parse(row.plan_json)}catch{fail('RESPONSE_PLAN_JSON')}return validateGroundedResponsePlan(value,id)}
  budget(turnId:string){const turn=dbRow(this.db,'SELECT budget_provenance_json,runtime_started_at,runtime_deadline_at FROM agent_turns WHERE id=?',text(turnId,'TURN_ID'));if(!turn)fail('TURN_NOT_FOUND');const budgets=parseBudgets(turn.budget_provenance_json),startedAt=text(turn.runtime_started_at,'RUNTIME_STARTED_AT',64),deadlineAt=text(turn.runtime_deadline_at,'RUNTIME_DEADLINE_AT',64);if(!Number.isFinite(Date.parse(startedAt))||!Number.isFinite(Date.parse(deadlineAt))||Date.parse(deadlineAt)<Date.parse(startedAt))fail('RUNTIME_DEADLINE');return freeze({budgets,startedAt,deadlineAt})}
  usage(turnId:string){const id=text(turnId,'TURN_ID');if(!dbRow(this.db,'SELECT 1 FROM agent_turns WHERE id=?',id))fail('TURN_NOT_FOUND');return freeze({modelAttempts:Number(dbRow(this.db,'SELECT count(*) n FROM agent_model_attempts WHERE turn_id=?',id)?.n??0),repairAttempts:Number(dbRow(this.db,"SELECT count(*) n FROM agent_model_attempts WHERE turn_id=? AND attempt_kind='REPAIR'",id)?.n??0),capabilityCalls:Number(dbRow(this.db,'SELECT count(*) n FROM agent_actions WHERE turn_id=?',id)?.n??0),resolvedActions:Number(dbRow(this.db,'SELECT count(*) n FROM agent_action_results WHERE turn_id=?',id)?.n??0),uncertainActions:Number(dbRow(this.db,'SELECT count(*) n FROM agent_action_execution_events WHERE turn_id=?',id)?.n??0)})}
  repairEvidence(turnId:string){const id=text(turnId,'TURN_ID');if(!dbRow(this.db,'SELECT 1 FROM agent_turns WHERE id=?',id))fail('TURN_NOT_FOUND');return dbRow(this.db,'SELECT decision_sequence,event_sequence,observation_hash,projection_hash,phase FROM agent_repair_evidence WHERE turn_id=? ORDER BY event_sequence DESC LIMIT 1',id) as {decision_sequence:number;event_sequence:number;observation_hash:string;projection_hash:string;phase:'PENDING'|'RESERVED'|'VALID'|'FAILED'|'COMMITTED'}|undefined}
  modelAttemptRecovery(turnId:string){const id=text(turnId,'TURN_ID');const attempt=dbRow(this.db,'SELECT sequence,attempt_kind,observation_hash,projection_hash FROM agent_model_attempts WHERE turn_id=? ORDER BY sequence DESC LIMIT 1',id);if(!attempt||attempt.attempt_kind!=='MODEL')return null;const repair=dbRow(this.db,"SELECT decision_sequence,observation_hash,projection_hash,phase FROM agent_repair_evidence WHERE turn_id=? ORDER BY event_sequence DESC LIMIT 1",id);const legacyScope=!attempt.observation_hash&&!attempt.projection_hash;if(repair?.decision_sequence===attempt.sequence&&repair.phase==='PENDING'&&(legacyScope||(repair.observation_hash===attempt.observation_hash&&repair.projection_hash===attempt.projection_hash)))return 'REPAIR_PENDING';const repairsBefore=Number(dbRow(this.db,"SELECT count(*) n FROM agent_model_attempts WHERE turn_id=? AND attempt_kind='REPAIR' AND sequence<?",id,attempt.sequence)?.n??0),decisionSequence=attempt.sequence-repairsBefore;if(decisionSequence>0&&dbRow(this.db,'SELECT 1 FROM agent_actions WHERE turn_id=? AND sequence=?',id,decisionSequence)||dbRow(this.db,'SELECT 1 FROM agent_response_plans WHERE turn_id=?',id))return 'REFLECTED';return 'UNCERTAIN'}
  recordModelValid(input:{turnId:string;sequence:number;observationHash:string;projectionHash:string}){const id=text(input.turnId,'TURN_ID'),sequence=positive(input.sequence,'MODEL_SEQUENCE');return this.#mutate(()=>{const attempt=dbRow(this.db,"SELECT attempt_kind,observation_hash,projection_hash FROM agent_model_attempts WHERE turn_id=? AND sequence=?",id,sequence);if(!attempt||attempt.attempt_kind!=='MODEL'||attempt.observation_hash!==input.observationHash||attempt.projection_hash!==input.projectionHash)fail('MODEL_ATTEMPT_SCOPE');this.db.prepare("INSERT OR IGNORE INTO agent_model_attempt_evidence(id,turn_id,sequence,attempt_kind,observation_hash,projection_hash,phase,created_at) VALUES(?,?,?,?,?,?,?,?)").run(randomUUID(),id,sequence,'MODEL',input.observationHash,input.projectionHash,'VALID',new Date().toISOString());return true})}
  private repairEvent(id:string, decisionSequence:number, observationHash:string, projectionHash:string, phase:'PENDING'|'RESERVED'|'VALID'|'FAILED'|'COMMITTED'){
    const latest=this.repairEvidence(id);if(latest&& (latest.decision_sequence!==decisionSequence||latest.observation_hash!==observationHash||latest.projection_hash!==projectionHash)) fail('REPAIR_SCOPE_MISMATCH');
    if(latest?.phase===phase)return;
    if(latest && !((latest.phase==='PENDING'&&phase==='RESERVED')||(latest.phase==='RESERVED'&&phase==='VALID')||(latest.phase==='VALID'&&phase==='COMMITTED')||((latest.phase==='PENDING'||latest.phase==='RESERVED')&&phase==='FAILED'))) fail('REPAIR_PHASE');
    const next=(latest?.event_sequence??0)+1;this.db.prepare('INSERT INTO agent_repair_evidence(id,turn_id,decision_sequence,event_sequence,observation_hash,projection_hash,phase,created_at) VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),id,decisionSequence,next,observationHash,projectionHash,phase,new Date().toISOString());
  }
  recordRepairPending(input:{turnId:string;decisionSequence:number;observationHash:string;projectionHash:string}){const id=text(input.turnId,'TURN_ID');const ds=positive(input.decisionSequence,'REPAIR_SEQUENCE');if(!input.observationHash||!input.projectionHash)fail('REPAIR_FINGERPRINT');return this.#mutate(()=>{const turn=dbRow(this.db,'SELECT status FROM agent_turns WHERE id=?',id);if(!turn)fail('REPAIR_STATE');const model=dbRow(this.db,"SELECT observation_hash,projection_hash FROM agent_model_attempts WHERE turn_id=? AND sequence=? AND attempt_kind='MODEL'",id,ds);if(!model)fail('REPAIR_MODEL_MISSING');if((model.observation_hash&&model.observation_hash!==input.observationHash)||(model.projection_hash&&model.projection_hash!==input.projectionHash))fail('REPAIR_SCOPE_MISMATCH');if(turn.status!=='AWAITING_DECISION')fail('REPAIR_STATE');this.repairEvent(id,ds,input.observationHash,input.projectionHash,'PENDING');this.db.prepare("INSERT OR IGNORE INTO agent_model_attempt_evidence(id,turn_id,sequence,attempt_kind,observation_hash,projection_hash,phase,created_at) VALUES(?,?,?,?,?,?,?,?)").run(randomUUID(),id,ds,'MODEL',input.observationHash,input.projectionHash,'REPAIR_PENDING',new Date().toISOString());return this.repairEvidence(id)!})}
  reserveRepairAttempt(input:{turnId:string;decisionSequence:number;observationHash:string;projectionHash:string;reasonCode:string}){const id=text(input.turnId,'TURN_ID'),reason=text(input.reasonCode,'ATTEMPT_REASON',120),ds=positive(input.decisionSequence,'REPAIR_SEQUENCE');return this.#mutate(()=>{const turn=dbRow(this.db,'SELECT status FROM agent_turns WHERE id=?',id);if(!turn)fail('REPAIR_STATE');if(turn.status!=='AWAITING_DECISION')fail('REPAIR_STATE');const latest=this.repairEvidence(id);if(!latest||latest.decision_sequence!==ds||latest.observation_hash!==input.observationHash||latest.projection_hash!==input.projectionHash||latest.phase!=='PENDING')fail('REPAIR_SCOPE_MISMATCH');const {budgets}=this.budget(id),usage=this.usage(id);if(usage.modelAttempts>=budgets.maxModelTurns)fail('PI_MAX_MODEL_TURNS');if(usage.repairAttempts>=budgets.maxRepairAttempts)fail('PI_MAX_REPAIR_ATTEMPTS');const sequence=usage.modelAttempts+1;this.db.prepare('INSERT INTO agent_model_attempts(id,turn_id,sequence,attempt_kind,reason_code,observation_hash,projection_hash,created_at) VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),id,sequence,'REPAIR',reason,input.observationHash,input.projectionHash,new Date().toISOString());this.repairEvent(id,ds,input.observationHash,input.projectionHash,'RESERVED');return sequence})}
  recordRepairValid(input:{turnId:string;decisionSequence:number;observationHash:string;projectionHash:string}){const id=text(input.turnId,'TURN_ID');return this.#mutate(()=>{const latest=this.repairEvidence(id);if(!latest||latest.phase!=='RESERVED')fail('REPAIR_PHASE');this.repairEvent(id,positive(input.decisionSequence,'REPAIR_SEQUENCE'),input.observationHash,input.projectionHash,'VALID');return this.repairEvidence(id)!})}
  recordRepairCommitted(input:{turnId:string;decisionSequence:number;observationHash:string;projectionHash:string}){const id=text(input.turnId,'TURN_ID');return this.#mutate(()=>{const latest=this.repairEvidence(id);if(!latest||latest.phase!=='VALID')fail('REPAIR_PHASE');this.repairEvent(id,positive(input.decisionSequence,'REPAIR_SEQUENCE'),input.observationHash,input.projectionHash,'COMMITTED');return this.repairEvidence(id)!})}
  failRepair(input:{turnId:string;decisionSequence:number;observationHash:string;projectionHash:string}){const id=text(input.turnId,'TURN_ID');return this.#mutate(()=>{const latest=this.repairEvidence(id);if(!latest||!['PENDING','RESERVED'].includes(latest.phase))fail('REPAIR_PHASE');this.repairEvent(id,positive(input.decisionSequence,'REPAIR_SEQUENCE'),input.observationHash,input.projectionHash,'FAILED');return this.repairEvidence(id)!})}
  reserveModelAttempt(input:{turnId:string;kind:'MODEL'|'REPAIR';reasonCode:string;observationHash?:string;projectionHash?:string}){const id=text(input.turnId,'TURN_ID'),reason=text(input.reasonCode,'ATTEMPT_REASON',120),observationHash=input.observationHash??'',projectionHash=input.projectionHash??'';return this.#mutate(()=>{const turn=dbRow(this.db,'SELECT status FROM agent_turns WHERE id=?',id);if(!turn)fail('TURN_NOT_FOUND');if(turn.status!=='AWAITING_DECISION')fail('MODEL_ATTEMPT_STATE');const {budgets}=this.budget(id),usage=this.usage(id);if(usage.modelAttempts>=budgets.maxModelTurns)fail('PI_MAX_MODEL_TURNS');if(input.kind==='REPAIR'&&usage.repairAttempts>=budgets.maxRepairAttempts)fail('PI_MAX_REPAIR_ATTEMPTS');const sequence=usage.modelAttempts+1;this.db.prepare('INSERT INTO agent_model_attempts(id,turn_id,sequence,attempt_kind,reason_code,observation_hash,projection_hash,created_at) VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),id,sequence,input.kind,reason,observationHash,projectionHash,new Date().toISOString());return sequence})}
  recordExecutionInterruption(input:{turnId:string;actionId:string;sequence:number;outcome:'TIMEOUT'|'CANCELLED';reasonCode:string}){const turnId=text(input.turnId,'TURN_ID'),actionId=text(input.actionId,'ACTION_ID'),sequence=positive(input.sequence,'SEQUENCE'),reason=text(input.reasonCode,'EXECUTION_REASON',120);return this.#mutate(()=>{const turn=dbRow(this.db,'SELECT status FROM agent_turns WHERE id=?',turnId);if(!turn)fail('TURN_NOT_FOUND');if(!dbRow(this.db,'SELECT 1 FROM agent_actions WHERE id=? AND turn_id=? AND sequence=?',actionId,turnId,sequence))fail('ACTION_NOT_FOUND');if(dbRow(this.db,'SELECT 1 FROM agent_action_results WHERE action_id=?',actionId))fail('ACTION_ALREADY_RESOLVED');const prior=dbRow(this.db,'SELECT outcome,reason_code FROM agent_action_execution_events WHERE action_id=?',actionId);if(prior){if(prior.outcome===input.outcome&&prior.reason_code===reason)return this.projectFromCurrent(turnId);fail('EXECUTION_EVENT_REPLAY_CONFLICT')}if(turn.status!=='RECONCILE_ACTION')fail('TURN_LEDGER_INCONSISTENT');this.db.prepare('INSERT INTO agent_action_execution_events(id,turn_id,action_id,sequence,outcome,reason_code,created_at) VALUES(?,?,?,?,?,?,?)').run(randomUUID(),turnId,actionId,sequence,input.outcome,reason,new Date().toISOString());return this.projectFromCurrent(turnId)})}
  exhaust(input:{turnId:string;reason:string}){const turn=dbRow(this.db,'SELECT * FROM agent_turns WHERE id=?',text(input.turnId,'TURN_ID'));if(!turn)fail('TURN_NOT_FOUND');const reason=text(input.reason,'TERMINAL_REASON',256);if(redactContextText(reason)!==reason)fail('TERMINAL_REASON_SECRET');if(turn.status==='TERMINAL'){if(turn.terminal_reason===reason)return this.projectFromCurrent(turn.id);fail('TERMINAL_REPLAY_CONFLICT')}if(dbRow(this.db,'SELECT 1 FROM agent_actions a LEFT JOIN agent_action_results r ON r.action_id=a.id WHERE a.turn_id=? AND r.id IS NULL LIMIT 1',turn.id))fail('UNRESOLVED_ACTION');const now=new Date().toISOString();this.#mutate(()=>{this.disposition(turn.id,'NONE','none',hashString(stableJson({reason})),now);this.db.prepare("UPDATE agent_turns SET status='TERMINAL',terminal_reason=?,completed_at=?,updated_at=? WHERE id=?").run(reason,now,now,turn.id)});return this.projectFromCurrent(turn.id)}

 propose(input:ProposedAgentAction):AgentTurnProjection{
  const turn=dbRow(this.db,'SELECT * FROM agent_turns WHERE id=?',text(input.turnId,'TURN_ID'));if(!turn)fail('TURN_NOT_FOUND');if(turn.status==='TERMINAL')fail('TERMINAL_MUTATION');
  const sequence=positive(input.sequence,'SEQUENCE'),name=text(input.capabilityName??input.capability?.name,'CAPABILITY_NAME'),version=text(input.capabilityVersion??input.capability?.version,'CAPABILITY_VERSION'),def=getCapability(name);if(!def||def.version!==version)fail('CAPABILITY_VERSION');
  const profile=this.profiles.resolve(turn.profile_id);if(profile.version!==turn.profile_version)fail('PROFILE_VERSION_CHANGED');if(!profile.permissions.includes(def.permission.identifier))fail('PERMISSION_DENIED');
  const envelope=authorizeCapability({name,arguments:input.arguments},{db:this.db,profileId:profile.id,permissions:profile.permissions,accountId:turn.account_id,conversationId:turn.conversation_id,customerId:dbRow(this.db,'SELECT customer_id FROM conversations WHERE id=? AND channel_account_id=?',turn.conversation_id,turn.account_id)?.customer_id,idempotencyKey:input.idempotencyKey} satisfies HostAuthorizationContext);
  const args=persistedJson(envelope.arguments,'ARGUMENTS',MAX_ARGUMENT_JSON_CHARS),suppliedActionId=input.actionId===undefined?undefined:text(input.actionId,'ACTION_ID');
  const prior=dbRow(this.db,'SELECT * FROM agent_actions WHERE turn_id=? AND sequence=?',turn.id,sequence)??(suppliedActionId?dbRow(this.db,'SELECT * FROM agent_actions WHERE id=?',suppliedActionId):undefined);
  if(prior){if(prior.turn_id!==turn.id||prior.sequence!==sequence||(suppliedActionId&&prior.id!==suppliedActionId)||prior.capability_name!==name||prior.capability_version!==version||prior.arguments_hash!==args.hash)fail('ACTION_REPLAY_CONFLICT');return this.projectFromCurrent(turn.id)}
  if(turn.status!=='AWAITING_DECISION'||dbRow(this.db,'SELECT 1 FROM agent_actions a LEFT JOIN agent_action_results r ON r.action_id=a.id WHERE a.turn_id=? AND r.id IS NULL LIMIT 1',turn.id))fail('PENDING_ACTION_EXISTS');
  const completedDuplicate=dbRow(this.db,'SELECT a.id FROM agent_actions a JOIN agent_action_results r ON r.action_id=a.id WHERE a.turn_id=? AND a.capability_name=? AND a.capability_version=? AND a.arguments_hash=? LIMIT 1',turn.id,name,version,args.hash);if(completedDuplicate)fail('COMPLETED_ACTION_REPEAT');
  const max=(dbRow(this.db,'SELECT COALESCE(MAX(sequence),0) n FROM agent_actions WHERE turn_id=?',turn.id)?.n??0) as number;const {budgets}=this.budget(turn.id);if(max>=budgets.maxCapabilityCalls)fail('PI_MAX_CAPABILITY_CALLS');if(sequence!==max+1)fail('ACTION_SEQUENCE');
  const actionId=suppliedActionId??randomUUID(),now=new Date().toISOString();this.#mutate(()=>{this.db.prepare('INSERT INTO agent_actions(id,turn_id,sequence,capability_name,capability_version,arguments_json,arguments_hash,created_at) VALUES(?,?,?,?,?,?,?,?)').run(actionId,turn.id,sequence,name,version,args.json,args.hash,now);this.db.prepare("UPDATE agent_turns SET status='RECONCILE_ACTION',updated_at=? WHERE id=?").run(now,turn.id)});return this.projectFromCurrent(turn.id)
 }
 proposeAction(input:ProposedAgentAction):AgentTurnProjection{return this.propose(input)}

 recordResult(input:{turnId:string;actionId:string;sequence:number;result:unknown}):AgentTurnProjection{
  const turn=dbRow(this.db,'SELECT * FROM agent_turns WHERE id=?',text(input.turnId,'TURN_ID'));if(!turn)fail('TURN_NOT_FOUND');const action=dbRow(this.db,'SELECT * FROM agent_actions WHERE id=? AND turn_id=? AND sequence=?',text(input.actionId,'ACTION_ID'),turn.id,positive(input.sequence,'SEQUENCE'));if(!action)fail('ACTION_NOT_FOUND');
  const result=normalizeCapabilityResult(input.result),payload=persistedJson(result,'RESULT',MAX_RESULT_JSON_CHARS),prior=dbRow(this.db,'SELECT * FROM agent_action_results WHERE action_id=?',action.id);
  if(prior){if(prior.turn_id!==turn.id||prior.sequence!==action.sequence||prior.result_hash!==payload.hash)fail('RESULT_REPLAY_CONFLICT');return this.projectFromCurrent(turn.id)}if(dbRow(this.db,'SELECT 1 FROM agent_action_execution_events WHERE action_id=?',action.id))fail('ACTION_EXECUTION_UNCERTAIN');if(turn.status==='TERMINAL')fail('TERMINAL_MUTATION');if(turn.status!=='RECONCILE_ACTION')fail('TURN_LEDGER_INCONSISTENT');
  const now=new Date().toISOString();this.#mutate(()=>{this.db.prepare('INSERT INTO agent_action_results(id,turn_id,action_id,sequence,result_json,result_hash,created_at) VALUES(?,?,?,?,?,?,?)').run(randomUUID(),turn.id,action.id,action.sequence,payload.json,payload.hash,now);this.db.prepare("UPDATE agent_turns SET status='AWAITING_DECISION',updated_at=? WHERE id=?").run(now,turn.id)});return this.projectFromCurrent(turn.id)
 }

 recordResultAndComplete(input:{turnId:string;actionId:string;sequence:number;result:unknown;reason:string}):AgentTurnProjection{
  const turn=dbRow(this.db,'SELECT * FROM agent_turns WHERE id=?',text(input.turnId,'TURN_ID'));if(!turn)fail('TURN_NOT_FOUND');
  const action=dbRow(this.db,'SELECT * FROM agent_actions WHERE id=? AND turn_id=? AND sequence=?',text(input.actionId,'ACTION_ID'),turn.id,positive(input.sequence,'SEQUENCE'));if(!action)fail('ACTION_NOT_FOUND');
  const result=normalizeCapabilityResult(input.result),payload=persistedJson(result,'RESULT',MAX_RESULT_JSON_CHARS),reason=text(input.reason,'TERMINAL_REASON',256);if(redactContextText(reason)!==reason)fail('TERMINAL_REASON_SECRET');
  const prior=dbRow(this.db,'SELECT * FROM agent_action_results WHERE action_id=?',action.id);
  if(prior){if(prior.turn_id!==turn.id||prior.sequence!==action.sequence||prior.result_hash!==payload.hash)fail('RESULT_REPLAY_CONFLICT');if(turn.status==='TERMINAL'&&turn.terminal_reason===reason)return this.projectFromCurrent(turn.id);fail('TERMINAL_REPLAY_CONFLICT');}
  if(dbRow(this.db,'SELECT 1 FROM agent_action_execution_events WHERE action_id=?',action.id))fail('ACTION_EXECUTION_UNCERTAIN');if(turn.status==='TERMINAL')fail('TERMINAL_MUTATION');if(turn.status!=='RECONCILE_ACTION')fail('TURN_LEDGER_INCONSISTENT');
  const now=new Date().toISOString();this.#mutate(()=>{this.db.prepare('INSERT INTO agent_action_results(id,turn_id,action_id,sequence,result_json,result_hash,created_at) VALUES(?,?,?,?,?,?,?)').run(randomUUID(),turn.id,action.id,action.sequence,payload.json,payload.hash,now);this.disposition(turn.id,reason==='PI_CAPABILITY_OWNED_QUOTATION'?'CAPABILITY_OWNED_QUOTATION':'HANDOFF_NO_CUSTOMER_MESSAGE',reason==='PI_CAPABILITY_OWNED_QUOTATION'?'quotation':'handoff',payload.hash,now);this.db.prepare("UPDATE agent_turns SET status='TERMINAL',terminal_reason=?,completed_at=?,updated_at=? WHERE id=?").run(reason,now,now,turn.id)});return this.projectFromCurrent(turn.id);
 }

  complete(input:{turnId:string;reason?:string}):AgentTurnProjection{const turn=dbRow(this.db,'SELECT * FROM agent_turns WHERE id=?',text(input.turnId,'TURN_ID'));if(!turn)fail('TURN_NOT_FOUND');const reason=input.reason===undefined?null:text(input.reason,'TERMINAL_REASON',256);if(reason&&redactContextText(reason)!==reason)fail('TERMINAL_REASON_SECRET');if(turn.status==='TERMINAL'){if((turn.terminal_reason??null)===reason)return this.projectFromCurrent(turn.id);fail('TERMINAL_REPLAY_CONFLICT')}if(dbRow(this.db,'SELECT 1 FROM agent_actions a LEFT JOIN agent_action_results r ON r.action_id=a.id WHERE a.turn_id=? AND r.id IS NULL LIMIT 1',turn.id))fail('UNRESOLVED_ACTION');const now=new Date().toISOString();this.#mutate(()=>{this.disposition(turn.id,'NONE','none',hashString(stableJson({reason})),now);this.db.prepare("UPDATE agent_turns SET status='TERMINAL',terminal_reason=?,completed_at=?,updated_at=? WHERE id=?").run(reason,now,now,turn.id)});return this.projectFromCurrent(turn.id)}
  completeWithResponsePlan(turnId:string,plan:GroundedResponsePlan):AgentTurnProjection{return this.completeResponsePlan(turnId,plan,'PI_FINAL_PENDING_GROUNDING')}
  /** Ordinary model-budget exhaustion still needs an explicit customer outcome.
   * This plan contains no ERP facts; GROUND-001 remains the only renderer and
   * outbound authorization path. Interruption/uncertain-side-effect paths do
   * not call this method and therefore remain fail-closed. */
  completeWithSafeHandoff(turnId:string):AgentTurnProjection{
    const id=text(turnId,'TURN_ID');
    return this.completeResponsePlan(id,{turnId:id,intent:'HANDOFF',connectiveText:'I’m sorry, I couldn’t complete that request. A staff member will follow up.',factClaims:[],safeReasonCode:'PI_BUDGET_EXHAUSTED_HANDOFF',handoff:{reasonCode:'PI_BUDGET_EXHAUSTED_HANDOFF'},outboundPurpose:'handoff'},'PI_BUDGET_EXHAUSTED_HANDOFF');
  }
  private completeResponsePlan(turnId:string,plan:GroundedResponsePlan,terminalReason:string):AgentTurnProjection{const id=text(turnId,'TURN_ID');validateGroundedResponsePlan(plan,id);const turn=dbRow(this.db,'SELECT * FROM agent_turns WHERE id=?',id);if(!turn)fail('TURN_NOT_FOUND');const payload=persistedJson(plan,'RESPONSE_PLAN',32768),prior=dbRow(this.db,'SELECT plan_json,plan_hash FROM agent_response_plans WHERE turn_id=?',id);if(prior){if(prior.plan_hash!==payload.hash||prior.plan_json!==payload.json)fail('RESPONSE_PLAN_REPLAY_CONFLICT');if(turn.status!=='TERMINAL'||turn.terminal_reason!==terminalReason)fail('RESPONSE_PLAN_TERMINAL_CONFLICT');return this.projectFromCurrent(id)}if(turn.status==='TERMINAL')fail('TERMINAL_MUTATION');if(dbRow(this.db,'SELECT 1 FROM agent_actions a LEFT JOIN agent_action_results r ON r.action_id=a.id WHERE a.turn_id=? AND r.id IS NULL LIMIT 1',id))fail('UNRESOLVED_ACTION');const now=new Date().toISOString();this.#mutate(()=>{this.db.prepare('INSERT INTO agent_response_plans(turn_id,plan_json,plan_hash,created_at) VALUES(?,?,?,?)').run(id,payload.json,payload.hash,now);this.disposition(id,'RUNTIME_RESPONSE',plan.outboundPurpose,payload.hash,now);this.db.prepare("UPDATE agent_turns SET status='TERMINAL',terminal_reason=?,completed_at=?,updated_at=? WHERE id=?").run(terminalReason,now,now,id)});return this.projectFromCurrent(id)}

 private projectFromCurrent(turnId:string):AgentTurnProjection{const turn=dbRow(this.db,'SELECT * FROM agent_turns WHERE id=?',turnId);if(!turn)fail('TURN_NOT_FOUND');return this.project(turnId,this.exactContext(turn))}
 private project(turnId:string,context:unknown):AgentTurnProjection{const turn=dbRow(this.db,'SELECT * FROM agent_turns WHERE id=?',turnId);if(!turn)fail('TURN_NOT_FOUND');const rows=this.db.prepare('SELECT a.id,a.sequence,a.capability_name AS capabilityName,a.capability_version AS capabilityVersion,a.arguments_json AS arguments,r.result_json AS result FROM agent_actions a LEFT JOIN agent_action_results r ON r.action_id=a.id WHERE a.turn_id=? ORDER BY a.sequence').all(turnId) as any[],actions=rows.map(a=>({id:a.id,sequence:a.sequence,capability:{name:a.capabilityName,version:a.capabilityVersion},arguments:JSON.parse(a.arguments),result:a.result?JSON.parse(a.result):null})),pending=actions.filter(a=>a.result===null).length;if((turn.status==='RECONCILE_ACTION'&&pending!==1)||(turn.status==='AWAITING_DECISION'&&pending!==0)||(turn.status==='TERMINAL'&&pending!==0))fail('TURN_LEDGER_INCONSISTENT');return freeze({turnId,status:turn.status as TurnResumeState,context:stableValue(context),actions:stableValue(actions) as AgentActionProjection[]})}
}
