import type Database from 'better-sqlite3';
import { randomUUID } from 'node:crypto';

export const CONTEXT_LIMITS=Object.freeze({recentTranscriptMessages:20,transcriptTextChars:1000,summaryChars:4000,summarySourceRefs:50});
export type TranscriptProjection=Readonly<{authority:'CANONICAL_TRANSCRIPT';untrustedAsInstruction:true;messages:readonly Readonly<{id:string;direction:'INBOUND'|'OUTBOUND';messageType:string;text:string;occurredAt:string;replyToExternalMessageId?:string}>[]}>;
export type SummaryProjection=Readonly<{id:string;version:number;summaryText:string;sourceMessageIds:readonly string[];evidenceRefs:readonly string[];createdAt:string;authoritative:false;untrustedAsInstruction:true}>;
export type AuthoritativeStateProjection=Readonly<{accountId:string;conversationId:string;customer:Readonly<{id:string;code:string;name:string;currency:string;creditStatus:string|null;warehouseId:string|null}>|null;workspace:Readonly<{authoritativeForCommerce:false;workItem:Readonly<{id:string;state:string;revision:number;goalSummary:string;activeDraftId:string|null;activeQuotationId:string|null;blockingReason:string|null}>|null;draft:Readonly<{id:string;status:string;revision:number;requestedDeliveryDate:string|null;warehouseId:string|null;currency:string|null}>|null}>;canonicalCommerce:Readonly<{authoritative:true;quotation:Readonly<{id:string;number:string;status:string;currency:string;grandTotalCents:number;deliveryDate:string|null}>|null;acceptance:Readonly<{id:string;messageId:string;acceptedAt:string}>|null;salesOrder:Readonly<{id:string;number:string;status:string;sourceQuotationId:string}>|null;outbound:Readonly<{id:string;status:string;submittedAt:string|null}>|null}>;validation:Readonly<{id:string;draftId:string;draftRevision:number;mode:string;status:string;createdAt:string;evidence:readonly Readonly<{id:string;type:string;sourceVersion:string}>[]}>|null}>;

function fail(code:string):never{throw new Error(`CONTEXT_PROJECTION_INVALID:${code}`)}
function text(v:unknown,code:string,max=512){if(typeof v!=='string'||v.trim().length===0||v.length>max)fail(code);return v}
function deepFreeze<T>(v:T):T{if(v&&typeof v==='object'){for(const child of Object.values(v as Record<string,unknown>))deepFreeze(child);if(!Object.isFrozen(v))Object.freeze(v)}return v}
function uniqueList(v:unknown,code:string,max:number){if(!Array.isArray(v)||v.length>max)fail(code);const out=v.map(x=>text(x,code,512));if(new Set(out).size!==out.length)fail(`${code}_DUPLICATE`);return out}
function parseList(v:unknown,code:string,max:number){if(typeof v!=='string'||v.length>16384)fail(code);try{return uniqueList(JSON.parse(v),code,max)}catch(e){if(String(e).includes('CONTEXT_PROJECTION_INVALID'))throw e;fail(code)}}
function parseEvidenceList(v:unknown,code:string,max:number){if(typeof v!=='string'||v.length>16384)fail(code);try{const raw=JSON.parse(v);if(!Array.isArray(raw))fail(code);return uniqueList(raw.map(x=>typeof x==='string'?x:x?.sourceId),code,max)}catch(e){if(String(e).includes('CONTEXT_PROJECTION_INVALID'))throw e;fail(code)}}
export function redactContextText(value:string){return value
 .replace(/-----BEGIN(?: [A-Z0-9]+)* PRIVATE KEY-----[\s\S]*?-----END(?: [A-Z0-9]+)* PRIVATE KEY-----/gi,'[REDACTED_PRIVATE_KEY]')
 .replace(/\bAuthorization\b\s*[:=]\s*(?:\"[^\"]*\"|'[^']*'|(?:Bearer|Basic)\s+[^\s,;}\]]+|[^\s,;}\]]+)/gi,'Authorization=[REDACTED]')
 .replace(/\bdmo_[A-Za-z0-9_-]{6,}\b/g,'[REDACTED_TOKEN]')
 .replace(/\bBearer\s+[A-Za-z0-9._~+\/-]{8,}/gi,'Bearer [REDACTED_TOKEN]')
 .replace(/([\"']?)(api[_-]?key|password|passwd|pwd|access[_-]?token|refresh[_-]?token|token|client[_-]?secret|secret)\1\s*[:=]\s*(?:\"[^\"]*\"|'[^']*'|[^\s,;}\]]+)/gi,'$2=[REDACTED]')
 .replace(/\bsk-[A-Za-z0-9_-]{8,}\b/g,'[REDACTED_TOKEN]')
 .replace(/\bgh[pousr]_[A-Za-z0-9]{20,}\b/g,'[REDACTED_TOKEN]')
 .replace(/\bAKIA[0-9A-Z]{16}\b/g,'[REDACTED_TOKEN]')}
function bounded(value:unknown,max:number){const s=typeof value==='string'?value:'';return s.length<=max?s:s.slice(0,max)}

export class ContextProjectionService{
 constructor(private readonly db:Database.Database){}
 private conversation(accountId:string,conversationId:string){text(accountId,'ACCOUNT');text(conversationId,'CONVERSATION');const row=this.db.prepare('SELECT id,customer_id FROM conversations WHERE id=? AND channel_account_id=?').get(conversationId,accountId) as {id:string;customer_id:string|null}|undefined;if(!row)fail('CONVERSATION_SCOPE');return row}
 recentTranscript(accountId:string,conversationId:string,requiredMessageId?:string):TranscriptProjection{
  this.conversation(accountId,conversationId);if(requiredMessageId!==undefined)text(requiredMessageId,'MESSAGE_ID');
  const required=requiredMessageId?this.db.prepare("SELECT rowid,id,direction,message_type,text,occurred_at,reply_to_external_message_id FROM messages WHERE id=? AND account_id=? AND conversation_id=? AND direction='INBOUND'").get(requiredMessageId,accountId,conversationId) as any:undefined;
  if(requiredMessageId&&!required)fail('MESSAGE_SCOPE');
  const messageRows=this.db.prepare('SELECT rowid,id,direction,message_type,text,occurred_at,reply_to_external_message_id FROM messages WHERE account_id=? AND conversation_id=? ORDER BY rowid DESC LIMIT ?').all(accountId,conversationId,CONTEXT_LIMITS.recentTranscriptMessages) as any[];
  const outboundRows=this.db.prepare("SELECT rowid,id,entity_type,payload_json,submitted_at,created_at FROM outbound_messages WHERE conversation_id=? AND status='SUBMITTED' AND entity_type IN ('TURN_RESPONSE','QUOTATION') ORDER BY rowid DESC LIMIT ?").all(conversationId,CONTEXT_LIMITS.recentTranscriptMessages) as any[];
  const projected:any[]=[];
  for(const row of messageRows){
    const direction=row.direction==='INBOUND'?'INBOUND' as const:row.direction==='OUTBOUND'?'OUTBOUND' as const:fail('MESSAGE_DIRECTION');
    projected.push({source:'message',rowid:Number(row.rowid),id:text(row.id,'MESSAGE_ID'),direction,messageType:text(row.message_type,'MESSAGE_TYPE',80),text:bounded(redactContextText(row.text??''),CONTEXT_LIMITS.transcriptTextChars),occurredAt:text(row.occurred_at,'MESSAGE_TIME',80),replyToExternalMessageId:row.reply_to_external_message_id?text(row.reply_to_external_message_id,'REPLY_REF'):undefined});
  }
  for(const row of outboundRows){
    let payload:any;try{payload=JSON.parse(row.payload_json)}catch{fail('OUTBOUND_TRANSCRIPT_PAYLOAD')}
    if(!payload||typeof payload!=='object'||Array.isArray(payload))fail('OUTBOUND_TRANSCRIPT_PAYLOAD');
    const rawText=row.entity_type==='TURN_RESPONSE'?payload.text:payload.customerMessage;
    if(typeof rawText!=='string'||rawText.trim().length===0)continue;
    const occurredAt=text(row.submitted_at??row.created_at,'OUTBOUND_TRANSCRIPT_TIME',80);
    projected.push({source:'outbound',rowid:Number(row.rowid),id:text(row.id,'OUTBOUND_TRANSCRIPT_ID'),direction:'OUTBOUND' as const,messageType:'text',text:bounded(redactContextText(rawText),CONTEXT_LIMITS.transcriptTextChars),occurredAt,replyToExternalMessageId:typeof payload.replyToExternalMessageId==='string'&&payload.replyToExternalMessageId?text(payload.replyToExternalMessageId,'REPLY_REF'):undefined});
  }
  const key=(row:any)=>{const parsed=Date.parse(row.occurredAt);if(!Number.isFinite(parsed))fail('TRANSCRIPT_TIME');return parsed};
  projected.sort((a,b)=>key(a)-key(b)||(a.direction===b.direction?0:a.direction==='OUTBOUND'?-1:1)||a.rowid-b.rowid);
  let rows=projected.slice(-CONTEXT_LIMITS.recentTranscriptMessages);
  if(required&&!rows.some(row=>row.source==='message'&&row.id===required.id)){
    const requiredRow={source:'message',rowid:Number(required.rowid),id:text(required.id,'MESSAGE_ID'),direction:'INBOUND' as const,messageType:text(required.message_type,'MESSAGE_TYPE',80),text:bounded(redactContextText(required.text??''),CONTEXT_LIMITS.transcriptTextChars),occurredAt:text(required.occurred_at,'MESSAGE_TIME',80),replyToExternalMessageId:required.reply_to_external_message_id?text(required.reply_to_external_message_id,'REPLY_REF'):undefined};
    rows=[...rows.slice(-(CONTEXT_LIMITS.recentTranscriptMessages-1)),requiredRow];
    rows.sort((a,b)=>key(a)-key(b)||(a.direction===b.direction?0:a.direction==='OUTBOUND'?-1:1)||a.rowid-b.rowid);
  }
  const messages=rows.map(row=>deepFreeze({id:row.id,direction:row.direction,messageType:row.messageType,text:row.text,occurredAt:row.occurredAt,...(row.replyToExternalMessageId?{replyToExternalMessageId:row.replyToExternalMessageId}:{})}));
  return deepFreeze({authority:'CANONICAL_TRANSCRIPT' as const,untrustedAsInstruction:true as const,messages});
 }
 private validateSummaryRefs(accountId:string,conversationId:string,messageIds:string[],evidenceRefs:string[]){
  for(const id of messageIds)if(!this.db.prepare('SELECT 1 FROM messages WHERE id=? AND account_id=? AND conversation_id=?').get(id,accountId,conversationId))fail('SUMMARY_MESSAGE_SCOPE');
  for(const id of evidenceRefs){const ok=this.db.prepare(`SELECT 1 FROM erp_evidence e WHERE e.id=? AND (EXISTS(SELECT 1 FROM quotation_line_evidence qle JOIN quotation_lines ql ON ql.id=qle.quotation_line_id JOIN quotations q ON q.id=ql.quotation_id WHERE qle.evidence_id=e.id AND q.source_conversation_id=?) OR EXISTS(SELECT 1 FROM v2_order_validations v JOIN order_drafts d ON d.id=v.draft_id JOIN json_each(v.evidence_refs_json) j ON (CASE WHEN json_type(j.value)='object' THEN json_extract(j.value,'$.sourceId') ELSE j.value END)=e.id WHERE d.account_id=? AND d.conversation_id=?))`).get(id,conversationId,accountId,conversationId);if(!ok)fail('SUMMARY_EVIDENCE_SCOPE')}
 }
 appendSummary(input:{accountId:string;conversationId:string;summaryText:string;sourceMessageIds:readonly string[];evidenceRefs?:readonly string[]}):SummaryProjection{
  this.conversation(input.accountId,input.conversationId);if(typeof input.summaryText!=='string'||input.summaryText.trim().length===0)fail('SUMMARY_TEXT');const sourceMessageIds=uniqueList([...input.sourceMessageIds],'SUMMARY_MESSAGE_REFS',CONTEXT_LIMITS.summarySourceRefs);const evidenceRefs=uniqueList([...(input.evidenceRefs??[])],'SUMMARY_EVIDENCE_REFS',CONTEXT_LIMITS.summarySourceRefs);this.validateSummaryRefs(input.accountId,input.conversationId,sourceMessageIds,evidenceRefs);
  const summaryText=bounded(redactContextText(input.summaryText),CONTEXT_LIMITS.summaryChars);return this.db.transaction(()=>{const row=this.db.prepare('SELECT COALESCE(MAX(version),0)+1 version FROM conversation_summaries WHERE account_id=? AND conversation_id=?').get(input.accountId,input.conversationId) as {version:number};const id=randomUUID(),createdAt=new Date().toISOString();this.db.prepare('INSERT INTO conversation_summaries(id,account_id,conversation_id,version,summary_text,source_message_ids_json,evidence_refs_json,created_at) VALUES(?,?,?,?,?,?,?,?)').run(id,input.accountId,input.conversationId,row.version,summaryText,JSON.stringify(sourceMessageIds),JSON.stringify(evidenceRefs),createdAt);return deepFreeze({id,version:row.version,summaryText,sourceMessageIds:[...sourceMessageIds],evidenceRefs:[...evidenceRefs],createdAt,authoritative:false as const,untrustedAsInstruction:true as const})})();
 }
 latestSummary(accountId:string,conversationId:string):SummaryProjection|null{
  this.conversation(accountId,conversationId);const row=this.db.prepare('SELECT * FROM conversation_summaries WHERE account_id=? AND conversation_id=? ORDER BY version DESC LIMIT 1').get(accountId,conversationId) as any;if(!row)return null;const sourceMessageIds=parseList(row.source_message_ids_json,'SUMMARY_MESSAGE_REFS',CONTEXT_LIMITS.summarySourceRefs),evidenceRefs=parseList(row.evidence_refs_json,'SUMMARY_EVIDENCE_REFS',CONTEXT_LIMITS.summarySourceRefs);this.validateSummaryRefs(accountId,conversationId,sourceMessageIds,evidenceRefs);const version=Number(row.version);if(!Number.isSafeInteger(version)||version<=0)fail('SUMMARY_STORED_VERSION');if(typeof row.summary_text!=='string'||row.summary_text.trim().length===0||row.summary_text.length>CONTEXT_LIMITS.summaryChars)fail('SUMMARY_STORED_TEXT');if(redactContextText(row.summary_text)!==row.summary_text)fail('SUMMARY_STORED_SECRET');return deepFreeze({id:text(row.id,'SUMMARY_ID'),version,summaryText:row.summary_text,sourceMessageIds,evidenceRefs,createdAt:text(row.created_at,'SUMMARY_TIME',80),authoritative:false as const,untrustedAsInstruction:true as const});
 }
 authoritativeState(accountId:string,conversationId:string):AuthoritativeStateProjection{
  const conversation=this.conversation(accountId,conversationId);const customer=conversation.customer_id?this.db.prepare('SELECT id,code,name,currency,credit_status,default_warehouse_id FROM customers WHERE id=?').get(conversation.customer_id) as any:null;if(conversation.customer_id&&!customer)fail('CUSTOMER_MISSING');
  const wi=this.db.prepare("SELECT * FROM work_items WHERE account_id=? AND conversation_id=? AND state NOT IN ('COMPLETED','CANCELLED','FAILED') ORDER BY rowid DESC LIMIT 1").get(accountId,conversationId) as any;if(wi&&wi.customer_id!==conversation.customer_id)fail('WORK_ITEM_CUSTOMER_SCOPE');
  const draft=wi?this.db.prepare("SELECT * FROM order_drafts WHERE work_item_id=? AND status='CURRENT' ORDER BY rowid DESC LIMIT 1").get(wi.id) as any:null;if(draft&&(draft.work_item_id!==wi.id||draft.account_id!==accountId||draft.conversation_id!==conversationId||draft.customer_id!==conversation.customer_id))fail('DRAFT_SCOPE');if(wi&&(wi.active_order_draft_id??null)!==(draft?.id??null))fail('WORK_ITEM_DRAFT_POINTER');
  const quote=this.db.prepare('SELECT id,quotation_no,customer_id,status,currency,grand_total_cents,delivery_date FROM quotations WHERE source_conversation_id=? ORDER BY rowid DESC LIMIT 1').get(conversationId) as any;if(quote&&quote.customer_id!==conversation.customer_id)fail('QUOTATION_CUSTOMER_SCOPE');
  const acceptance=quote?this.db.prepare('SELECT id,message_id,accepted_at FROM quotation_acceptances WHERE quotation_id=?').get(quote.id) as any:null;if(acceptance&&!this.db.prepare("SELECT 1 FROM messages WHERE id=? AND account_id=? AND conversation_id=? AND direction='INBOUND'").get(acceptance.message_id,accountId,conversationId))fail('ACCEPTANCE_MESSAGE_SCOPE');
  const so=quote?this.db.prepare('SELECT id,sales_order_no,customer_id,status,source_quotation_id,source_acceptance_message_id FROM sales_orders WHERE source_quotation_id=?').get(quote.id) as any:null;if(so&&(so.customer_id!==conversation.customer_id||so.source_quotation_id!==quote.id||!acceptance||so.source_acceptance_message_id!==acceptance.message_id))fail('SALES_ORDER_SCOPE');
  const outbound=quote?this.db.prepare("SELECT id,conversation_id,status,submitted_at FROM outbound_messages WHERE entity_type='QUOTATION' AND entity_id=? ORDER BY rowid DESC LIMIT 1").get(quote.id) as any:null;if(outbound&&outbound.conversation_id!==conversationId)fail('OUTBOUND_CONVERSATION_SCOPE');
  const validation=draft?this.db.prepare('SELECT id,draft_id,draft_revision,mode,status,evidence_refs_json,created_at FROM v2_order_validations WHERE draft_id=? ORDER BY rowid DESC LIMIT 1').get(draft.id) as any:null;let validationProjection:null|any=null;if(validation){if(validation.draft_id!==draft.id)fail('VALIDATION_DRAFT_SCOPE');const refs=parseEvidenceList(validation.evidence_refs_json,'VALIDATION_EVIDENCE_REFS',100);const evidence=refs.map(id=>{const e=this.db.prepare('SELECT id,evidence_type,source_version FROM erp_evidence WHERE id=?').get(id) as any;if(!e)fail('VALIDATION_EVIDENCE_MISSING');return{id:e.id,type:e.evidence_type,sourceVersion:e.source_version}});validationProjection={id:validation.id,draftId:validation.draft_id,draftRevision:validation.draft_revision,mode:validation.mode,status:validation.status,createdAt:validation.created_at,evidence};}
  return deepFreeze({accountId,conversationId,customer:customer?{id:customer.id,code:customer.code,name:customer.name,currency:customer.currency,creditStatus:customer.credit_status??null,warehouseId:customer.default_warehouse_id??null}:null,workspace:{authoritativeForCommerce:false as const,workItem:wi?{id:wi.id,state:wi.state,revision:wi.revision,goalSummary:bounded(wi.goal_summary,1000),activeDraftId:wi.active_order_draft_id??null,activeQuotationId:wi.active_quotation_id??null,blockingReason:wi.blocking_reason?bounded(redactContextText(wi.blocking_reason),512):null}:null,draft:draft?{id:draft.id,status:draft.status,revision:draft.current_revision,requestedDeliveryDate:draft.requested_delivery_date??null,warehouseId:draft.warehouse_id??null,currency:draft.currency??null}:null},canonicalCommerce:{authoritative:true as const,quotation:quote?{id:quote.id,number:quote.quotation_no,status:quote.status,currency:quote.currency,grandTotalCents:quote.grand_total_cents,deliveryDate:quote.delivery_date??null}:null,acceptance:acceptance?{id:acceptance.id,messageId:acceptance.message_id,acceptedAt:acceptance.accepted_at}:null,salesOrder:so?{id:so.id,number:so.sales_order_no,status:so.status,sourceQuotationId:so.source_quotation_id}:null,outbound:outbound?{id:outbound.id,status:outbound.status,submittedAt:outbound.submitted_at??null}:null},validation:validationProjection});
 }
}
