import {randomUUID} from 'node:crypto';
import {V1Database} from './database.js';
import {canonicalSha256} from './v2-canonical.js';
import {OrderDraftService,type DraftLineInput} from './v2-order-draft.js';
import {WorkItemService,workspaceFail,type AuthorityRow} from './v2-work-item.js';
import {type MigrationApproval,type MigrationApprovalAuthority,type MigrationAction,type MigrationOwner,type VerifiedMigrationApproval} from './migration-auth.js';

const now=()=>new Date().toISOString(),uid=()=>randomUUID();
const rollbackIdentity=(value:unknown,code:string):string=>{if(typeof value!=='string'||value.trim().length===0||value.length>512)workspaceFail(code);return value};
const SCHEMA='customer_order_memory.pending_order.v1';
type LegacyPending={customerId:string;accountId:string;sourceMessageId:string;senderExternalId:string;requestedDeliveryDate:string;lines:Array<{query:string;quantity:number|string;uom:string;rowItemRemark?:string}>};
type MigrationSnapshot={status:'EMPTY'|'SHADOWED'|'PROMOTED'|'ROLLED_BACK'|'CLEANED'|'QUARANTINED';error?:string;sourceHash?:string;observedSourceHash?:string;observedError?:string;workItemId?:string|null;draftId?:string|null;draftRevision?:number|null;authority:AuthorityRow};
type AuthorityPatch={migration_state:AuthorityRow['migration_state'];authoritative_writer:AuthorityRow['authoritative_writer'];work_item_id?:string|null;legacy_source_hash?:string|null;legacy_schema_version?:string|null;quarantine_reason?:string|null};

export class WorkspaceMigrationService{
  private readonly work:WorkItemService;private readonly drafts:OrderDraftService;
  private readonly approvals:MigrationApprovalAuthority;
  constructor(public readonly database:V1Database, approvals:MigrationApprovalAuthority){if(!approvals)throw Error('MIGRATION_APPROVAL_AUTHORITY_REQUIRED');this.approvals=approvals;this.work=new WorkItemService(database);this.drafts=new OrderDraftService(database,this.work)}
  private get db(){return this.database.db}
  getAuthority(accountId:string,conversationId:string){return this.work.getAuthority(accountId,conversationId)}

  private prior(accountId:string,conversationId:string,idempotencyKey:string,inputHash:string):MigrationSnapshot|undefined{
    const row=this.db.prepare("SELECT normalized_input_hash,immutable_snapshot_json FROM workspace_migration_events WHERE account_id=? AND conversation_id=? AND work_item_type='SALES_ORDER_REQUEST' AND idempotency_key=?").get(accountId,conversationId,idempotencyKey) as any;
    if(!row)return;if(row.normalized_input_hash!==inputHash)workspaceFail('IDEMPOTENCY_CONFLICT');return JSON.parse(row.immutable_snapshot_json) as MigrationSnapshot;
  }

  private mutateAuthority(a:AuthorityRow,input:{eventType:string;patch:AuthorityPatch;workItemId?:string|null;draftId?:string|null;draftRevision?:number|null;sourceHash?:string|null;idempotencyKey:string;inputHash:string;snapshot:Omit<MigrationSnapshot,'authority'>;approval:VerifiedMigrationApproval}){
    const eventId=uid(),t=now();
    const authority:AuthorityRow={...a,...input.patch,revision:a.revision+1,work_item_id:input.patch.work_item_id===undefined?a.work_item_id:input.patch.work_item_id,legacy_source_hash:input.patch.legacy_source_hash===undefined?a.legacy_source_hash:input.patch.legacy_source_hash,legacy_schema_version:input.patch.legacy_schema_version===undefined?a.legacy_schema_version:input.patch.legacy_schema_version,quarantine_reason:input.patch.quarantine_reason===undefined?a.quarantine_reason:input.patch.quarantine_reason,last_migration_event_id:eventId,updated_at:t};
    const snapshot:MigrationSnapshot={...input.snapshot,authority};
    this.db.prepare(`INSERT INTO workspace_migration_events(id,account_id,conversation_id,work_item_type,event_type,from_state,to_state,authoritative_writer,previous_event_id,work_item_id,draft_id,draft_revision,legacy_source_hash,legacy_schema_version,idempotency_key,normalized_input_hash,immutable_snapshot_json,approval_subject,approval_action,created_at) VALUES(?,?,?,'SALES_ORDER_REQUEST',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(eventId,a.account_id,a.conversation_id,input.eventType,a.migration_state,authority.migration_state,authority.authoritative_writer,a.last_migration_event_id??null,input.workItemId??authority.work_item_id??null,input.draftId??null,input.draftRevision??null,input.sourceHash??authority.legacy_source_hash??null,SCHEMA,input.idempotencyKey,input.inputHash,JSON.stringify({...snapshot,approval:{subject:input.approval.subject,action:input.approval.action}}),input.approval.subject,input.approval.action,t);
    const expected=this.db.prepare("SELECT 1 FROM workspace_authority WHERE account_id=? AND conversation_id=? AND work_item_type='SALES_ORDER_REQUEST' AND migration_state=? AND authoritative_writer=? AND revision=? AND COALESCE(last_migration_event_id,'')=COALESCE(?,'') AND COALESCE(legacy_source_hash,'')=COALESCE(?,'')").get(a.account_id,a.conversation_id,a.migration_state,a.authoritative_writer,a.revision,a.last_migration_event_id??null,a.legacy_source_hash??null);
    if(!expected)workspaceFail('MIGRATION_CONFLICT');
    const changed=this.db.prepare("UPDATE workspace_authority SET migration_state=?,authoritative_writer=?,work_item_id=?,legacy_source_hash=?,legacy_schema_version=?,quarantine_reason=?,last_migration_event_id=?,revision=?,updated_at=? WHERE account_id=? AND conversation_id=? AND revision=?").run(authority.migration_state,authority.authoritative_writer,authority.work_item_id??null,authority.legacy_source_hash??null,authority.legacy_schema_version??null,authority.quarantine_reason??null,eventId,authority.revision,t,a.account_id,a.conversation_id,a.revision);
    const observed=this.db.prepare("SELECT migration_state,authoritative_writer,revision,last_migration_event_id,legacy_source_hash FROM workspace_authority WHERE account_id=? AND conversation_id=? AND work_item_type='SALES_ORDER_REQUEST'").get(a.account_id,a.conversation_id) as any;
    if(changed.changes!==1&&(!observed||observed.revision!==authority.revision||observed.last_migration_event_id!==eventId))workspaceFail('MIGRATION_CONFLICT');return snapshot;
  }
  private approve(candidate:MigrationApproval, action:MigrationAction, owner:MigrationOwner, expected?:Omit<VerifiedMigrationApproval['descriptor'],'owner'|'action'>){const verified=this.approvals.verify(candidate,action,owner,expected);if(!verified)workspaceFail('MIGRATION_APPROVAL_REQUIRED');return verified}
  private approvalIdentity(approval:VerifiedMigrationApproval){return {subject:approval.subject,owner:approval.owner,action:approval.action,descriptor:approval.descriptor}}
  private approvalState(accountId:string,conversationId:string,customerId:string,extra:{expectedHash:string;expectedWorkItemId:string|null;expectedDraftRevision:number|null;compatibilityConfirmed:boolean|null}){const a=this.getAuthority(accountId,conversationId);return {accountId,conversationId,customerId,expectedState:a.migration_state,expectedHash:extra.expectedHash,expectedRevision:a.revision,expectedWorkItemId:extra.expectedWorkItemId,expectedDraftRevision:extra.expectedDraftRevision,compatibilityConfirmed:extra.compatibilityConfirmed};}

  private compatibilityQuarantine(a:AuthorityRow,input:{eventType:string;idempotencyKey:string;inputHash:string;approval:VerifiedMigrationApproval;observed:{hash:string;error?:string}}){
    return this.mutateAuthority(a,{eventType:input.eventType,patch:{migration_state:a.migration_state,authoritative_writer:a.authoritative_writer,legacy_source_hash:a.legacy_source_hash??null,legacy_schema_version:a.legacy_schema_version??SCHEMA,quarantine_reason:'LEGACY_COMPATIBILITY_MISMATCH'},sourceHash:input.observed.hash,idempotencyKey:input.idempotencyKey,inputHash:input.inputHash,snapshot:{status:'QUARANTINED',error:'LEGACY_COMPATIBILITY_MISMATCH',sourceHash:a.legacy_source_hash??undefined,observedSourceHash:input.observed.hash,observedError:input.observed.error,workItemId:a.work_item_id??null},approval:input.approval});
  }

  private legacyRaw(customerId:string,conversationId:string){return this.db.prepare("SELECT value_json FROM customer_order_memory WHERE customer_id=? AND memory_type='pending_order' AND key_text=? ORDER BY rowid DESC LIMIT 1").get(customerId,conversationId) as {value_json:string}|undefined}
  private parseLegacy(raw:string|undefined):{source:LegacyPending|null;hash:string;error?:string}{
    if(raw===undefined)return{source:null,hash:canonicalSha256(null)};
    let value:any;try{value=JSON.parse(raw)}catch{return{source:null,hash:canonicalSha256(raw),error:'LEGACY_SOURCE_INVALID'}}
    if(!value||typeof value!=='object'||typeof value.customerId!=='string'||typeof value.accountId!=='string'||typeof value.sourceMessageId!=='string'||typeof value.senderExternalId!=='string'||typeof value.requestedDeliveryDate!=='string'||!Array.isArray(value.lines)||!value.lines.length)return{source:null,hash:canonicalSha256(value),error:'LEGACY_SOURCE_INVALID'};
    return{source:value as LegacyPending,hash:canonicalSha256(value)};
  }
  private legacyIdentityError(source:LegacyPending,input:{accountId:string;conversationId:string;customerId:string}){
    if(source.customerId!==input.customerId||source.accountId!==input.accountId)return'LEGACY_SOURCE_SCOPE';
    const msg=this.db.prepare('SELECT sender_external_id FROM messages WHERE account_id=? AND conversation_id=? AND (id=? OR external_message_id=?)').get(input.accountId,input.conversationId,source.sourceMessageId,source.sourceMessageId) as {sender_external_id:string|null}|undefined;
    if(!msg)return'LEGACY_SOURCE_MESSAGE_SCOPE';if(msg.sender_external_id!==source.senderExternalId)return'LEGACY_SOURCE_IDENTITY_MISMATCH';return undefined;
  }
  private safeBoundary(conversationId:string){
    if(this.work.canonicalCommitment(conversationId))workspaceFail('CANONICAL_COMMITMENT_HANDOFF');
    if(this.db.prepare("SELECT 1 FROM quotations WHERE source_conversation_id=? AND status IN ('DRAFT','SENT') LIMIT 1").get(conversationId))workspaceFail('CANONICAL_WORKSPACE_RECONCILIATION_REQUIRED');
    if(this.db.prepare("SELECT 1 FROM outbound_messages WHERE conversation_id=? AND status IN ('PENDING','UNKNOWN') LIMIT 1").get(conversationId))workspaceFail('OUTBOUND_RECONCILIATION_REQUIRED');
  }
  private customerDefaults(customerId:string){const row=this.db.prepare('SELECT currency,default_warehouse_id FROM customers WHERE id=?').get(customerId) as {currency:string;default_warehouse_id:string}|undefined;if(!row)workspaceFail('CUSTOMER_SCOPE');return row}
  private exactLegacyQuantity(value:string){const n=Number(value);if(!Number.isFinite(n)||String(n)!==value)workspaceFail('ROLLBACK_QUANTITY_NOT_EXACT');return n}

  shadowImport(input:{accountId:string;conversationId:string;customerId:string;idempotencyKey:string;approval:MigrationApproval}){
    if(!input.idempotencyKey)workspaceFail('IDEMPOTENCY_KEY_REQUIRED');this.work.ensureScope(input.accountId,input.conversationId,input.customerId);
    const parsed=this.parseLegacy(this.legacyRaw(input.customerId,input.conversationId)?.value_json),a0=this.getAuthority(input.accountId,input.conversationId),candidate=this.approve(input.approval,'SHADOW_IMPORT','MIGRATION_OWNER');
    const inputHash=canonicalSha256({kind:'SHADOW_IMPORT',accountId:input.accountId,conversationId:input.conversationId,customerId:input.customerId,idempotencyKey:input.idempotencyKey,approval:this.approvalIdentity(candidate),sourceHash:parsed.hash});const replay=this.prior(input.accountId,input.conversationId,input.idempotencyKey,inputHash);if(replay)return replay;
    const approval=this.approve(input.approval,'SHADOW_IMPORT','MIGRATION_OWNER',this.approvalState(input.accountId,input.conversationId,input.customerId,{expectedHash:parsed.hash,expectedWorkItemId:a0.work_item_id??null,expectedDraftRevision:null,compatibilityConfirmed:null}));
    const result=this.database.runWorkspaceMigration(()=>{
      const a=this.getAuthority(input.accountId,input.conversationId);if(a.authoritative_writer!=='LEGACY'||!['V1_ONLY','SHADOW_IMPORT'].includes(a.migration_state))workspaceFail('INVALID_MIGRATION_STATE');
      const quarantine=(reason:string)=>this.mutateAuthority(a,{eventType:'SHADOW_IMPORT_QUARANTINE',patch:{migration_state:'SHADOW_IMPORT',authoritative_writer:'LEGACY',legacy_source_hash:parsed.hash,legacy_schema_version:SCHEMA,quarantine_reason:reason},sourceHash:parsed.hash,idempotencyKey:input.idempotencyKey,inputHash,snapshot:{status:'QUARANTINED',error:reason,sourceHash:parsed.hash},approval});
      if(parsed.error)return quarantine(parsed.error);
      let projected:{workItem:any;draft:any}|undefined;
      if(parsed.source){const identityError=this.legacyIdentityError(parsed.source,input);if(identityError)return quarantine(identityError);try{const defaults=this.customerDefaults(input.customerId),lines:DraftLineInput[]=parsed.source.lines.map((line,i)=>({lineNo:i+1,requestedWording:String(line.query??''),quantity:line.quantity,requestedUom:String(line.uom??''),rowRemark:line.rowItemRemark}));projected=this.drafts.projectShadow({accountId:input.accountId,conversationId:input.conversationId,customerId:input.customerId,sourceMessageId:parsed.source.sourceMessageId,requestedDeliveryDate:parsed.source.requestedDeliveryDate,warehouseId:defaults.default_warehouse_id,currency:defaults.currency,lines},{idempotencyKey:`${input.idempotencyKey}:draft`,sourceHash:parsed.hash})}catch(error){return quarantine(`LEGACY_PROJECTION_INVALID:${(error as Error).message}`)}}
      return this.mutateAuthority(a,{eventType:'SHADOW_IMPORT',patch:{migration_state:'SHADOW_IMPORT',authoritative_writer:'LEGACY',work_item_id:projected?.workItem.id??a.work_item_id??null,legacy_source_hash:parsed.hash,legacy_schema_version:SCHEMA,quarantine_reason:null},workItemId:projected?.workItem.id??a.work_item_id??null,draftId:projected?.draft.id??null,draftRevision:projected?.draft.current_revision??null,sourceHash:parsed.hash,idempotencyKey:input.idempotencyKey,inputHash,snapshot:{status:projected?'SHADOWED':'EMPTY',sourceHash:parsed.hash,workItemId:projected?.workItem.id??null,draftId:projected?.draft.id??null,draftRevision:projected?.draft.current_revision??null},approval});
    },input.approval,'SHADOW_IMPORT','MIGRATION_OWNER',{accountId:input.accountId,conversationId:input.conversationId,customerId:input.customerId});
    if(result.error)workspaceFail(result.error);return result;
  }

  promoteCanary(input:{accountId:string;conversationId:string;customerId:string;expectedLegacySourceHash:string;expectedWorkItemId?:string|null;expectedDraftRevision?:number|null;idempotencyKey:string;approval:MigrationApproval}){
    if(!input.idempotencyKey)workspaceFail('IDEMPOTENCY_KEY_REQUIRED');this.work.ensureScope(input.accountId,input.conversationId,input.customerId);
    const a0=this.getAuthority(input.accountId,input.conversationId),candidate=this.approve(input.approval,'PROMOTE_CANARY','V1_OWNER'),inputHash=canonicalSha256({kind:'PROMOTE_CANARY',accountId:input.accountId,conversationId:input.conversationId,customerId:input.customerId,expectedLegacySourceHash:input.expectedLegacySourceHash,expectedWorkItemId:input.expectedWorkItemId??null,expectedDraftRevision:input.expectedDraftRevision??null,idempotencyKey:input.idempotencyKey,approval:this.approvalIdentity(candidate)}),replay=this.prior(input.accountId,input.conversationId,input.idempotencyKey,inputHash);if(replay)return replay;
    const approval=this.approve(input.approval,'PROMOTE_CANARY','V1_OWNER',this.approvalState(input.accountId,input.conversationId,input.customerId,{expectedHash:input.expectedLegacySourceHash,expectedWorkItemId:input.expectedWorkItemId??null,expectedDraftRevision:input.expectedDraftRevision??null,compatibilityConfirmed:null}));
    const result=this.database.runWorkspaceMigration(()=>{
      const a=this.getAuthority(input.accountId,input.conversationId);if(a.migration_state!=='SHADOW_IMPORT'||a.authoritative_writer!=='LEGACY')workspaceFail('INVALID_MIGRATION_STATE');if(a.quarantine_reason)workspaceFail('WORKSPACE_QUARANTINED');
      const fresh=this.parseLegacy(this.legacyRaw(input.customerId,input.conversationId)?.value_json);
      const identityError=fresh.source?this.legacyIdentityError(fresh.source,input):undefined;
      const mismatch=fresh.error??identityError??(fresh.hash!==input.expectedLegacySourceHash||a.legacy_source_hash!==input.expectedLegacySourceHash?'SHADOW_HASH_MISMATCH':undefined);
      if(mismatch)return this.mutateAuthority(a,{eventType:'PROMOTE_QUARANTINE',patch:{migration_state:'SHADOW_IMPORT',authoritative_writer:'LEGACY',legacy_source_hash:fresh.hash,legacy_schema_version:SCHEMA,quarantine_reason:mismatch},sourceHash:fresh.hash,idempotencyKey:input.idempotencyKey,inputHash,snapshot:{status:'QUARANTINED',error:mismatch,sourceHash:fresh.hash},approval});
      this.safeBoundary(input.conversationId);
      const workItemId=a.work_item_id??null;if((input.expectedWorkItemId??null)!==workItemId)workspaceFail('SHADOW_WORK_ITEM_MISMATCH');
      let draftId:string|null=null,draftRevision:number|null=null;
      if(workItemId){const d=this.db.prepare("SELECT id,current_revision FROM order_drafts WHERE work_item_id=? AND status='CURRENT'").get(workItemId) as {id:string;current_revision:number}|undefined;if(d){draftId=d.id;draftRevision=d.current_revision;if((input.expectedDraftRevision??null)!==draftRevision)workspaceFail('SHADOW_DRAFT_REVISION_MISMATCH')}else{if(fresh.source)workspaceFail('SHADOW_PROJECTION_MISSING');if(input.expectedDraftRevision!=null)workspaceFail('SHADOW_DRAFT_REVISION_MISMATCH')}}else if(input.expectedDraftRevision!=null)workspaceFail('SHADOW_DRAFT_REVISION_MISMATCH');
      return this.mutateAuthority(a,{eventType:'PROMOTE_CANARY',patch:{migration_state:'V2_CANARY',authoritative_writer:'V2',legacy_source_hash:fresh.hash,legacy_schema_version:SCHEMA,quarantine_reason:null},workItemId,draftId,draftRevision,sourceHash:fresh.hash,idempotencyKey:input.idempotencyKey,inputHash,snapshot:{status:'PROMOTED',sourceHash:fresh.hash,workItemId,draftId,draftRevision},approval});
    },input.approval,'PROMOTE_CANARY','V1_OWNER',{accountId:input.accountId,conversationId:input.conversationId,customerId:input.customerId});
    if(result.error)workspaceFail(result.error);return result;
  }

  rollback(input:{accountId:string;conversationId:string;customerId:string;idempotencyKey:string;approval:MigrationApproval}){
    if(!input.idempotencyKey)workspaceFail('IDEMPOTENCY_KEY_REQUIRED');this.work.ensureScope(input.accountId,input.conversationId,input.customerId);
    const a0=this.getAuthority(input.accountId,input.conversationId),candidate=this.approve(input.approval,'ROLLBACK','V1_OWNER'),inputHash=canonicalSha256({kind:'ROLLBACK',accountId:input.accountId,conversationId:input.conversationId,customerId:input.customerId,idempotencyKey:input.idempotencyKey,approval:this.approvalIdentity(candidate)}),replay=this.prior(input.accountId,input.conversationId,input.idempotencyKey,inputHash);if(replay)return replay;
    const approval=this.approve(input.approval,'ROLLBACK','V1_OWNER',this.approvalState(input.accountId,input.conversationId,input.customerId,{expectedHash:a0.legacy_source_hash??'',expectedWorkItemId:a0.work_item_id??null,expectedDraftRevision:null,compatibilityConfirmed:null}));
    return this.database.runWorkspaceMigration(()=>{
      const a=this.getAuthority(input.accountId,input.conversationId);if(!['V2_CANARY','V2_PRIMARY'].includes(a.migration_state)||a.authoritative_writer!=='V2')workspaceFail('ROLLBACK_NOT_REQUIRED');this.safeBoundary(input.conversationId);
      let draftId:string|null=null,draftRevision:number|null=null,sourceHash:string|null=a.legacy_source_hash??null;
      if(a.work_item_id){const d=this.db.prepare("SELECT * FROM order_drafts WHERE work_item_id=? AND status='CURRENT'").get(a.work_item_id) as any;if(d){draftId=d.id;draftRevision=d.current_revision;const lines=this.db.prepare('SELECT * FROM order_draft_lines WHERE draft_id=? ORDER BY line_no').all(d.id) as any[];const msg=d.source_message_id?this.db.prepare('SELECT external_message_id,sender_external_id FROM messages WHERE id=? AND account_id=? AND conversation_id=?').get(d.source_message_id,input.accountId,input.conversationId) as any:undefined;if(!msg)workspaceFail('ROLLBACK_SOURCE_MESSAGE_REQUIRED');const sourceMessageId=rollbackIdentity(msg.external_message_id,'ROLLBACK_SOURCE_MESSAGE_IDENTITY_REQUIRED'),senderExternalId=rollbackIdentity(msg.sender_external_id,'ROLLBACK_SOURCE_SENDER_IDENTITY_REQUIRED');const pending={customerId:input.customerId,accountId:input.accountId,sourceMessageId,senderExternalId,requestedDeliveryDate:d.requested_delivery_date,lines:lines.map(line=>({query:line.requested_wording,quantity:this.exactLegacyQuantity(line.quantity),uom:line.requested_uom,rowItemRemark:line.row_remark??undefined}))};sourceHash=canonicalSha256(pending);this.db.prepare("DELETE FROM customer_order_memory WHERE customer_id=? AND memory_type='pending_order' AND key_text=?").run(input.customerId,input.conversationId);this.db.prepare('INSERT INTO customer_order_memory VALUES(?,?,?,?,?,?,?,?)').run(uid(),input.customerId,'pending_order',input.conversationId,JSON.stringify(pending),1,sourceMessageId,now())}}
      return this.mutateAuthority(a,{eventType:'ROLLBACK',patch:{migration_state:'V1_ONLY',authoritative_writer:'LEGACY',legacy_source_hash:sourceHash,legacy_schema_version:SCHEMA,quarantine_reason:null},workItemId:a.work_item_id??null,draftId,draftRevision,sourceHash, idempotencyKey:input.idempotencyKey,inputHash,snapshot:{status:'ROLLED_BACK',sourceHash:sourceHash??undefined,workItemId:a.work_item_id??null,draftId,draftRevision},approval});
    },input.approval,'ROLLBACK','V1_OWNER',{accountId:input.accountId,conversationId:input.conversationId,customerId:input.customerId});
  }

  promotePrimary(input:{accountId:string;conversationId:string;customerId:string;expectedLegacySourceHash:string;idempotencyKey:string;approval:MigrationApproval}){
    if(!input.idempotencyKey)workspaceFail('IDEMPOTENCY_KEY_REQUIRED');this.work.ensureScope(input.accountId,input.conversationId,input.customerId);
    const a0=this.getAuthority(input.accountId,input.conversationId),candidate=this.approve(input.approval,'PROMOTE_PRIMARY','MIGRATION_OWNER'),inputHash=canonicalSha256({kind:'PROMOTE_PRIMARY',accountId:input.accountId,conversationId:input.conversationId,customerId:input.customerId,expectedLegacySourceHash:input.expectedLegacySourceHash,idempotencyKey:input.idempotencyKey,approval:this.approvalIdentity(candidate)});const replay=this.prior(input.accountId,input.conversationId,input.idempotencyKey,inputHash);if(replay)return replay;
    const approval=this.approve(input.approval,'PROMOTE_PRIMARY','MIGRATION_OWNER',this.approvalState(input.accountId,input.conversationId,input.customerId,{expectedHash:input.expectedLegacySourceHash,expectedWorkItemId:a0.work_item_id??null,expectedDraftRevision:null,compatibilityConfirmed:null}));
    const result=this.database.runWorkspaceMigration(()=>{const a=this.getAuthority(input.accountId,input.conversationId);if(a.migration_state!=='V2_CANARY'||a.authoritative_writer!=='V2')workspaceFail('INVALID_MIGRATION_STATE');if(a.quarantine_reason)workspaceFail('WORKSPACE_QUARANTINED');const fresh=this.parseLegacy(this.legacyRaw(input.customerId,input.conversationId)?.value_json),identityError=fresh.source?this.legacyIdentityError(fresh.source,input):undefined;if(fresh.error||identityError||fresh.hash!==input.expectedLegacySourceHash||a.legacy_source_hash!==input.expectedLegacySourceHash)return this.compatibilityQuarantine(a,{eventType:'PROMOTE_PRIMARY_QUARANTINE',idempotencyKey:input.idempotencyKey,inputHash,approval,observed:{hash:fresh.hash,error:fresh.error??identityError}});this.safeBoundary(input.conversationId);return this.mutateAuthority(a,{eventType:'PROMOTE_PRIMARY',patch:{migration_state:'V2_PRIMARY',authoritative_writer:'V2'},workItemId:a.work_item_id??null,sourceHash:fresh.hash,idempotencyKey:input.idempotencyKey,inputHash,snapshot:{status:'PROMOTED',sourceHash:fresh.hash,workItemId:a.work_item_id??null},approval});},input.approval,'PROMOTE_PRIMARY','MIGRATION_OWNER',{accountId:input.accountId,conversationId:input.conversationId,customerId:input.customerId});
    if(result.error)workspaceFail(result.error);return result;
  }

  retireLegacy(input:{accountId:string;conversationId:string;customerId:string;expectedLegacySourceHash:string;compatibilityConfirmed:true;idempotencyKey:string;approval:MigrationApproval}){
    if(!input.idempotencyKey)workspaceFail('IDEMPOTENCY_KEY_REQUIRED');if(input.compatibilityConfirmed!==true)workspaceFail('LEGACY_COMPATIBILITY_REQUIRED');this.work.ensureScope(input.accountId,input.conversationId,input.customerId);
    const a0=this.getAuthority(input.accountId,input.conversationId),candidate=this.approve(input.approval,'RETIRE_LEGACY','MIGRATION_OWNER'),inputHash=canonicalSha256({kind:'RETIRE_LEGACY',accountId:input.accountId,conversationId:input.conversationId,customerId:input.customerId,expectedLegacySourceHash:input.expectedLegacySourceHash,compatibilityConfirmed:input.compatibilityConfirmed,idempotencyKey:input.idempotencyKey,approval:this.approvalIdentity(candidate)});const replay=this.prior(input.accountId,input.conversationId,input.idempotencyKey,inputHash);if(replay)return replay;
    const approval=this.approve(input.approval,'RETIRE_LEGACY','MIGRATION_OWNER',this.approvalState(input.accountId,input.conversationId,input.customerId,{expectedHash:input.expectedLegacySourceHash,expectedWorkItemId:a0.work_item_id??null,expectedDraftRevision:null,compatibilityConfirmed:true}));
    const result=this.database.runWorkspaceMigration(()=>{const a=this.getAuthority(input.accountId,input.conversationId);if(a.migration_state!=='V2_PRIMARY'||a.authoritative_writer!=='V2')workspaceFail('INVALID_MIGRATION_STATE');if(a.quarantine_reason)workspaceFail('WORKSPACE_QUARANTINED');const fresh=this.parseLegacy(this.legacyRaw(input.customerId,input.conversationId)?.value_json),identityError=fresh.source?this.legacyIdentityError(fresh.source,input):undefined;if(fresh.error||identityError||fresh.hash!==input.expectedLegacySourceHash||a.legacy_source_hash!==input.expectedLegacySourceHash)return this.compatibilityQuarantine(a,{eventType:'RETIRE_LEGACY_QUARANTINE',idempotencyKey:input.idempotencyKey,inputHash,approval,observed:{hash:fresh.hash,error:fresh.error??identityError}});this.safeBoundary(input.conversationId);return this.mutateAuthority(a,{eventType:'RETIRE_LEGACY',patch:{migration_state:'LEGACY_RETIRED',authoritative_writer:'V2'},workItemId:a.work_item_id??null,sourceHash:fresh.hash,idempotencyKey:input.idempotencyKey,inputHash,snapshot:{status:'PROMOTED',sourceHash:fresh.hash,workItemId:a.work_item_id??null},approval});},input.approval,'RETIRE_LEGACY','MIGRATION_OWNER',{accountId:input.accountId,conversationId:input.conversationId,customerId:input.customerId});
    if(result.error)workspaceFail(result.error);return result;
  }

  cleanupLegacy(input:{accountId:string;conversationId:string;customerId:string;expectedLegacySourceHash:string;idempotencyKey:string;approval:MigrationApproval}){
    if(!input.idempotencyKey)workspaceFail('IDEMPOTENCY_KEY_REQUIRED');this.work.ensureScope(input.accountId,input.conversationId,input.customerId);
    const a0=this.getAuthority(input.accountId,input.conversationId),candidate=this.approve(input.approval,'CLEANUP_LEGACY','MIGRATION_OWNER'),inputHash=canonicalSha256({kind:'CLEANUP_LEGACY',accountId:input.accountId,conversationId:input.conversationId,customerId:input.customerId,expectedLegacySourceHash:input.expectedLegacySourceHash,idempotencyKey:input.idempotencyKey,approval:this.approvalIdentity(candidate)}),replay=this.prior(input.accountId,input.conversationId,input.idempotencyKey,inputHash);if(replay)return replay;
    const approval=this.approve(input.approval,'CLEANUP_LEGACY','MIGRATION_OWNER',this.approvalState(input.accountId,input.conversationId,input.customerId,{expectedHash:input.expectedLegacySourceHash,expectedWorkItemId:a0.work_item_id??null,expectedDraftRevision:null,compatibilityConfirmed:null}));
    const result=this.database.runWorkspaceMigration(()=>{
      const a=this.getAuthority(input.accountId,input.conversationId);if(a.migration_state!=='LEGACY_RETIRED'||a.authoritative_writer!=='V2')workspaceFail('INVALID_MIGRATION_STATE');if(a.quarantine_reason)workspaceFail('WORKSPACE_QUARANTINED');if(a.legacy_source_hash!==input.expectedLegacySourceHash)workspaceFail('LEGACY_SOURCE_HASH_MISMATCH');
      const raw=this.legacyRaw(input.customerId,input.conversationId);if(!raw)workspaceFail('LEGACY_SOURCE_MISSING');const fresh=this.parseLegacy(raw.value_json),identityError=fresh.source?this.legacyIdentityError(fresh.source,input):undefined;if(fresh.error||identityError)workspaceFail('LEGACY_COMPATIBILITY_MISMATCH');if(fresh.hash!==input.expectedLegacySourceHash)workspaceFail('LEGACY_SOURCE_HASH_MISMATCH');
      const snapshot=this.mutateAuthority(a,{eventType:'LEGACY_CLEANUP',patch:{migration_state:'LEGACY_RETIRED',authoritative_writer:'V2',quarantine_reason:null},workItemId:a.work_item_id??null,sourceHash:fresh.hash,idempotencyKey:input.idempotencyKey,inputHash,snapshot:{status:'CLEANED',sourceHash:fresh.hash,workItemId:a.work_item_id??null},approval});
      this.db.prepare("DELETE FROM customer_order_memory WHERE customer_id=? AND memory_type='pending_order' AND key_text=?").run(input.customerId,input.conversationId);return snapshot;
    },input.approval,'CLEANUP_LEGACY','MIGRATION_OWNER',{accountId:input.accountId,conversationId:input.conversationId,customerId:input.customerId});
    if(result.error)workspaceFail(result.error);return result;
  }
}
