/** V3-GOAL-002 shadow-only, descriptive goal graph persistence. */
import {canonicalJson, canonicalSha256} from './v2-canonical.js';
import {buildConversationGoal, validateConversationGoal, type ConversationGoal} from './v3-conversation-goal.js';
import type {V1Database} from './database.js';
import type Database from 'better-sqlite3';

export const V3_GOAL_EVENT_TYPES=['CREATED','UPDATED','SUPERSEDED','CANCELLED'] as const;
export type V3GoalEventType=typeof V3_GOAL_EVENT_TYPES[number];
export const V3_GOAL_EDGE_TYPES=['PARENT','DEPENDENCY','RELATED'] as const;
export type V3GoalEdgeType=typeof V3_GOAL_EDGE_TYPES[number];
export const V3_GOAL_EDGE_EVENT_TYPES=['ADDED','REMOVED'] as const;
export type V3GoalEdgeEventType=typeof V3_GOAL_EDGE_EVENT_TYPES[number];
export type GoalGraphScope=Readonly<{accountId:string;conversationId:string}>;
export type GoalGraphEdge=Readonly<GoalGraphScope&{edgeId:string;fromGoalId:string;toGoalId:string;edgeType:V3GoalEdgeType;idempotencyKey:string;createdAt:string}>;
export type GoalGraph=Readonly<{scope:GoalGraphScope;goals:readonly ConversationGoal[];edges:readonly GoalGraphEdge[]}>;
type EventRow={event_id:string;account_id:string;conversation_id:string;goal_id:string;event_type:V3GoalEventType;goal_json:string;goal_hash:string;idempotency_key:string;created_at:string;revision:number};
type EdgeRow={edge_id:string;account_id:string;conversation_id:string;from_goal_id:string;to_goal_id:string;edge_type:V3GoalEdgeType;edge_event_type:V3GoalEdgeEventType;idempotency_key:string;created_at:string;revision:number};
const text=(v:unknown,c:string)=>{if(typeof v!=='string'||v.trim()==='')throw Error(`V3_GOAL_GRAPH_INVALID:${c}`);return v};
const timestamp=(v:unknown,c:string)=>{const s=text(v,c);if(new Date(s).toISOString()!==s)throw Error(`V3_GOAL_GRAPH_INVALID:${c}`);return s};
const one=<T extends string>(values:readonly T[],v:unknown,c:string)=>{if(!values.includes(v as T))throw Error(`V3_GOAL_GRAPH_INVALID:${c}`);return v as T};
function exact(v:unknown,required:readonly string[],optional:readonly string[]=[]){if(v===null||typeof v!=='object'||Array.isArray(v)||Object.getPrototypeOf(v)!==Object.prototype)throw Error('V3_GOAL_GRAPH_INVALID:INPUT_SHAPE');const keys=Reflect.ownKeys(v),allowed=new Set([...required,...optional]);if(keys.some(k=>typeof k!=='string'||!allowed.has(k))||required.some(k=>!keys.includes(k)))throw Error('V3_GOAL_GRAPH_INVALID:INPUT_SHAPE');const out=Object.create(null) as Record<string,unknown>;for(const k of [...required,...optional])if(keys.includes(k)){const d=Object.getOwnPropertyDescriptor(v,k);if(!d||!('value'in d)||!d.enumerable)throw Error('V3_GOAL_GRAPH_INVALID:INPUT_SHAPE');out[k]=d.value}return out}
const edgeKey=(from:string,to:string,type:string)=>`${from}\0${to}\0${type}`;
type MutationContext=Record<string,string|number>;
type MutationState={eventDepth:number;edgeDepth:number;eventContext?:MutationContext;edgeContext?:MutationContext};
const mutationStates=new WeakMap<Database.Database,MutationState>();
const ACTIVE_GOAL_STATUSES=['OPEN','IN_PROGRESS','NEEDS_CLARIFICATION','WAITING_EXTERNAL','BLOCKED_BY_AUTHORITY'] as const;
const activeGoalStatus=(status:ConversationGoal['status'])=>ACTIVE_GOAL_STATUSES.includes(status as typeof ACTIVE_GOAL_STATUSES[number]);

function mutationState(db:Database.Database):MutationState{
  const existing=mutationStates.get(db);
  if(existing)return existing;
  const state:MutationState={eventDepth:0,edgeDepth:0};
  db.function('v3_goal_event_mutation_authorized',()=>state.eventDepth>0?1:0);
  for(const[n,f]of [['id','event_id'],['account','account_id'],['conversation','conversation_id'],['goal','goal_id'],['type','event_type'],['json','goal_json'],['hash','goal_hash'],['idempotency','idempotency_key'],['created_at','created_at'],['revision','revision']]as const)db.function(`v3_goal_event_${n}`,()=>state.eventContext?.[f]??null);
  db.function('v3_goal_edge_mutation_authorized',()=>state.edgeDepth>0?1:0);
  for(const[n,f]of [['id','edge_id'],['account','account_id'],['conversation','conversation_id'],['from','from_goal_id'],['to','to_goal_id'],['type','edge_type'],['event_type','edge_event_type'],['idempotency','idempotency_key'],['created_at','created_at'],['revision','revision']]as const)db.function(`v3_goal_edge_${n}`,()=>state.edgeContext?.[f]??null);
  mutationStates.set(db,state);
  return state;
}

export class V3GoalGraphStore{
  #mutation:MutationState;
  constructor(private readonly database:V1Database){this.#mutation=mutationState(database.db)}
  appendGoalEvent(input:{scope:GoalGraphScope;eventId:string;goal:ConversationGoal;eventType:V3GoalEventType;idempotencyKey:string;createdAt:string}){const s=exact(input,['scope','eventId','goal','eventType','idempotencyKey','createdAt']),scope=exact(s.scope,['accountId','conversationId'])as GoalGraphScope,id=text(s.eventId,'EVENT_ID'),type=one(V3_GOAL_EVENT_TYPES,s.eventType,'EVENT_TYPE'),idem=text(s.idempotencyKey,'IDEMPOTENCY_KEY'),at=timestamp(s.createdAt,'CREATED_AT'),goal=validateConversationGoal(s.goal);if(goal.accountId!==scope.accountId||goal.conversationId!==scope.conversationId)throw Error('V3_GOAL_EVENT_SCOPE');const json=canonicalJson(goal),hash=canonicalSha256(goal);return this.database.runImmediate(()=>{this.#scope(scope);const prior=this.database.db.prepare('SELECT * FROM conversation_goal_events WHERE event_id=? OR idempotency_key=?').all(id,idem)as EventRow[];if(prior.length){if(prior.length===1&&prior[0].event_id===id&&prior[0].idempotency_key===idem&&prior[0].goal_json===json&&prior[0].goal_hash===hash&&prior[0].event_type===type&&prior[0].created_at===at)return prior[0];throw Error('V3_GOAL_EVENT_IDEMPOTENCY_CONFLICT')}this.#time(scope,at);const graph=this.#rebuild(scope),exists=graph.goals.some(g=>g.goalId===goal.goalId);const current=graph.goals.find(g=>g.goalId===goal.goalId);this.#lifecycle(type,current,goal);if(type==='CREATED'?exists:!exists)throw Error(type==='CREATED'?'V3_GOAL_ALREADY_EXISTS':'V3_GOAL_NOT_FOUND');const goals=new Map(graph.goals.map(g=>[g.goalId,g]));goals.set(goal.goalId,goal);this.#edges(scope,goals,graph.edges);const row={event_id:id,account_id:scope.accountId,conversation_id:scope.conversationId,goal_id:goal.goalId,event_type:type,goal_json:json,goal_hash:hash,idempotency_key:idem,created_at:at,revision:this.#next(scope)};this.#mutation.eventDepth++;const old=this.#mutation.eventContext;this.#mutation.eventContext=row;try{this.database.db.prepare('INSERT INTO conversation_goal_events(event_id,account_id,conversation_id,goal_id,event_type,goal_json,goal_hash,idempotency_key,created_at,revision) VALUES(?,?,?,?,?,?,?,?,?,?)').run(row.event_id,row.account_id,row.conversation_id,row.goal_id,row.event_type,row.goal_json,row.goal_hash,row.idempotency_key,row.created_at,row.revision)}finally{this.#mutation.eventContext=old;this.#mutation.eventDepth--}return row})}
  appendGoalEventIfCurrent(input:{scope:GoalGraphScope;eventId:string;goal:ConversationGoal;eventType:V3GoalEventType;idempotencyKey:string;createdAt:string}, expected:{goalId:string|null;revision:number|null;status:ConversationGoal['status']|null}, admissionValidator?:()=>void){
    const s=exact(input,['scope','eventId','goal','eventType','idempotencyKey','createdAt']), scope=exact(s.scope,['accountId','conversationId']) as GoalGraphScope;
    return this.database.runImmediate(()=>{
      this.#scope(scope);
      if(this.database.db.prepare('SELECT 1 FROM conversation_goal_events WHERE event_id=? OR idempotency_key=?').get(text(s.eventId,'EVENT_ID'),text(s.idempotencyKey,'IDEMPOTENCY_KEY'))) return this.#appendGoalEventInTransaction(input);
      const goal=validateConversationGoal(s.goal);
      const current=expected.goalId===null?undefined:this.database.db.prepare('SELECT goal_id,goal_json,revision FROM conversation_goal_events WHERE account_id=? AND conversation_id=? AND goal_id=? ORDER BY revision DESC LIMIT 1').get(scope.accountId,scope.conversationId,expected.goalId) as {goal_id:string;goal_json:string;revision:number}|undefined;
      if(expected.goalId===null){if(expected.revision!==null||expected.status!==null)throw Error('V3_GOAL_PROPOSAL_EXPECTATION');}
      else if(!current)throw Error('V3_GOAL_PROPOSAL_NOT_FOUND');
      else {
        const currentGoal=validateConversationGoal(JSON.parse(current.goal_json));
        if(current.revision!==expected.revision||currentGoal.status!==expected.status)throw Error('V3_GOAL_PROPOSAL_STALE');
        if(goal.createdAt!==currentGoal.createdAt)throw Error('V3_GOAL_PROPOSAL_CREATED_AT_REWRITE');
        if(new Date(goal.updatedAt).getTime()<new Date(currentGoal.updatedAt).getTime())throw Error('V3_GOAL_PROPOSAL_UPDATED_AT_REGRESSION');
      }
      admissionValidator?.();
      return this.#appendGoalEventInTransaction(input);
    });
  }
  #appendGoalEventInTransaction(input:{scope:GoalGraphScope;eventId:string;goal:ConversationGoal;eventType:V3GoalEventType;idempotencyKey:string;createdAt:string}){
    const s=exact(input,['scope','eventId','goal','eventType','idempotencyKey','createdAt']),scope=exact(s.scope,['accountId','conversationId']) as GoalGraphScope,id=text(s.eventId,'EVENT_ID'),type=one(V3_GOAL_EVENT_TYPES,s.eventType,'EVENT_TYPE'),idem=text(s.idempotencyKey,'IDEMPOTENCY_KEY'),at=timestamp(s.createdAt,'CREATED_AT'),goal=validateConversationGoal(s.goal);
    if(goal.accountId!==scope.accountId||goal.conversationId!==scope.conversationId)throw Error('V3_GOAL_EVENT_SCOPE');
    const json=canonicalJson(goal),hash=canonicalSha256(goal),prior=this.database.db.prepare('SELECT * FROM conversation_goal_events WHERE event_id=? OR idempotency_key=?').all(id,idem) as EventRow[];
    if(prior.length){if(prior.length===1&&prior[0].event_id===id&&prior[0].idempotency_key===idem&&prior[0].goal_json===json&&prior[0].goal_hash===hash&&prior[0].event_type===type&&prior[0].created_at===at)return prior[0];throw Error('V3_GOAL_EVENT_IDEMPOTENCY_CONFLICT');}
    this.#time(scope,at);const graph=this.#rebuild(scope),exists=graph.goals.some(g=>g.goalId===goal.goalId);const current=graph.goals.find(g=>g.goalId===goal.goalId);this.#lifecycle(type,current,goal);if(type==='CREATED'?exists:!exists)throw Error(type==='CREATED'?'V3_GOAL_ALREADY_EXISTS':'V3_GOAL_NOT_FOUND');const goals=new Map(graph.goals.map(g=>[g.goalId,g]));goals.set(goal.goalId,goal);this.#edges(scope,goals,graph.edges);const row={event_id:id,account_id:scope.accountId,conversation_id:scope.conversationId,goal_id:goal.goalId,event_type:type,goal_json:json,goal_hash:hash,idempotency_key:idem,created_at:at,revision:this.#next(scope)};
    this.#mutation.eventDepth++;const old=this.#mutation.eventContext;this.#mutation.eventContext=row;try{this.database.db.prepare('INSERT INTO conversation_goal_events(event_id,account_id,conversation_id,goal_id,event_type,goal_json,goal_hash,idempotency_key,created_at,revision) VALUES(?,?,?,?,?,?,?,?,?,?)').run(row.event_id,row.account_id,row.conversation_id,row.goal_id,row.event_type,row.goal_json,row.goal_hash,row.idempotency_key,row.created_at,row.revision)}finally{this.#mutation.eventContext=old;this.#mutation.eventDepth--}return row;
  }
  appendGoalEdge(input:{scope:GoalGraphScope;edgeId:string;fromGoalId:string;toGoalId:string;edgeType:V3GoalEdgeType;edgeEventType?:V3GoalEdgeEventType;idempotencyKey:string;createdAt:string}){const s=exact(input,['scope','edgeId','fromGoalId','toGoalId','edgeType','idempotencyKey','createdAt'],['edgeEventType']),scope=exact(s.scope,['accountId','conversationId'])as GoalGraphScope,id=text(s.edgeId,'EDGE_ID'),from=text(s.fromGoalId,'FROM_GOAL'),to=text(s.toGoalId,'TO_GOAL'),type=one(V3_GOAL_EDGE_TYPES,s.edgeType,'EDGE_TYPE'),op=one(V3_GOAL_EDGE_EVENT_TYPES,s.edgeEventType??'ADDED','EDGE_EVENT_TYPE'),idem=text(s.idempotencyKey,'IDEMPOTENCY_KEY'),at=timestamp(s.createdAt,'CREATED_AT');if(from===to)throw Error('V3_GOAL_EDGE_SELF');return this.database.runImmediate(()=>{this.#scope(scope);const prior=this.database.db.prepare('SELECT * FROM conversation_goal_edges WHERE edge_id=? OR idempotency_key=?').all(id,idem)as EdgeRow[];if(prior.length){if(prior.length===1&&prior[0].edge_id===id&&prior[0].idempotency_key===idem&&prior[0].from_goal_id===from&&prior[0].to_goal_id===to&&prior[0].edge_type===type&&prior[0].edge_event_type===op&&prior[0].created_at===at)return prior[0];throw Error('V3_GOAL_EDGE_IDEMPOTENCY_CONFLICT')}this.#time(scope,at);const graph=this.#rebuild(scope),k=edgeKey(from,to,type),active=new Map(graph.edges.map(e=>[edgeKey(e.fromGoalId,e.toGoalId,e.edgeType),e]));if(op==='REMOVED'&&!active.has(k))throw Error('V3_GOAL_EDGE_REMOVE_STALE');if(op==='ADDED'){if(active.has(k))throw Error('V3_GOAL_EDGE_ALREADY_ACTIVE');if(!graph.goals.some(g=>g.goalId===from)||!graph.goals.some(g=>g.goalId===to))throw Error('V3_GOAL_EDGE_GOAL_NOT_FOUND');this.#relationship(graph.goals,from,to,type)}const row={edge_id:id,account_id:scope.accountId,conversation_id:scope.conversationId,from_goal_id:from,to_goal_id:to,edge_type:type,edge_event_type:op,idempotency_key:idem,created_at:at,revision:this.#next(scope)};this.#mutation.edgeDepth++;const old=this.#mutation.edgeContext;this.#mutation.edgeContext=row;try{this.database.db.prepare('INSERT INTO conversation_goal_edges(edge_id,account_id,conversation_id,from_goal_id,to_goal_id,edge_type,edge_event_type,idempotency_key,created_at,revision) VALUES(?,?,?,?,?,?,?,?,?,?)').run(row.edge_id,row.account_id,row.conversation_id,row.from_goal_id,row.to_goal_id,row.edge_type,row.edge_event_type,row.idempotency_key,row.created_at,row.revision)}finally{this.#mutation.edgeContext=old;this.#mutation.edgeDepth--}return row})}
  #lifecycle(type:V3GoalEventType,current:ConversationGoal|undefined,next:ConversationGoal,replay=false){const valid=type==='CREATED'?!current&&next.status==='OPEN':!!current&&(type==='UPDATED'&&activeGoalStatus(current.status)&&(activeGoalStatus(next.status)||next.status==='FULFILLED')||type==='SUPERSEDED'&&activeGoalStatus(current.status)&&next.status==='SUPERSEDED'||type==='CANCELLED'&&activeGoalStatus(current.status)&&next.status==='CANCELLED');if(!valid)throw Error(replay?'V3_GOAL_HISTORY_INVALID':'V3_GOAL_EVENT_ILLEGAL_TRANSITION')}
  readGoalGraph(s:GoalGraphScope):GoalGraph{return this.database.runImmediate(()=>this.#rebuild(exact(s,['accountId','conversationId'])as GoalGraphScope))}rebuildGoalGraph(s:GoalGraphScope){return this.readGoalGraph(s)}
  #rebuild(scope:GoalGraphScope):GoalGraph{this.#scope(scope);const ev=this.database.db.prepare('SELECT * FROM conversation_goal_events WHERE account_id=? AND conversation_id=?').all(scope.accountId,scope.conversationId)as EventRow[],ee=this.database.db.prepare('SELECT * FROM conversation_goal_edges WHERE account_id=? AND conversation_id=?').all(scope.accountId,scope.conversationId)as EdgeRow[];const rows:any[]=[...ev.map(r=>({...r,kind:'G'})),...ee.map(r=>({...r,kind:'E'}))].sort((a,b)=>a.revision-b.revision||a.kind.localeCompare(b.kind));const goals=new Map<string,ConversationGoal>(),active=new Map<string,GoalGraphEdge>();let rev=0,when='';for(const r of rows){if(r.revision<=rev||r.created_at<when)throw Error('V3_GOAL_HISTORY_INVALID');rev=r.revision;when=r.created_at;if(r.kind==='G'){let g;try{g=validateConversationGoal(JSON.parse(r.goal_json))}catch{throw Error('V3_GOAL_EVENT_INTEGRITY')}if(g.goalId!==r.goal_id||g.accountId!==scope.accountId||g.conversationId!==scope.conversationId||canonicalJson(g)!==r.goal_json||canonicalSha256(g)!==r.goal_hash)throw Error('V3_GOAL_EVENT_INTEGRITY');this.#lifecycle(r.event_type,goals.get(r.goal_id),g,true);goals.set(r.goal_id,g)}else{if(r.from_goal_id===r.to_goal_id||!goals.has(r.from_goal_id)||!goals.has(r.to_goal_id))throw Error('V3_GOAL_EDGE_INTEGRITY');const k=edgeKey(r.from_goal_id,r.to_goal_id,r.edge_type);if(r.edge_event_type==='ADDED'){if(active.has(k))throw Error('V3_GOAL_EDGE_HISTORY_INVALID');this.#relationship([...goals.values()],r.from_goal_id,r.to_goal_id,r.edge_type);active.set(k,{edgeId:r.edge_id,accountId:r.account_id,conversationId:r.conversation_id,fromGoalId:r.from_goal_id,toGoalId:r.to_goal_id,edgeType:r.edge_type,idempotencyKey:r.idempotency_key,createdAt:r.created_at})}else if(r.edge_event_type==='REMOVED'){if(!active.delete(k))throw Error('V3_GOAL_EDGE_HISTORY_INVALID')}else throw Error('V3_GOAL_EDGE_INTEGRITY')}}this.#edges(scope,goals,[...active.values()]);return{scope,goals:[...goals.values()],edges:[...active.values()]}}
  #scope(s:GoalGraphScope){if(!this.database.db.prepare('SELECT 1 FROM conversations WHERE id=? AND channel_account_id=?').get(s.conversationId,s.accountId))throw Error('V3_GOAL_GRAPH_SCOPE')}
  #next(s:GoalGraphScope){return Number((this.database.db.prepare('SELECT COALESCE(MAX(revision),0)+1 AS revision FROM (SELECT revision FROM conversation_goal_events WHERE account_id=? AND conversation_id=? UNION ALL SELECT revision FROM conversation_goal_edges WHERE account_id=? AND conversation_id=?)').get(s.accountId,s.conversationId,s.accountId,s.conversationId)as{revision:number}).revision)}
  #time(s:GoalGraphScope,at:string){const r=this.database.db.prepare('SELECT MAX(created_at) AS created_at FROM (SELECT created_at FROM conversation_goal_events WHERE account_id=? AND conversation_id=? UNION ALL SELECT created_at FROM conversation_goal_edges WHERE account_id=? AND conversation_id=?)').get(s.accountId,s.conversationId,s.accountId,s.conversationId)as{created_at:string|null};if(r.created_at&&at<r.created_at)throw Error('V3_GOAL_GRAPH_BACKDATED_TIME')}
  #relationship(gs:readonly ConversationGoal[],from:string,to:string,type:V3GoalEdgeType){const g=gs.find(x=>x.goalId===from);if(!g||type==='PARENT'&&g.parentGoalId!==to||type==='DEPENDENCY'&&!g.dependsOnGoalIds.includes(to)||type==='RELATED'&&!g.relatedGoalIds.includes(to))throw Error('V3_GOAL_EDGE_SNAPSHOT_CONFLICT')}
  #edges(s:GoalGraphScope,goals:Map<string,ConversationGoal>,edges:readonly GoalGraphEdge[]){for(const e of edges){if(!goals.has(e.fromGoalId)||!goals.has(e.toGoalId))throw Error('V3_GOAL_EDGE_SNAPSHOT_CONFLICT');this.#relationship([...goals.values()],e.fromGoalId,e.toGoalId,e.edgeType)}}
}
export{buildConversationGoal};
