import {isProxy} from 'node:util/types';
import {canonicalSha256} from './v2-canonical.js';
import {getCapability} from './v2-capability-registry.js';
import type {V1Database} from './database.js';
import {projectAdaptiveInboundBundles,readAdaptiveArrivalsFromV2Receipts,validateInboundBundle, type InboundBundle} from './v3-inbound-bundle.js';
import {V3GoalGraphStore, type GoalGraph} from './v3-goal-graph.js';
import type {ConversationGoal, ErpObjectRef} from './v3-conversation-goal.js';
import type {V3ConversationMemory} from './v3-conversation-memory.js';
import {createV3RetrievalTools, type V3RetrievalToolMessage, type V3RetrievalTools} from './v3-retrieval-tools.js';
import type {V3RetrievalAttachmentRef,V3RetrievalHostAuthority,V3RetrievalHostToken,V3RetrievalIndexes,V3RetrievalScope} from './v3-retrieval-index.js';

export const V3_RETRIEVAL_LADDER_CONTRACT_VERSION='V3-RET-005';
export const V3_RETRIEVAL_LADDER_SCHEMA_VERSION=1;
export const V3_RETRIEVAL_LADDER_LAYERS=Object.freeze(['CURRENT_BUNDLE','RECENT_RAW','GOALS','SECTIONS','RAW_HISTORY','ATTACHMENTS','HISTORICAL_ERP'] as const);
export const V3_RETRIEVAL_LADDER_TOOL_NAMES=Object.freeze(['conversation_goal_list','conversation_business_objects','conversation_retrieval_ladder'] as const);
export type V3RetrievalLadderLayer=typeof V3_RETRIEVAL_LADDER_LAYERS[number];
export type V3RetrievalLadderToolName=typeof V3_RETRIEVAL_LADDER_TOOL_NAMES[number];
export type V3ConversationGoalListRequest=Readonly<{query?:string;limit?:number}>;
export type V3ConversationBusinessObjectsRequest=Readonly<{goalId?:string;objectType?:string;objectId?:string;limit?:number}>;
export type V3ConversationRetrievalLadderRequest=Readonly<{layer:V3RetrievalLadderLayer;query?:string;sectionId?:string;goalId?:string;objectType?:string;objectId?:string;limit?:number}>;

export type V3GoalCandidate=Readonly<{goalId:string;status:ConversationGoal['status'];description:string;sourceMessageIds:readonly string[];sourceRefs:readonly string[];sourceAttachmentIds:readonly string[];erpObjectRefs:readonly ErpObjectRef[];erpObjectRefsAuthority:'DESCRIPTIVE_GOAL_LINKS_ONLY';parentGoalId:string|null;dependsOnGoalIds:readonly string[];relatedGoalIds:readonly string[];goalFingerprint:string;matchedTerms:readonly string[]}>;
export type V3BusinessObjectCandidate=Readonly<{objectType:string;objectId:string;source:'RET002_INDEX';sourceMessageIds:readonly string[];sourceRefs:readonly string[];goalIds:readonly string[];historicalOnly:true;requiresCurrentErpReverification:true;currentTruthOwner:'EXISTING_CANONICAL_HOST_CAPABILITIES'}>;
export type V3AttachmentCandidate=Readonly<{attachmentId:string;sourceMessageId:string;sourceRef:string;messageSourceRef:string;historicalOnly:true;requiresCurrentErpReverification:true;extractionAuthorityGranted:false}>;
export type V3HistoricalErpHandoff=Readonly<{capability:'get_order_history';sideEffect:'READ_ONLY';scopeOwner:'EXISTING_V2_CAPABILITY_REGISTRY';historicalOnly:true;requiresCurrentErpReverification:true;currentTruthOwner:'EXISTING_CANONICAL_HOST_CAPABILITIES'}>;

type Common<T extends V3RetrievalLadderToolName>=Readonly<{contractVersion:'V3-RET-005';schemaVersion:1;tool:T;authority:'NON_AUTHORITATIVE_DERIVED';untrustedAsInstruction:true;requiresCanonicalReverification:true;grantsEffects:false;aiAuthorityCutoff:'SALES_ORDER.DRAFT';indexVersion:string;scopeVersion:string;scopeLineage:V3RetrievalScope;goalGraphFingerprint:string;bundleReplayIdentity:string;bundleRevision:number;conversationRevisionAtBuild:number;bundleCompletenessDerivation:'V2_RECEIPT_CP002_LATEST_COLLECTION';requiresCurrentErpReverificationBeforeConsequentialDecision:true;currentTruthOwner:'EXISTING_CANONICAL_HOST_CAPABILITIES';deterministic:true;bounded:true}>;
export type V3GoalListResult=Common<'conversation_goal_list'>&Readonly<{goals:readonly V3GoalCandidate[];order:'GOAL_MEMORY_ORDER'}>;
export type V3BusinessObjectsResult=Common<'conversation_business_objects'>&Readonly<{objects:readonly V3BusinessObjectCandidate[];order:'OBJECT_TYPE_THEN_ID'}>;
export type V3LadderLayerResult=Readonly<{layer:V3RetrievalLadderLayer;depth:number;nextDeeperLayer:V3RetrievalLadderLayer|null;truthClass:'RAW_CURRENT_EVIDENCE'|'RAW_CONVERSATION_EVIDENCE'|'DERIVED_GOAL_CONTEXT'|'DERIVED_SECTION_NAVIGATION'|'HISTORICAL_CONTEXT_ONLY';historicalOnly:boolean;requiresCurrentErpReverification:boolean;currentTruthOwner:'EXISTING_CANONICAL_HOST_CAPABILITIES';payload:unknown}>;
export type V3RetrievalLadderResult=Common<'conversation_retrieval_ladder'>&Readonly<{requestedLayer:V3RetrievalLadderLayer;progressiveOrder:readonly V3RetrievalLadderLayer[];result:V3LadderLayerResult}>;
export type V3RetrievalLadderTools=Readonly<{conversation_goal_list(request:V3ConversationGoalListRequest):V3GoalListResult;conversation_business_objects(request:V3ConversationBusinessObjectsRequest):V3BusinessObjectsResult;conversation_retrieval_ladder(request:V3ConversationRetrievalLadderRequest):V3RetrievalLadderResult}>;

const ALLOWED_OBJECT_TYPES=new Set(['WORK_ITEM','ORDER_DRAFT','QUOTATION','QUOTATION_ACCEPTANCE','SALES_ORDER']);
const ACTIVE_GOAL_STATUSES=new Set<ConversationGoal['status']>(['OPEN','IN_PROGRESS','NEEDS_CLARIFICATION','WAITING_EXTERNAL','BLOCKED_BY_AUTHORITY']);
const MAX_LIMIT=50,DEFAULT_LIMIT=20,MAX_NESTED_REFS=50,MAX_CURRENT_BUNDLE_MESSAGES=50,MAX_ID=256,MAX_QUERY=512,MAX_TERMS=32,MAX_OUTPUT_TEXT=6000,MAX_REF=1024,MAX_VERSION=512;
function invalid(code:string):never{throw new Error(`V3_RETRIEVAL_LADDER_INVALID:${code}`)}
function unavailable():never{throw new Error('V3_RETRIEVAL_LADDER_UNAVAILABLE')}
function freeze<T>(value:T):T{if(value&&typeof value==='object'){for(const child of Object.values(value as Record<string,unknown>))freeze(child);if(!Object.isFrozen(value))Object.freeze(value)}return value}
function bytes(value:string):number{return Buffer.byteLength(value,'utf8')}
function bounded(value:string,code:string,max=MAX_ID):string{if(typeof value!=='string'||value.trim()===''||bytes(value)>max)invalid(code);return value}
function id(value:unknown,code='ID'):string{return bounded(value as string,code,MAX_ID)}
function limit(value:unknown):number{if(value===undefined)return DEFAULT_LIMIT;if(typeof value!=='number'||!Number.isInteger(value)||value<1||value>MAX_LIMIT)invalid('LIMIT');return value}
function tokenize(value:string):string[]{return [...new Set((value.normalize('NFKC').toLocaleLowerCase('en-US').match(/[\p{L}\p{N}]+/gu)??[]))].sort()}
function query(value:unknown,optional=true):string[]{if(value===undefined&&optional)return[];if(typeof value!=='string'||value.trim()===''||bytes(value)>MAX_QUERY)invalid('QUERY');const terms=tokenize(value);if(terms.length===0||terms.length>MAX_TERMS)invalid('QUERY_TERMS');return terms}
function request(value:unknown,allowed:readonly string[]):Record<string,unknown>{if(value===null||typeof value!=='object'||Array.isArray(value)||isProxy(value)||Object.getPrototypeOf(value)!==Object.prototype)invalid('REQUEST_SHAPE');let keys:PropertyKey[],descriptors:PropertyDescriptorMap;try{keys=Reflect.ownKeys(value);descriptors=Object.getOwnPropertyDescriptors(value)}catch{invalid('REQUEST_SHAPE')}const out:Record<string,unknown>={};for(const key of keys){if(typeof key!=='string'||!allowed.includes(key))invalid('REQUEST_FIELD');const d=descriptors[key];if(!d||!('value'in d)||!d.enumerable)invalid('REQUEST_FIELD');out[key]=d.value}return out}
function scopeLineage(scope:V3RetrievalScope):V3RetrievalScope{return {tenantId:bounded(scope.tenantId,'SCOPE'),accountId:bounded(scope.accountId,'SCOPE'),channelAccountId:bounded(scope.channelAccountId,'SCOPE'),conversationId:bounded(scope.conversationId,'SCOPE'),customerId:scope.customerId===null?null:bounded(scope.customerId,'SCOPE')}}
function unique<T>(values:readonly T[]):T[]{return [...new Set(values)]}
function exactSourceRefs(messages:readonly V3RetrievalToolMessage[]):string[]{return messages.map(m=>bounded(m.sourceRef,'SOURCE_REF',MAX_REF))}
function canonicalObjectType(value:string):string{const result=bounded(value,'OBJECT_TYPE');if(!ALLOWED_OBJECT_TYPES.has(result))unavailable();return result}
function activeGoal(goal:ConversationGoal):boolean{return ACTIVE_GOAL_STATUSES.has(goal.status)}
function goalTerms(goal:ConversationGoal):Set<string>{return new Set(tokenize([goal.goalId,goal.description,goal.status,...goal.erpObjectRefs.flatMap(r=>[r.objectType,r.objectId])].join(' ')))}

class Service{
  private readonly ret4:V3RetrievalTools;
  private readonly bundle:InboundBundle;
  constructor(private readonly database:V1Database,private readonly authority:V3RetrievalHostAuthority,private readonly token:V3RetrievalHostToken,private readonly index:V3RetrievalIndexes,private readonly memory:V3ConversationMemory,bundle:InboundBundle){
    this.ret4=createV3RetrievalTools(database.db,authority,token,index,memory);
    this.bundle=validateInboundBundle(bundle);if(this.bundle.messageIds.length>MAX_CURRENT_BUNDLE_MESSAGES)invalid('CURRENT_BUNDLE_SIZE');
    if(this.bundle.accountId!==index.scope.accountId||this.bundle.conversationId!==index.scope.conversationId)unavailable();
    for(const messageId of this.bundle.messageIds)this.ret4.conversation_get_message({messageId});this.assertBundleCurrent();
    const cap=getCapability('get_order_history');if(!cap||cap.sideEffect!=='READ_ONLY')invalid('HISTORICAL_CAPABILITY');
  }
  private assertBundleCurrent():void{const ids=this.bundle.messageIds;if(ids.length===0||!['QUIET_WINDOW','HARD_CAP'].includes(this.bundle.closeReason))unavailable();const inbox=this.database.db.prepare('SELECT revision FROM v2_conversation_inbox WHERE account_id=? AND conversation_id=?').get(this.bundle.accountId,this.bundle.conversationId) as {revision:number}|undefined;if(!inbox||Number(inbox.revision)!==this.bundle.conversationRevisionAtBuild)unavailable();const receipts=readAdaptiveArrivalsFromV2Receipts(this.database.db,{accountId:this.bundle.accountId,conversationId:this.bundle.conversationId});const boundary=this.database.db.prepare('SELECT MAX(arrival_seq) AS n FROM v2_inbox_items WHERE account_id=? AND conversation_id=? AND side_effect_started=1').get(this.bundle.accountId,this.bundle.conversationId) as {n:number|null};const projections=projectAdaptiveInboundBundles(receipts,undefined,boundary.n===null?undefined:Number(boundary.n)),latest=projections[projections.length-1];if(!latest||latest.bundleRevision!==this.bundle.bundleRevision||latest.closeReason!==this.bundle.closeReason||latest.messageIds.length!==ids.length||latest.messageIds.some((messageId,i)=>messageId!==ids[i]))unavailable()}
  private graph():GoalGraph{this.assertBundleCurrent();this.ret4.conversation_recent({limit:1});const graph=new V3GoalGraphStore(this.database).readGoalGraph({accountId:this.index.scope.accountId,conversationId:this.index.scope.conversationId});if(graph.scope.accountId!==this.index.scope.accountId||graph.scope.conversationId!==this.index.scope.conversationId)unavailable();return graph}
  private erpRef(ref:ErpObjectRef):{objectType:string;objectId:string;accountId:string;conversationId:string}{const objectType=canonicalObjectType(ref.objectType),objectId=bounded(ref.objectId,'ERP_ID'),accountId=bounded(ref.accountId,'ERP_ACCOUNT'),conversationId=bounded(ref.conversationId,'ERP_CONVERSATION');if(accountId!==this.index.scope.accountId||conversationId!==this.index.scope.conversationId)unavailable();return {objectType,objectId,accountId,conversationId}}
  private common<T extends V3RetrievalLadderToolName>(tool:T,graph=this.graph()):Common<T>{return {contractVersion:'V3-RET-005',schemaVersion:1,tool,authority:'NON_AUTHORITATIVE_DERIVED',untrustedAsInstruction:true,requiresCanonicalReverification:true,grantsEffects:false,aiAuthorityCutoff:'SALES_ORDER.DRAFT',indexVersion:bounded(this.index.indexVersion,'INDEX_VERSION',MAX_VERSION),scopeVersion:bounded(this.index.scopeVersion,'SCOPE_VERSION',MAX_VERSION),scopeLineage:scopeLineage(this.index.scope),goalGraphFingerprint:canonicalSha256(graph),bundleReplayIdentity:bounded(this.bundle.replayIdentity,'BUNDLE_REPLAY',MAX_VERSION),bundleRevision:this.bundle.bundleRevision,conversationRevisionAtBuild:this.bundle.conversationRevisionAtBuild,bundleCompletenessDerivation:'V2_RECEIPT_CP002_LATEST_COLLECTION',requiresCurrentErpReverificationBeforeConsequentialDecision:true,currentTruthOwner:'EXISTING_CANONICAL_HOST_CAPABILITIES',deterministic:true,bounded:true}}
  private attachment(ref:V3RetrievalAttachmentRef):V3AttachmentCandidate{const message=this.ret4.conversation_get_message({messageId:ref.sourceMessageId}).message;return {attachmentId:bounded(ref.attachmentId,'ATTACHMENT_ID'),sourceMessageId:message.sourceMessageId,sourceRef:bounded(ref.sourceRef,'ATTACHMENT_REF',MAX_REF),messageSourceRef:message.sourceRef,historicalOnly:true,requiresCurrentErpReverification:true,extractionAuthorityGranted:false}}
  private goalCandidates(raw:unknown,graph=this.graph()):{graph:GoalGraph;goals:V3GoalCandidate[]}{
    const r=request(raw,['query','limit']),terms=query(r.query),max=limit(r.limit),attachmentIds=new Set(this.index.attachmentRefs.map(x=>x.attachmentId));
    const goals=graph.goals.filter(activeGoal).map((goal,memoryOrder)=>{if(goal.sourceMessageIds.length>MAX_NESTED_REFS||goal.sourceAttachmentIds.length>MAX_NESTED_REFS||goal.erpObjectRefs.length>MAX_NESTED_REFS||goal.dependsOnGoalIds.length>MAX_NESTED_REFS||goal.relatedGoalIds.length>MAX_NESTED_REFS)invalid('GOAL_REF_COUNT');for(const sourceMessageId of goal.sourceMessageIds)this.ret4.conversation_get_message({messageId:sourceMessageId});for(const attachmentId of goal.sourceAttachmentIds)if(!attachmentIds.has(attachmentId))unavailable();for(const ref of goal.erpObjectRefs)this.erpRef(ref);const matchedTerms=terms.filter(t=>goalTerms(goal).has(t));return {goal,memoryOrder,matchedTerms}}).filter(x=>terms.length===0||x.matchedTerms.length>0).sort((a,b)=>terms.length?(b.matchedTerms.length-a.matchedTerms.length||a.memoryOrder-b.memoryOrder):a.memoryOrder-b.memoryOrder).slice(0,max).map(({goal,matchedTerms})=>{
      const messages=goal.sourceMessageIds.map(sourceMessageId=>this.ret4.conversation_get_message({messageId:sourceMessageId}).message),refs=goal.erpObjectRefs.map(ref=>this.erpRef(ref));
      return {goalId:bounded(goal.goalId,'GOAL_ID'),status:goal.status,description:bounded(goal.description,'GOAL_DESCRIPTION',MAX_OUTPUT_TEXT),sourceMessageIds:goal.sourceMessageIds.map(x=>bounded(x,'SOURCE_MESSAGE_ID')),sourceRefs:exactSourceRefs(messages),sourceAttachmentIds:goal.sourceAttachmentIds.map(x=>bounded(x,'GOAL_ATTACHMENT')),erpObjectRefs:refs,erpObjectRefsAuthority:'DESCRIPTIVE_GOAL_LINKS_ONLY',parentGoalId:goal.parentGoalId===null?null:bounded(goal.parentGoalId,'PARENT_GOAL'),dependsOnGoalIds:goal.dependsOnGoalIds.map(x=>bounded(x,'DEPENDENCY_GOAL')),relatedGoalIds:goal.relatedGoalIds.map(x=>bounded(x,'RELATED_GOAL')),goalFingerprint:canonicalSha256(goal),matchedTerms} as V3GoalCandidate;
    });return {graph,goals};
  }
  goals(raw:unknown,graph=this.graph()):V3GoalListResult{const projected=this.goalCandidates(raw,graph);return freeze({...this.common('conversation_goal_list',graph),goals:projected.goals,order:'GOAL_MEMORY_ORDER' as const})}
  businessObjects(raw:unknown,graph=this.graph()):V3BusinessObjectsResult{
    const r=request(raw,['goalId','objectType','objectId','limit']),goalId=r.goalId===undefined?undefined:id(r.goalId,'GOAL_ID'),filterObjectType=r.objectType===undefined?undefined:canonicalObjectType(id(r.objectType,'OBJECT_TYPE')),objectId=r.objectId===undefined?undefined:id(r.objectId,'OBJECT_ID'),max=limit(r.limit),sourceMap=new Map<string,V3BusinessObjectCandidate>();
    const targetGoal=goalId?graph.goals.find(g=>g.goalId===goalId&&activeGoal(g)):undefined;if(goalId&&!targetGoal)unavailable();if(targetGoal&&targetGoal.erpObjectRefs.length>MAX_NESTED_REFS)invalid('GOAL_REF_COUNT');const allowed=targetGoal?new Set(targetGoal.erpObjectRefs.map(ref=>{const safe=this.erpRef(ref);return `${safe.objectType}\0${safe.objectId}`})):null;
    for(const entity of this.index.entities){if(entity.sourceMessageIds.length>MAX_NESTED_REFS)invalid('OBJECT_SOURCE_REF_COUNT');const key=`${entity.objectType}\0${entity.objectId}`;if(allowed&&!allowed.has(key)||filterObjectType&&entity.objectType!==filterObjectType||objectId&&entity.objectId!==objectId)continue;const messages=entity.sourceMessageIds.map(messageId=>this.ret4.conversation_get_message({messageId}).message);sourceMap.set(key,{objectType:canonicalObjectType(entity.objectType),objectId:bounded(entity.objectId,'OBJECT_ID'),source:'RET002_INDEX',sourceMessageIds:entity.sourceMessageIds.map(x=>bounded(x,'SOURCE_MESSAGE_ID')),sourceRefs:exactSourceRefs(messages),goalIds:[],historicalOnly:true,requiresCurrentErpReverification:true,currentTruthOwner:'EXISTING_CANONICAL_HOST_CAPABILITIES'})}
    for(const goal of graph.goals.filter(activeGoal)){if(goalId&&goal.goalId!==goalId)continue;if(goal.erpObjectRefs.length>MAX_NESTED_REFS)invalid('GOAL_REF_COUNT');for(const ref of goal.erpObjectRefs){const safeRef=this.erpRef(ref);if(filterObjectType&&ref.objectType!==filterObjectType||objectId&&ref.objectId!==objectId)continue;const key=`${safeRef.objectType}\0${safeRef.objectId}`,prior=sourceMap.get(key);if(!prior)unavailable();const goalIds=unique([...prior.goalIds,bounded(goal.goalId,'GOAL_ID')]);if(goalIds.length>MAX_NESTED_REFS)invalid('OBJECT_GOAL_REF_COUNT');sourceMap.set(key,{...prior,goalIds})}}
    const objects=[...sourceMap.values()].sort((a,b)=>a.objectType.localeCompare(b.objectType)||a.objectId.localeCompare(b.objectId)).slice(0,max);return freeze({...this.common('conversation_business_objects',graph),objects,order:'OBJECT_TYPE_THEN_ID' as const});
  }
  ladder(raw:unknown):V3RetrievalLadderResult{
    const r=request(raw,['layer','query','sectionId','goalId','objectType','objectId','limit']);if(typeof r.layer!=='string'||!V3_RETRIEVAL_LADDER_LAYERS.includes(r.layer as V3RetrievalLadderLayer))invalid('LAYER');const layer=r.layer as V3RetrievalLadderLayer,max=limit(r.limit),depth=V3_RETRIEVAL_LADDER_LAYERS.indexOf(layer),next=V3_RETRIEVAL_LADDER_LAYERS[depth+1]??null,graph=this.graph();let payload:unknown,truthClass:V3LadderLayerResult['truthClass'],historicalOnly=false,requires=false;
    if(layer==='CURRENT_BUNDLE'){
      if(r.query!==undefined||r.sectionId!==undefined||r.goalId!==undefined||r.objectType!==undefined||r.objectId!==undefined||r.limit!==undefined)invalid('LAYER_FIELDS');const messages=this.bundle.messageIds.map(messageId=>this.ret4.conversation_get_message({messageId}).message);payload={bundleId:bounded(this.bundle.bundleId,'BUNDLE_ID'),bundleRevision:this.bundle.bundleRevision,conversationRevisionAtBuild:this.bundle.conversationRevisionAtBuild,messages,truncated:false};truthClass='RAW_CURRENT_EVIDENCE';
    }else if(layer==='RECENT_RAW'){
      if(r.query!==undefined||r.sectionId!==undefined||r.goalId!==undefined||r.objectType!==undefined||r.objectId!==undefined)invalid('LAYER_FIELDS');payload=this.ret4.conversation_recent({limit:max});truthClass='RAW_CONVERSATION_EVIDENCE';
    }else if(layer==='GOALS'){
      if(r.sectionId!==undefined||r.objectType!==undefined||r.objectId!==undefined||r.goalId!==undefined)invalid('LAYER_FIELDS');payload=this.goals({...(r.query===undefined?{}:{query:r.query as string}),limit:max},graph);truthClass='DERIVED_GOAL_CONTEXT';
    }else if(layer==='SECTIONS'){
      if(r.sectionId!==undefined||r.goalId!==undefined||r.objectType!==undefined||r.objectId!==undefined)invalid('LAYER_FIELDS');payload=this.ret4.conversation_find_sections({...(r.query===undefined?{}:{query:r.query as string}),limit:max});truthClass='DERIVED_SECTION_NAVIGATION';
    }else if(layer==='RAW_HISTORY'){
      if(r.goalId!==undefined||r.objectType!==undefined||r.objectId!==undefined||(r.query===undefined)===(r.sectionId===undefined))invalid('LAYER_FIELDS');payload=r.sectionId!==undefined?this.ret4.conversation_open_section({sectionId:id(r.sectionId,'SECTION_ID'),limit:max}):this.ret4.conversation_search({query:bounded(r.query as string,'QUERY',MAX_QUERY),limit:max});truthClass='RAW_CONVERSATION_EVIDENCE';historicalOnly=true;requires=true;
    }else if(layer==='ATTACHMENTS'){
      if(r.query!==undefined||r.sectionId!==undefined||r.objectType!==undefined||r.objectId!==undefined)invalid('LAYER_FIELDS');let refs=this.index.attachmentRefs;if(r.goalId!==undefined){const goalId=id(r.goalId,'GOAL_ID'),goal=graph.goals.find(g=>g.goalId===goalId&&activeGoal(g));if(!goal)unavailable();if(goal.sourceAttachmentIds.length>MAX_NESTED_REFS)invalid('GOAL_REF_COUNT');const allow=new Set(goal.sourceAttachmentIds);refs=refs.filter(x=>allow.has(x.attachmentId));for(const expected of allow)if(!refs.some(x=>x.attachmentId===expected))unavailable()}payload={attachments:refs.slice(0,max).map(ref=>this.attachment(ref)),truncated:refs.length>max};truthClass='HISTORICAL_CONTEXT_ONLY';historicalOnly=true;requires=true;
    }else{
      if(r.query!==undefined||r.sectionId!==undefined)invalid('LAYER_FIELDS');const objects=this.businessObjects({...(r.goalId===undefined?{}:{goalId:r.goalId as string}),...(r.objectType===undefined?{}:{objectType:r.objectType as string}),...(r.objectId===undefined?{}:{objectId:r.objectId as string}),limit:max},graph);const capability=getCapability('get_order_history')!;const handoff:V3HistoricalErpHandoff={capability:'get_order_history',sideEffect:'READ_ONLY',scopeOwner:'EXISTING_V2_CAPABILITY_REGISTRY',historicalOnly:true,requiresCurrentErpReverification:true,currentTruthOwner:'EXISTING_CANONICAL_HOST_CAPABILITIES'};if(capability.name!=='get_order_history'||capability.sideEffect!=='READ_ONLY')invalid('HISTORICAL_CAPABILITY');payload={objects:objects.objects,capabilityHandoff:handoff};truthClass='HISTORICAL_CONTEXT_ONLY';historicalOnly=true;requires=true;
    }
    const result:V3LadderLayerResult={layer,depth,nextDeeperLayer:next,truthClass,historicalOnly,requiresCurrentErpReverification:requires,currentTruthOwner:'EXISTING_CANONICAL_HOST_CAPABILITIES',payload};return freeze({...this.common('conversation_retrieval_ladder',graph),requestedLayer:layer,progressiveOrder:[...V3_RETRIEVAL_LADDER_LAYERS],result});
  }
}

export function createV3RetrievalLadderTools(database:V1Database,authority:V3RetrievalHostAuthority,token:V3RetrievalHostToken,index:V3RetrievalIndexes,memory:V3ConversationMemory,bundle:InboundBundle):V3RetrievalLadderTools{
  const service=new Service(database,authority,token,index,memory,bundle);return Object.freeze({conversation_goal_list:(r)=>service.goals(r),conversation_business_objects:(r)=>service.businessObjects(r),conversation_retrieval_ladder:(r)=>service.ladder(r)});
}
